(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* The firmware and boot-image parsing layer of the driver-less NVIDIA boot
   chain, on hand-built synthetic images: the VBIOS FWSEC walk and its FRTS
   patch and signature splice, the heavy-secured booter and RISC-V
   bootloader header parses, the chain-of-trust ELF split, the pure page
   hierarchy, and the sha-verified firmware loader over a temporary
   directory standing in for the firmware root. The RPC message queue runs
   over anonymous memory standing in for the shared queue pages, with frame
   goldens (checksums, element counts, byte placement) generated by driving
   the pinned reference implementation over the same inputs; run_cpu_seq
   runs over scripted registers and clock. *)

open Windtrap
module Ip = Tolk_nv.Ip
module Rpc_queue = Tolk_nv.Ip.Rpc_queue
module Tables = Tolk_nv.Nv_tables
module Gsp_defs = Tolk_nv.Nv_tables.Gsp_defs
module Mmio = Tolk_hcq.Hcq.Mmio
module File_io = Tolk_hcq.Hcq.File_io

(* Little-endian byte pokes for building fixtures. *)
let set8 b off v = Bytes.set_uint8 b off (v land 0xff)
let set16 b off v = Bytes.set_uint16_le b off (v land 0xffff)
let set32 b off v = Bytes.set_int32_le b off (Int32.of_int (v land 0xffffffff))
let set64 b off v = Bytes.set_int64_le b off (Int64.of_int v)
let get32 b off = Int32.to_int (Bytes.get_int32_le b off) land 0xffffffff
let get64 b off = Int64.to_int (Bytes.get_int64_le b off)

let hex digest =
  let n = Bytes.length digest in
  let out = Bytes.create (n * 2) in
  for i = 0 to n - 1 do
    let v = Bytes.get_uint8 digest i in
    Bytes.set out (2 * i) "0123456789abcdef".[v lsr 4];
    Bytes.set out ((2 * i) + 1) "0123456789abcdef".[v land 0xf]
  done;
  Bytes.unsafe_to_string out

let contains ~needle haystack =
  let nl = String.length needle and hl = String.length haystack in
  if nl = 0 then true
  else
    let rec loop i =
      if i + nl > hl then false
      else if String.sub haystack i nl = needle then true
      else loop (i + 1)
    in
    loop 0

let raises_failure_with subs f =
  raises_match
    (function
      | Failure m -> List.for_all (fun n -> contains ~needle:n m) subs
      | _ -> false)
    f

let raises_timeout_with subs f =
  raises_match
    (function
      | Ip.Timeout_error m -> List.for_all (fun n -> contains ~needle:n m) subs
      | _ -> false)
    f

(* Anonymous memory standing in for the shared queue pages. *)
let with_mem size f =
  let addr =
    File_io.mmap ~addr:0n ~size
      ~prot:(File_io.prot_read lor File_io.prot_write)
      ~flags:(File_io.map_private lor File_io.map_anonymous)
      ~fd:(-1) ~offset:0L
  in
  Fun.protect
    ~finally:(fun () -> File_io.munmap addr ~size)
    (fun () -> f (Mmio.make ~addr ~size))

let m32 m off = Int32.to_int (Mmio.read32 m off) land 0xffffffff

(* The transmit header at the start of a queue's memory: size@0x4,
   msgSize@0x8, msgCount@0xc, writePtr@0x10, flags@0x14, rxHdrOff@0x18,
   entryOff@0x1c (ip.py:383, layout from the generated tables). *)
let init_tx m ~size ~msg_size ~msg_count ~write_ptr ~rx_hdr_off =
  let hdr = Bytes.make 0x20 '\000' in
  set32 hdr 0x4 size;
  set32 hdr 0x8 msg_size;
  set32 hdr 0xc msg_count;
  set32 hdr 0x10 write_ptr;
  set32 hdr 0x14 1;
  set32 hdr 0x18 rx_hdr_off;
  set32 hdr 0x1c 0x1000;
  Mmio.blit_bytes m ~off:0 hdr

(* A queue's memory with its header published: a 0x1000-byte header
   region then the element ring. *)
let with_queue ~msg_size ~msg_count ?(write_ptr = 0) f =
  let size = 0x1000 + (msg_size * msg_count) in
  with_mem size (fun m ->
      init_tx m ~size ~msg_size ~msg_count ~write_ptr ~rx_hdr_off:0x20;
      f m)

let mk_queue ?completion_q_view ?now_ms ?(doorbells = ref 0)
    ?(on_seq = fun _ -> ()) ?(on_err = fun () -> ()) view =
  Rpc_queue.make ?completion_q_view ?now_ms ~devfmt:"test"
    ~notify:(fun () -> incr doorbells)
    ~on_run_cpu_seq:on_seq ~on_error:on_err view

(* A clock that advances one millisecond per reading, so timeout paths
   consume no wall time. *)
let fake_clock () =
  let t = ref 0 in
  fun () ->
    incr t;
    !t

(* A message frame as the GSP publishes it into the status ring: element
   header, RPC header, payload, zero-padded to whole elements. The
   element checksum stays zero; the consumer never reads it. *)
let gsp_frame ~msg_size ~func ?(result = 0) ?(seq = 0) payload =
  let total = 0x30 + 0x20 + Bytes.length payload in
  let elems = (total + msg_size - 1) / msg_size in
  let b = Bytes.make (elems * msg_size) '\000' in
  set32 b 0x24 seq;
  set32 b 0x28 elems;
  set32 b 0x30 0x03000000 (* header version *);
  set32 b 0x34 0x43505256 (* signature *);
  set32 b 0x38 (Bytes.length payload + 0x20) (* length *);
  set32 b 0x3c func;
  set32 b 0x40 result;
  set32 b 0x44 result;
  Bytes.blit payload 0 b 0x50 (Bytes.length payload);
  b

(* The command-sequence buffer run_cpu_seq interprets: a 0x28-byte
   header whose word at 0x4 counts the command words that follow. *)
let seq_buf ?cmd_index cmds =
  let b = Bytes.make (0x28 + (4 * List.length cmds)) '\000' in
  set32 b 4 (Option.value ~default:(List.length cmds) cmd_index);
  List.iteri (fun i c -> set32 b (0x28 + (4 * i)) c) cmds;
  b

(* Interpret [cmds] over scripted registers, logging reads and writes
   chronologically as ["r:addr:value"] / ["w:addr:value"]. *)
let run_seq ?(rreg = fun _ -> 0) ?(sleep_us = fun _ -> ())
    ?(core = fun (_ : string) -> ()) ?cmd_index cmds =
  let log = ref [] in
  let rreg a =
    let v = rreg a in
    log := Printf.sprintf "r:%x:%x" a v :: !log;
    v
  in
  let wreg a v = log := Printf.sprintf "w:%x:%x" a v :: !log in
  Ip.Gsp.run_cpu_seq ~rreg ~wreg ~now_ms:(fake_clock ()) ~sleep_us
    ~core_reset:(fun () -> core "reset")
    ~core_start:(fun () -> core "start")
    ~core_wait_halted:(fun () -> core "halt")
    ~core_resume:(fun () -> core "resume")
    (seq_buf ?cmd_index cmds);
  List.rev !log

(* A synthetic VBIOS ROM shaped like the on-board image the FWSEC walk
   expects: two PCI expansion-ROM images (a base then the extended one, so
   the extended base resolves to 0), a BIT header at 0x1b0 with one falcon
   data token, a one-entry ucode table pointing at a production FWSEC
   descriptor, then the descriptor, its 0x180-byte signature, and the
   FWSEC image carrying an application interface with a DMEM mapper. *)
let build_vbios () =
  let rom = Bytes.make 0x800 '\000' in
  (* PCI image 0 (base): pci data at 0x100, 2 blocks of 0x200 = 0x400. *)
  set16 rom 0x18 0x100;
  set16 rom 0x110 2;
  set8 rom 0x114 0 (* VBIOS_BASE *);
  (* PCI image 1 (extended) at 0x400: pci data at 0x100, extended code. *)
  set16 rom 0x418 0x100;
  set8 rom 0x514 0xe0 (* VBIOS_EXT -> expansion base 0x400 - 0x400 = 0 *);
  (* BIT header at 0x1b0. *)
  set32 rom 0x1b2 0x00544942 (* "BIT" *);
  set8 rom 0x1b8 0xc (* header size *);
  set8 rom 0x1b9 8 (* token size *);
  set8 rom 0x1ba 1 (* token entries *);
  (* Falcon data token at 0x1b0 + 0xc = 0x1bc. *)
  set8 rom 0x1bc 0x70 (* BIT_TOKEN_FALCON_DATA *);
  set8 rom 0x1bd 2 (* data version *);
  set16 rom 0x1be 4 (* data size *);
  set32 rom 0x1c0 0x1d0 (* data ptr *);
  (* Falcon data at 0x1d0: ucode table ptr. *)
  set32 rom 0x1d0 0x1e0;
  (* Ucode table header at 0x1e0. *)
  set8 rom 0x1e1 6 (* header size *);
  set8 rom 0x1e2 6 (* entry size *);
  set8 rom 0x1e3 1 (* entry count *);
  (* Ucode entry 0 at 0x1e0 + 6 = 0x1e6. *)
  set8 rom 0x1e6 0x85 (* FWSEC_PROD *);
  set32 rom 0x1e8 0x200 (* desc ptr *);
  (* Ucode descriptor at 0x200. vDesc high half is the descriptor size. *)
  let desc_size = 0x1ac in
  set32 rom 0x200 (desc_size lsl 16);
  set32 rom 0x204 0x300 (* stored size *);
  set32 rom 0x208 0x80 (* pkc data offset *);
  set32 rom 0x20c 0x00 (* interface offset *);
  set32 rom 0x210 0x1000 (* imem phys base *);
  set32 rom 0x214 0x100 (* imem load size *);
  set32 rom 0x218 0x2000 (* imem virt base *);
  set32 rom 0x21c 0x3000 (* dmem phys base *);
  set32 rom 0x220 0x200 (* dmem load size *);
  set16 rom 0x224 0x5 (* engine id mask *);
  set8 rom 0x226 0x3 (* ucode id *);
  (* Signature: 0x180 bytes at desc + 0x2c = 0x22c. *)
  for i = 0 to 0x17f do
    set8 rom (0x22c + i) ((i + 0x11) land 0xff)
  done;
  (* FWSEC image at desc + desc_size = 0x3ac, length round_up(0x300,256). *)
  let image_start = 0x3ac in
  (* Application interface header at imem_load_size + interface_offset. *)
  set8 rom (image_start + 0x103) 1 (* entry count *);
  set32 rom (image_start + 0x104) 4 (* entry id = DMEMMAPPER *);
  set32 rom (image_start + 0x108) 0x10 (* dmem offset *);
  (* DMEM mapper at imem_load_size + dmem_offset = 0x110. *)
  set32 rom (image_start + 0x118) 0x50 (* cmd in buffer offset *);
  rom

(* A heavy-secured booter container: an nvfw binary header pointing at a
   heavy-secure header, whose load header and app entry carry the data and
   code spans, and whose patch points name where the production signature
   is spliced into the extracted image. *)
let build_booter () =
  let blob = Bytes.make 0x200 '\000' in
  set32 blob 0xc 0x40 (* header_offset -> hs header *);
  set32 blob 0x10 0x100 (* data_offset *);
  set32 blob 0x14 0x80 (* data_size *);
  (* u32 cells the hs header points at for the patch values. *)
  set32 blob 0x20 0x10 (* patch_loc value *);
  set32 blob 0x24 0x8 (* patch_sig value *);
  set32 blob 0x28 1 (* num_sig value *);
  (* hs header at 0x40. *)
  set32 blob 0x40 0xc0 (* sig_prod_offset *);
  set32 blob 0x44 0x10 (* sig_prod_size *);
  set32 blob 0x48 0x20 (* patch_loc cell *);
  set32 blob 0x4c 0x24 (* patch_sig cell *);
  set32 blob 0x58 0x28 (* num_sig cell *);
  set32 blob 0x5c 0x80 (* header_offset -> load header *);
  (* load header at 0x80. *)
  set32 blob 0x88 0x10 (* os_data_offset *);
  set32 blob 0x8c 0x20 (* os_data_size *);
  (* app at 0x80 + 0x14 = 0x94. *)
  set32 blob 0x94 0x30 (* code offset *);
  set32 blob 0x98 0x40 (* code size *);
  (* signature bytes: sig_prod_offset + patch_sig = 0xc8, length 0x10. *)
  for j = 0 to 0xf do
    set8 blob (0xc8 + j) ((0x40 + j) land 0xff)
  done;
  blob

(* A RISC-V bootloader container: nvfw header pointing at a ucode
   descriptor with the monitor code, data and manifest offsets. *)
let build_bootloader () =
  let blob = Bytes.make 0x100 '\000' in
  set32 blob 0xc 0x40 (* header_offset -> ucode desc *);
  set32 blob 0x10 0x80 (* data_offset *);
  set32 blob 0x14 0x40 (* data_size *);
  (* RM_RISCV_UCODE_DESC at 0x40: manifest 0x20, data 0x28, code 0x30. *)
  set32 blob (0x40 + 0x20) 0x111 (* manifest offset *);
  set32 blob (0x40 + 0x28) 0x222 (* monitor data offset *);
  set32 blob (0x40 + 0x30) 0x333 (* monitor code offset *);
  blob

(* A minimal 64-bit little-endian ELF (ET_DYN) carrying the named program
   sections, so the chain-of-trust split has real sections to find. *)
let build_elf sections =
  let buf = Buffer.create 1024 in
  Buffer.add_bytes buf (Bytes.make 64 '\000');
  let pad_to align =
    while Buffer.length buf mod align <> 0 do
      Buffer.add_char buf '\000'
    done
  in
  let add content =
    pad_to 8;
    let off = Buffer.length buf in
    Buffer.add_bytes buf content;
    off
  in
  let offs = List.map (fun (_, c) -> add c) sections in
  let shstr = Buffer.create 64 in
  Buffer.add_char shstr '\000';
  let name s =
    let o = Buffer.length shstr in
    Buffer.add_string shstr s;
    Buffer.add_char shstr '\000';
    o
  in
  let names = List.map (fun (n, _) -> name n) sections in
  let n_shstr = name ".shstrtab" in
  let off_shstr = add (Buffer.to_bytes shstr) in
  pad_to 8;
  let e_shoff = Buffer.length buf in
  let shdr ~nm ~ty ~off ~size =
    let b = Bytes.make 64 '\000' in
    set32 b 0 nm;
    set32 b 4 ty;
    set64 b 24 off;
    set64 b 32 size;
    set64 b 48 1;
    Buffer.add_bytes buf b
  in
  shdr ~nm:0 ~ty:0 ~off:0 ~size:0;
  List.iter2
    (fun (_, c) (nm, off) -> shdr ~nm ~ty:1 ~off ~size:(Bytes.length c))
    sections
    (List.combine names offs);
  shdr ~nm:n_shstr ~ty:3 ~off:off_shstr ~size:(Buffer.length shstr);
  let obj = Buffer.to_bytes buf in
  Bytes.blit_string "\x7fELF\x02\x01\x01" 0 obj 0 7;
  set16 obj 16 3 (* ET_DYN *);
  set16 obj 18 0xB7 (* AArch64 *);
  set32 obj 20 1;
  set64 obj 40 e_shoff;
  set16 obj 52 64;
  set16 obj 58 64;
  set16 obj 60 (List.length sections + 2);
  set16 obj 62 (List.length sections + 1);
  obj

let mkdir_p path =
  let rec go p =
    if not (Sys.file_exists p) then begin
      go (Filename.dirname p);
      (try Sys.mkdir p 0o755 with Sys_error _ -> ())
    end
  in
  go path

let write_file path content =
  Out_channel.with_open_bin path (fun oc -> Out_channel.output_string oc content)

(* The falcon execution layer, on a scripted device: a register file over
   a hashtable with per-address read hooks and a chronological write log,
   an anonymous mapping standing in for the VRAM BAR, and a clock that
   advances one millisecond per reading so the boot delays consume no wall
   time. The primitives are driven directly and their register traffic
   checked against hand-computed goldens; init_sw and init_hw compose them
   over parsed firmware and are exercised only on real hardware. *)

module Nvdev = Tolk_nv.Nvdev
module Nv_reg = Nvdev.Nv_reg

let falcon_base = 0x00110000
let sec2_base = 0x00840000

type fake = {
  dev : Nvdev.t;
  reads : (int, unit -> int) Hashtbl.t;
  log : (int * int) list ref;
}

let with_fake_dev ?(arch = 0x17) ?(impl = 2) ?(boot0 = 0x174000a1) f =
  with_mem 0x5000000 (fun fvram ->
      let store = Hashtbl.create 64 in
      let reads = Hashtbl.create 64 in
      let log = ref [] in
      let clock = ref 0 in
      Hashtbl.replace store 0x0 boot0 (* NV_PMC_BOOT_0 *);
      Hashtbl.replace store 0xa00 ((arch lsl 24) lor (impl lsl 20))
      (* NV_PMC_BOOT_42 *);
      Hashtbl.replace store 0x1183a4 80 (* SCRATCH_GROUP_42: 80MB *);
      let rreg addr =
        match Hashtbl.find_opt reads addr with
        | Some hook -> hook ()
        | None -> Option.value ~default:0 (Hashtbl.find_opt store addr)
      in
      let wreg addr v =
        log := (addr, v) :: !log;
        Hashtbl.replace store addr v
      in
      let dev =
        Nvdev.make
          ~now_ms:(fun () ->
            incr clock;
            !clock)
          ~bar1_base:0x40000000 ~rreg ~wreg
          ~mmio:(Mmio.view fvram ~off:0 ~size:0x1000 ())
          ~vram:fvram ~devfmt:"test" ()
      in
      f { dev; reads; log })

(* The write log in the order the primitives issued it. *)
let writes fd = List.rev !(fd.log)

(* The write log as [addr:value] hex pairs, for goldens. *)
let show_writes fd =
  List.map (fun (a, v) -> Printf.sprintf "%x:%x" a v) (writes fd)

(* The falcon register families init_sw would resolve, included up front
   so the primitives can be driven on their own. *)
let include_falcon fd =
  List.iter
    (fun (family, arch) -> Nvdev.include_regs fd.dev ~family ~arch)
    [
      ("dev_gsp", "ga102"); ("dev_falcon_v4", "ga102");
      ("dev_riscv_pri", "ga102"); ("dev_fbif_v4", "ga102");
      ("dev_falcon_second_pri", "ga102"); ("dev_sec_pri", "ga102");
      ("dev_bus", "tu102");
    ]

let addr_of fd ?base ?idx name =
  let r = Nvdev.reg fd.dev name in
  let r = match base with Some b -> Nv_reg.with_base r b | None -> r in
  let r = match idx with Some i -> Nv_reg.with_idx r i | None -> r in
  Nv_reg.addr r

(* Install a constant read-back at a register's resolved address. *)
let set_read fd ?base ?idx name v =
  Hashtbl.replace fd.reads (addr_of fd ?base ?idx name) (fun () -> v)

let () =
  run "Nv_ip"
    [
      group "vbios fwsec"
        [
          test "descriptor fields parse out of the ucode table" (fun () ->
              let u = Ip.Flcn.prep_ucode ~rom:(build_vbios ()) ~vram_size:0x10000000 in
              equal int 0x100 u.desc.imem_load_size;
              equal int 0x1000 u.desc.imem_phys_base;
              equal int 0x2000 u.desc.imem_virt_base;
              equal int 0x3000 u.desc.dmem_phys_base;
              equal int 0x200 u.desc.dmem_load_size;
              equal int 0x80 u.desc.pkc_data_offset;
              equal int 0x5 u.desc.engine_id_mask;
              equal int 0x3 u.desc.ucode_id;
              equal int 0x300 u.desc.stored_size;
              equal int 0 u.desc.interface_offset);
          test "frts offset is the top 1 MiB of the 2 MiB reservation"
            (fun () ->
              let u = Ip.Flcn.prep_ucode ~rom:(build_vbios ()) ~vram_size:0x10000000 in
              (* vram_size - 0x100000 - 0x100000 *)
              equal int 0xfe00000 u.frts_offset;
              equal int 0x300 (Bytes.length u.frts_image));
          test "the dmem mapper is patched to select the frts command"
            (fun () ->
              let u = Ip.Flcn.prep_ucode ~rom:(build_vbios ()) ~vram_size:0x10000000 in
              (* init_cmd at imem_load_size + dmem_offset + 0x2c = 0x13c *)
              equal int 0x15 (get32 u.frts_image 0x13c));
          test "the frts command is spliced into the input buffer" (fun () ->
              let u = Ip.Flcn.prep_ucode ~rom:(build_vbios ()) ~vram_size:0x10000000 in
              (* cmd buffer at imem_load_size + cmd_in_buffer_offset = 0x150 *)
              equal int 1 (get32 u.frts_image 0x150) (* read desc version *);
              equal int 0x18 (get32 u.frts_image 0x154) (* read desc size *);
              equal int 2 (get32 u.frts_image 0x164) (* read desc flags *);
              equal int 1 (get32 u.frts_image 0x168) (* region version *);
              equal int 0x14 (get32 u.frts_image 0x16c) (* region size field *);
              equal int 0xfe00 (get32 u.frts_image 0x170) (* offset >> 12 *);
              equal int 0x100 (get32 u.frts_image 0x174) (* region byte size *);
              equal int 2 (get32 u.frts_image 0x178) (* media type *));
          test "the signature is spliced over the pkc data region" (fun () ->
              let u = Ip.Flcn.prep_ucode ~rom:(build_vbios ()) ~vram_size:0x10000000 in
              (* sig at imem_load_size + pkc_data_offset = 0x180 *)
              let expected =
                String.init 0x180 (fun i -> Char.chr ((i + 0x11) land 0xff))
              in
              equal string expected
                (Bytes.sub_string u.frts_image 0x180 0x180));
        ];
      group "read_vbios"
        [
          test "assembles the register window little-endian" (fun () ->
              let b = Ip.Flcn.read_vbios ~read32:(fun a -> a lsr 2) in
              equal int 0x100000 (Bytes.length b);
              (* word i is read32 (0x300000 + i*4) = 0xc0000 + i *)
              equal int 0xc0000 (get32 b 0);
              equal int 0xc0010 (get32 b 0x40));
        ];
      group "booter"
        [
          test "header parse and signature splice" (fun () ->
              let bt = Ip.Flcn.prep_booter ~blob:(build_booter ()) in
              equal int 0x10 bt.data_off;
              equal int 0x20 bt.data_sz;
              equal int 0x30 bt.code_off;
              equal int 0x40 bt.code_sz;
              equal int 0x80 (Bytes.length bt.image);
              (* signature (0x10 bytes) spliced at patch_loc = 0x10 *)
              let expected =
                String.init 0x10 (fun j -> Char.chr ((0x40 + j) land 0xff))
              in
              equal string expected (Bytes.sub_string bt.image 0x10 0x10));
        ];
      group "bootloader"
        [
          test "riscv ucode descriptor offsets" (fun () ->
              let bl = Ip.Gsp.init_boot_binary_image ~blob:(build_bootloader ()) in
              equal int 0x40 (Bytes.length bl.image);
              equal int 0x333 bl.monitor_code_offset;
              equal int 0x222 bl.monitor_data_offset;
              equal int 0x111 bl.manifest_offset);
        ];
      group "fmc split"
        [
          test "elf sections split into image and word blobs" (fun () ->
              let image = Bytes.of_string "FMC-IMAGE-BYTES!" in
              let hash =
                Bytes.of_string "\x01\x02\x03\x04\x05\x06\x07\x08"
              in
              let signature =
                Bytes.init 16 (fun i -> Char.chr (0x10 + i))
              in
              let publickey =
                Bytes.of_string "\xaa\xbb\xcc\xdd\xee"
              in
              let elf =
                build_elf
                  [
                    ("image", image);
                    ("hash", hash);
                    ("signature", signature);
                    ("publickey", publickey);
                  ]
              in
              let f = Ip.Flcn_cot.init_fmc_image ~blob:elf in
              equal string (Bytes.to_string image) (Bytes.to_string f.image);
              equal (array int) [| 0x04030201; 0x08070605 |] f.hash;
              equal (array int)
                [| 0x13121110; 0x17161514; 0x1b1a1918; 0x1f1e1d1c |]
                f.signature;
              (* publickey padded by 3 zero bytes before the final word *)
              equal (array int) [| 0xddccbbaa; 0xee |] f.public_key);
        ];
      group "radix3"
        [
          (* Derived from the pinned source page math (ip.py:406-409): the
             deepest level maps round_up(len,0x1000)/0x1000 pages, and each
             level above holds one entry per 512 pages of the level below;
             offsets are the running byte position of each level. *)
          test "single-page image" (fun () ->
              let r = Ip.Gsp.radix3 ~image_len:0x1000 in
              equal (array int) [| 1; 1; 1; 1 |] r.npages;
              equal (array int) [| 0; 0x1000; 0x2000; 0x3000 |] r.offsets;
              equal int 0x3000 r.image_off);
          test "nine-megabyte image spans a middle directory page" (fun () ->
              let r = Ip.Gsp.radix3 ~image_len:0x900000 in
              equal (array int) [| 1; 1; 5; 2304 |] r.npages;
              equal (array int) [| 0; 0x1000; 0x2000; 0x7000 |] r.offsets;
              equal int 0x7000 r.image_off);
          test "one page past a directory boundary adds a directory page"
            (fun () ->
              let r = Ip.Gsp.radix3 ~image_len:0x201000 in
              equal (array int) [| 1; 1; 2; 513 |] r.npages;
              equal (array int) [| 0; 0x1000; 0x2000; 0x4000 |] r.offsets;
              equal int 0x4000 r.image_off);
        ];
      group "firmware loader"
        [
          test "unknown file has no pinned digest table" (fun () ->
              raises_failure_with [ "no pinned digest table" ] (fun () ->
                  Ip.Firmware.fetch ~dir:"/nonexistent" ~chip_dir:"ga102"
                    "not-a-real-file.bin"));
          test "unknown chip dir has no pinned digest" (fun () ->
              raises_failure_with [ "no pinned digest for chip dir" ] (fun () ->
                  Ip.Firmware.fetch ~dir:"/nonexistent" ~chip_dir:"zz999"
                    "bootloader-570.144.bin"));
          test "missing file names both paths, the digest and the source"
            (fun () ->
              let dir =
                Filename.concat (Filename.get_temp_dir_name ())
                  (Printf.sprintf "tolk_nv_ip_missing_%d" (Random.int 1_000_000))
              in
              mkdir_p (Filename.concat (Filename.concat dir "ga102") "gsp");
              let sha =
                List.assoc "ga102"
                  (List.assoc "bootloader-570.144.bin" Gsp_defs.firmware)
              in
              raises_failure_with
                [
                  Filename.concat
                    (Filename.concat (Filename.concat dir "ga102") "gsp")
                    "bootloader-570.144.bin";
                  ".zst";
                  Gsp_defs.upstream;
                  sha;
                ]
                (fun () ->
                  Ip.Firmware.fetch ~dir ~chip_dir:"ga102"
                    "bootloader-570.144.bin"));
          test "a present plain file is read and its digest is checked"
            (fun () ->
              let dir =
                Filename.concat (Filename.get_temp_dir_name ())
                  (Printf.sprintf "tolk_nv_ip_plain_%d" (Random.int 1_000_000))
              in
              let gsp = Filename.concat (Filename.concat dir "ga102") "gsp" in
              mkdir_p gsp;
              let content = "not the real firmware" in
              write_file (Filename.concat gsp "bootloader-570.144.bin") content;
              let sha =
                List.assoc "ga102"
                  (List.assoc "bootloader-570.144.bin" Gsp_defs.firmware)
              in
              let actual = hex (Tolk.Helpers.sha256 (Bytes.of_string content)) in
              raises_failure_with [ "sha mismatch"; sha; actual ] (fun () ->
                  Ip.Firmware.fetch ~dir ~chip_dir:"ga102"
                    "bootloader-570.144.bin"));
          test "a zstd file is decoded before the digest is checked" (fun () ->
              if Sys.command "command -v zstd >/dev/null 2>&1" <> 0 then ()
              else begin
                let dir =
                  Filename.concat (Filename.get_temp_dir_name ())
                    (Printf.sprintf "tolk_nv_ip_zst_%d" (Random.int 1_000_000))
                in
                let gsp = Filename.concat (Filename.concat dir "ga102") "gsp" in
                mkdir_p gsp;
                let content = "compressed placeholder firmware" in
                let scratch = Filename.temp_file "tolk_nv_ip_src" ".bin" in
                write_file scratch content;
                let zst =
                  Filename.concat gsp "bootloader-570.144.bin.zst"
                in
                let status =
                  Sys.command
                    (Printf.sprintf "zstd -q -f %s -o %s" (Filename.quote scratch)
                       (Filename.quote zst))
                in
                (try Sys.remove scratch with Sys_error _ -> ());
                is_true (status = 0);
                let actual =
                  hex (Tolk.Helpers.sha256 (Bytes.of_string content))
                in
                raises_failure_with [ "sha mismatch"; actual ] (fun () ->
                    Ip.Firmware.fetch ~dir ~chip_dir:"ga102"
                      "bootloader-570.144.bin")
              end);
        ];
      (* Frame goldens below (checksums, element counts, pointer values)
         were generated by driving the pinned reference queue
         implementation (ip.py:19-91) over these exact inputs. *)
      group "rpc queue"
        [
          test "construction waits for the queue header to be published"
            (fun () ->
              with_mem 0x1800 (fun m ->
                  (* entryOff still zero: the owner never published. *)
                  raises_timeout_with [ "RPC queue not initialized" ] (fun () ->
                      ignore (mk_queue ~now_ms:(fake_clock ()) m))));
          test "a single record is framed byte-exactly" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun m ->
                  let doorbells = ref 0 in
                  let q = mk_queue ~doorbells m in
                  Rpc_queue.send_rpc q 0x36
                    (Bytes.init 12 (fun i -> Char.chr (0x11 + i)));
                  let expected = Bytes.make 0x100 '\000' in
                  set32 expected 0x20 0x504f4c50 (* checksum *);
                  set32 expected 0x28 1 (* element count *);
                  set32 expected 0x30 0x03000000 (* header version *);
                  set32 expected 0x34 0x43505256 (* signature *);
                  set32 expected 0x38 0x2c (* length = payload + 0x20 *);
                  set32 expected 0x3c 0x36 (* function *);
                  set32 expected 0x40 0xffffffff (* result: pending *);
                  set32 expected 0x44 0xffffffff (* result private *);
                  for i = 0 to 11 do
                    set8 expected (0x50 + i) (0x11 + i)
                  done;
                  equal string (hex expected)
                    (hex (Mmio.read_bytes m ~off:0x1000 ~len:0x100));
                  equal int 1 (m32 m 0x10) (* write pointer *);
                  equal int 1 !doorbells));
          test "each record consumes one sequence number" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun m ->
                  let q = mk_queue m in
                  Rpc_queue.send_rpc q 0x36
                    (Bytes.init 12 (fun i -> Char.chr (0x11 + i)));
                  Rpc_queue.send_rpc q 0x103 Bytes.empty;
                  equal int 2 (m32 m 0x10);
                  (* second element: seqNum 1 feeds the checksum *)
                  equal int 0x40505375 (m32 m 0x1120);
                  equal int 1 (m32 m 0x1124) (* seqNum *);
                  equal int 1 (m32 m 0x1128) (* elemCount *);
                  equal int 0x20 (m32 m 0x1138) (* length of empty payload *)));
          test "a record may span several ring elements" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun m ->
                  let q = mk_queue m in
                  let payload =
                    Bytes.init 0x1d0 (fun i -> Char.chr (((i * 7) + 3) land 0xff))
                  in
                  Rpc_queue.send_rpc q 0x4c payload;
                  equal int 3 (m32 m 0x1028) (* elemCount *);
                  equal int 0x9000a359 (m32 m 0x1020) (* checksum *);
                  equal int 3 (m32 m 0x10) (* write pointer *);
                  equal string (hex payload)
                    (hex (Mmio.read_bytes m ~off:0x1050 ~len:0x1d0));
                  (* the frame is padded to the element boundary *)
                  equal string
                    (hex (Bytes.make 0xe0 '\000'))
                    (hex (Mmio.read_bytes m ~off:0x1220 ~len:0xe0))));
          test "an oversized message continues in continuation records"
            (fun () ->
              with_queue ~msg_size:0x40 ~msg_count:0x20 (fun m ->
                  let doorbells = ref 0 in
                  let q = mk_queue ~doorbells m in
                  (* max payload of one 16-element frame: 0x400 - 0x50 *)
                  let payload =
                    Bytes.init (0x3b0 + 56) (fun i ->
                        Char.chr (((i * 5) + 1) land 0xff))
                  in
                  Rpc_queue.send_rpc q 0x67 payload;
                  (* first record: a full 16-element frame *)
                  equal int 16 (m32 m 0x1028);
                  equal int 0 (m32 m 0x1024) (* seqNum *);
                  equal int 0x40304131 (m32 m 0x1020) (* checksum *);
                  equal int 0x67 (m32 m 0x103c);
                  equal int 0x3d0 (m32 m 0x1038) (* 0x3b0 + 0x20 *);
                  (* continuation record at element 16 *)
                  equal int 3 (m32 m 0x1428);
                  equal int 1 (m32 m 0x1424) (* seqNum *);
                  equal int 0x74643edf (m32 m 0x1420) (* checksum *);
                  equal int 0x47 (m32 m 0x143c) (* continuation function *);
                  equal int 0x58 (m32 m 0x1438) (* 56 + 0x20 *);
                  equal string
                    (hex (Bytes.sub payload 0x3b0 56))
                    (hex (Mmio.read_bytes m ~off:0x1450 ~len:56));
                  equal int 19 (m32 m 0x10) (* write pointer *);
                  equal int 2 !doorbells));
          test "publishing wraps across the ring end" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 ~write_ptr:6 (fun m ->
                  let q = mk_queue m in
                  let payload =
                    Bytes.init 0x1d0 (fun i -> Char.chr ((i + 1) land 0xff))
                  in
                  Rpc_queue.send_rpc q 0x4c payload;
                  equal int 1 (m32 m 0x10) (* (6 + 3) mod 8 *);
                  equal int 3 (m32 m 0x1628) (* elemCount at element 6 *);
                  equal int 0x905053e9 (m32 m 0x1620) (* checksum *);
                  equal string
                    (hex (Bytes.sub payload 0 0x1b0))
                    (hex (Mmio.read_bytes m ~off:0x1650 ~len:0x1b0));
                  (* the tail wraps to the start of the ring, then padding *)
                  equal string
                    (hex (Bytes.sub payload 0x1b0 0x20))
                    (hex (Mmio.read_bytes m ~off:0x1000 ~len:0x20));
                  equal string
                    (hex (Bytes.make 0xe0 '\000'))
                    (hex (Mmio.read_bytes m ~off:0x1020 ~len:0xe0))));
          test "responses are read at the header length and events dispatched"
            (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      (* the GSP publishes an error-log event, then the
                         response the caller waits for *)
                      let log_payload =
                        Bytes.cat (Bytes.make 12 '\000')
                          (Bytes.of_string "gsp said hi\000\000")
                      in
                      let f0 =
                        gsp_frame ~msg_size:0x100 ~func:0x1006 log_payload
                      in
                      let resp_payload =
                        Bytes.init 0x20 (fun i -> Char.chr (0x40 + i))
                      in
                      let f1 =
                        gsp_frame ~msg_size:0x100 ~func:0x4c ~seq:1 resp_payload
                      in
                      Mmio.blit_bytes stat ~off:0x1000 f0;
                      Mmio.blit_bytes stat ~off:(0x1000 + Bytes.length f0) f1;
                      Mmio.write32 stat 0x10 2l (* write pointer: 2 elements *);
                      let errors = ref 0 in
                      let q =
                        mk_queue ~completion_q_view:cmd
                          ~on_err:(fun () -> incr errors)
                          stat
                      in
                      (* the declared length covers the header too, so the
                         message carries 0x20 trailing ring bytes *)
                      let expected =
                        Bytes.cat resp_payload (Bytes.make 0x20 '\000')
                      in
                      equal string (hex expected)
                        (hex (Rpc_queue.wait_resp q 0x4c));
                      equal int 2 (m32 cmd 0x20) (* read pointer advanced *);
                      equal int 1 !errors)));
          test "a cpu-sequencer command is handed to its callback" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      let payload =
                        Bytes.init 16 (fun i -> Char.chr (0xa0 + i))
                      in
                      Mmio.blit_bytes stat ~off:0x1000
                        (gsp_frame ~msg_size:0x100 ~func:0x1002 payload);
                      Mmio.write32 stat 0x10 1l;
                      let seen = ref [] in
                      let q =
                        mk_queue ~completion_q_view:cmd
                          ~on_seq:(fun b -> seen := hex b :: !seen)
                          stat
                      in
                      let drained = List.of_seq (Rpc_queue.read_resp q) in
                      let expected =
                        hex (Bytes.cat payload (Bytes.make 0x20 '\000'))
                      in
                      equal (list string) [ expected ] !seen;
                      equal (list (pair int string))
                        [ (0x1002, expected) ]
                        (List.map (fun (f, b) -> (f, hex b)) drained);
                      equal int 1 (m32 cmd 0x20))));
          test "a nonzero rpc result fails naming the call" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      Mmio.blit_bytes stat ~off:0x1000
                        (gsp_frame ~msg_size:0x100 ~func:0x4c ~result:0x57
                           (Bytes.make 8 '\xaa'));
                      Mmio.write32 stat 0x10 1l;
                      let q = mk_queue ~completion_q_view:cmd stat in
                      raises_failure_with
                        [ "RPC call 76 failed with result 87" ]
                        (fun () ->
                          ignore (List.of_seq (Rpc_queue.read_resp q))))));
          test "the frame checksum is not verified on receive" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      let f =
                        gsp_frame ~msg_size:0x100 ~func:0x4c
                          (Bytes.make 8 '\xbb')
                      in
                      set32 f 0x20 0xdeadbeef (* corrupt the checksum *);
                      Mmio.blit_bytes stat ~off:0x1000 f;
                      Mmio.write32 stat 0x10 1l;
                      let q = mk_queue ~completion_q_view:cmd stat in
                      match List.of_seq (Rpc_queue.read_resp q) with
                      | [ (func, _) ] -> equal int 0x4c func
                      | l -> equal int 1 (List.length l))));
          test "the read pointer wraps at the ring end" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      Mmio.blit_bytes stat ~off:0x1700
                        (gsp_frame ~msg_size:0x100 ~func:0x4c
                           (Bytes.make 8 '\xcc'));
                      let q = mk_queue ~completion_q_view:cmd stat in
                      Mmio.write32 cmd 0x20 7l (* read pointer at the last
                                                  element; write pointer 0 *);
                      equal int 1
                        (List.length (List.of_seq (Rpc_queue.read_resp q)));
                      equal int 0 (m32 cmd 0x20))));
          test "wait_resp times out on an idle queue" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun stat ->
                  with_queue ~msg_size:0x100 ~msg_count:8 (fun cmd ->
                      let q =
                        mk_queue ~completion_q_view:cmd
                          ~now_ms:(fake_clock ()) stat
                      in
                      raises_failure_with
                        [ "Timeout waiting for RPC response for command 76" ]
                        (fun () ->
                          ignore (Rpc_queue.wait_resp q ~timeout_ms:5 0x4c)))));
          test "reading without a read pointer is refused" (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun m ->
                  let q = mk_queue m in
                  raises_match
                    (function
                      | Invalid_argument s ->
                          contains ~needle:"no read pointer" s
                      | _ -> false)
                    (fun () -> ignore (List.of_seq (Rpc_queue.read_resp q)))));
          test "the opposite queue's read slot is where the header says"
            (fun () ->
              with_queue ~msg_size:0x100 ~msg_count:8 (fun m ->
                  equal int 0x20 (Rpc_queue.rx_hdr_off (mk_queue m))));
        ];
      (* Expected effects generated by driving the pinned reference
         interpreter (ip.py:618-650) over the same command streams. *)
      group "run_cpu_seq"
        [
          test "a write command writes through wreg" (fun () ->
              equal (list string)
                [ "w:1234:deadbeef" ]
                (run_seq [ 0x0; 0x1234; 0xdeadbeef ]));
          test "a modify command keeps bits outside the mask" (fun () ->
              equal (list string)
                [ "r:100:aabbccdd"; "w:100:aa0fcc0f" ]
                (run_seq
                   ~rreg:(fun _ -> 0xaabbccdd)
                   [ 0x1; 0x100; 0x0f0f0f0f; 0x00ff00ff ]));
          test "a poll command reads until the value appears" (fun () ->
              let n = ref 0 in
              let rreg _ =
                incr n;
                if !n >= 3 then 0x8000 else 0
              in
              equal (list string)
                [ "r:200:0"; "r:200:0"; "r:200:8000" ]
                (run_seq ~rreg [ 0x2; 0x200; 0xffff; 0x8000; 7; 8 ]));
          test "a poll command times out naming the register" (fun () ->
              raises_timeout_with
                [ "Register 0x200 not equal to 0x8000 after polling" ]
                (fun () -> run_seq [ 0x2; 0x200; 0xffff; 0x8000; 7; 8 ]));
          test "a delay command sleeps the given microseconds" (fun () ->
              let slept = ref [] in
              let log =
                run_seq ~sleep_us:(fun us -> slept := us :: !slept) [ 0x3; 205 ]
              in
              equal (list string) [] log;
              equal (list int) [ 205 ] !slept);
          test "a save command reads into the scratch area" (fun () ->
              equal (list string) [ "r:300:1122" ]
                (run_seq ~rreg:(fun _ -> 0x1122) [ 0x4; 0x300; 2 ]);
              raises_match
                (function Invalid_argument _ -> true | _ -> false)
                (fun () -> ignore (run_seq [ 0x4; 0x300; 9 ])));
          test "core commands invoke their actions in order" (fun () ->
              let acts = ref [] in
              let log =
                run_seq ~core:(fun a -> acts := a :: !acts) [ 0x5; 0x6; 0x7; 0x8 ]
              in
              equal (list string) [] log;
              equal (list string)
                [ "reset"; "start"; "halt"; "resume" ]
                (List.rev !acts));
          test "an unknown command fails naming it" (fun () ->
              raises_failure_with [ "Unknown op code 9 in run_cpu_seq" ]
                (fun () -> ignore (run_seq [ 0x9 ])));
          test "words past the command count are ignored" (fun () ->
              equal (list string) [ "w:42:99" ]
                (run_seq ~cmd_index:3 [ 0x0; 0x42; 0x99; 0x0; 0x777 ]));
          test "arguments past the command count fail loudly" (fun () ->
              raises_failure_with [ "truncated command stream" ] (fun () ->
                  ignore (run_seq ~cmd_index:2 [ 0x0; 0x42 ])));
        ];
      group "falcon reset"
        [
          test "the GSP falcon resets and selects its RISC-V core"
            (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  (* scrubbing done, the block carries a RISC-V core, and
                     it validates once selected. *)
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_HWCFG2"
                    (1 lsl 10);
                  set_read fd ~base:falcon_base "NV_PRISCV_RISCV_BCR_CTRL" 1;
                  Ip.Flcn.reset flcn falcon_base;
                  equal (list string)
                    [
                      "1103c0:1"; "1103c0:0"; "111668:0"; "110084:174000a1";
                    ]
                    (show_writes fd)));
          test "a RISC-V reset leaves the core fetching its bootloader"
            (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_HWCFG2" 0;
                  Ip.Flcn.reset flcn ~riscv:true falcon_base;
                  equal (list string)
                    [ "1103c0:1"; "1103c0:0"; "111668:110" ]
                    (show_writes fd)));
          test "the SEC2 booter resets without a RISC-V core" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_HWCFG2" 0;
                  Ip.Flcn.reset flcn sec2_base;
                  equal (list string)
                    [ "8403c0:1"; "8403c0:0" ]
                    (show_writes fd)));
        ];
      group "falcon core control"
        [
          test "disable_ctx_req opens context-free physical DMA" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  Ip.Flcn.disable_ctx_req flcn falcon_base;
                  equal (list string)
                    [ "110624:80"; "11010c:0" ]
                    (show_writes fd)));
          test "start_cpu starts the core directly when no alias" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL" 0;
                  Ip.Flcn.start_cpu flcn falcon_base;
                  equal (list string) [ "110100:2" ] (show_writes fd)));
          test "start_cpu uses the alias register when enabled" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL"
                    (1 lsl 6);
                  Ip.Flcn.start_cpu flcn falcon_base;
                  equal (list string) [ "110130:2" ] (show_writes fd)));
          test "wait_cpu_halted returns once the core halts" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL"
                    (1 lsl 4);
                  Ip.Flcn.wait_cpu_halted flcn falcon_base;
                  equal (list string) [] (show_writes fd)));
          test "wait_cpu_halted times out on a running core" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL" 0;
                  raises_timeout_with [ "not halted" ] (fun () ->
                      Ip.Flcn.wait_cpu_halted flcn falcon_base)));
        ];
      group "falcon execute_hs"
        [
          test "a heavy-secured run loads both memories and boots the core"
            (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  (* the DMA queue is free and idle, and the core halts. *)
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_DMATRFCMD"
                    0x2;
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL"
                    (1 lsl 4);
                  let r =
                    Ip.Flcn.execute_hs flcn falcon_base ~img_paddr:0x10000000
                      ~code_off:0x0 ~data_off:0x800 ~imem_pa:0x1000
                      ~imem_va:0x100 ~imem_sz:256 ~dmem_pa:0x2000 ~dmem_va:0x0
                      ~dmem_sz:256 ~pkc_off:0x300 ~engid:0x2 ~ucodeid:0x3 ()
                  in
                  equal (option (pair int int)) None r;
                  equal (list string)
                    [
                      "110624:80"; "11010c:0"; "110600:4"; "110110:fffff";
                      "110128:0"; "110114:1000"; "11011c:100"; "110118:614";
                      "110110:100008"; "110128:0"; "110114:2000"; "11011c:0";
                      "110118:600"; "111210:300"; "11119c:2"; "111198:3";
                      "111180:1"; "110104:100"; "110100:2";
                    ]
                    (show_writes fd)));
          test "a mailbox seed is written and the pair is read back"
            (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_DMATRFCMD" 0x2;
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_CPUCTL"
                    (1 lsl 4);
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_MAILBOX0"
                    0xdead;
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_MAILBOX1"
                    0xbeef;
                  let r =
                    Ip.Flcn.execute_hs flcn sec2_base ~img_paddr:0x0
                      ~code_off:0x0 ~data_off:0x0 ~imem_pa:0x0 ~imem_va:0x0
                      ~imem_sz:0 ~dmem_pa:0x0 ~dmem_va:0x0 ~dmem_sz:0
                      ~pkc_off:0x10 ~engid:1 ~ucodeid:3 ~mailbox:0x123456789 ()
                  in
                  equal (option (pair int int)) (Some (0xdead, 0xbeef)) r;
                  let mb =
                    List.filter_map
                      (fun (a, v) ->
                        if a = 0x840040 || a = 0x840044 then
                          Some (Printf.sprintf "%x:%x" a v)
                        else None)
                      (writes fd)
                  in
                  equal (list string) [ "840040:23456789"; "840044:1" ] mb));
        ];
      group "falcon wait_for_reset"
        [
          test "returns once the boot-progress scratch reports complete"
            (fun () ->
              with_fake_dev (fun fd ->
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd
                    "NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK" 1;
                  set_read fd ~idx:0 "NV_PGC6_AON_SECURE_SCRATCH_GROUP_05"
                    0xff;
                  Ip.Flcn.wait_for_reset flcn;
                  equal (list string) [] (show_writes fd)));
          test "keeps waiting until both conditions hold" (fun () ->
              with_fake_dev (fun fd ->
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd
                    "NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK" 1;
                  set_read fd ~idx:0 "NV_PGC6_AON_SECURE_SCRATCH_GROUP_05"
                    0x00;
                  raises_timeout_with [ "waiting for reset" ] (fun () ->
                      Ip.Flcn.wait_for_reset flcn)));
        ];
      group "chain-of-trust execution"
        [
          test "wait_for_reset polls the thermal scratch" (fun () ->
              with_fake_dev (fun fd ->
                  let cot = Ip.Flcn_cot.create fd.dev in
                  Hashtbl.replace fd.reads 0xad00bc (fun () -> 0xff);
                  Ip.Flcn_cot.wait_for_reset cot;
                  equal (list string) [] (show_writes fd)));
          test "kfsp_send_msg frames, pushes and drains a message"
            (fun () ->
              with_fake_dev (fun fd ->
                  Nvdev.include_regs fd.dev ~family:"dev_fsp_pri" ~arch:"gh100";
                  let cot = Ip.Flcn_cot.create fd.dev in
                  (* a reply is already queued: head past tail. *)
                  Hashtbl.replace fd.reads 0x8f2c80 (fun () -> 1);
                  Hashtbl.replace fd.reads 0x8f2c84 (fun () -> 0);
                  let payload = Bytes.create 8 in
                  set32 payload 0 0x44332211;
                  set32 payload 4 0x88776655;
                  Ip.Flcn_cot.kfsp_send_msg cot ~nvmd:0x14 payload;
                  equal (list string)
                    [
                      "8f2ac0:1000000"; "8f2ac4:c0000000"; "8f2ac4:1410de7e";
                      "8f2ac4:44332211"; "8f2ac4:88776655"; "8f2ac4:0";
                      "8f2c04:10"; "8f2c00:0"; "8f2ac0:2000000"; "8f2c84:1";
                    ]
                    (show_writes fd)));
          test "kfsp_send_msg rejects an oversized message" (fun () ->
              with_fake_dev (fun fd ->
                  Nvdev.include_regs fd.dev ~family:"dev_fsp_pri" ~arch:"gh100";
                  let cot = Ip.Flcn_cot.create fd.dev in
                  raises_failure_with [ "FSP message too long" ] (fun () ->
                      Ip.Flcn_cot.kfsp_send_msg cot ~nvmd:0x14
                        (Bytes.make 0x400 '\000'))));
        ];
      (* Byte goldens below were generated by driving the pinned reference
         structures (ip.py:363-616 over the nv/nv_570 autogen) on these exact
         inputs. *)
      group "gsp payload builders"
        [
          test "the registry table packs the boot keys" (fun () ->
              equal string
                "5200000002000000280000000100000001000000040000003e000000010000000100000004000000524d466f72636550636965436f6e6669675361766500524d5365634275735265736574456e61626c6500"
                (hex (Ip.Gsp.registry_table ())));
          test "the system info carries the BARs and PCI identity" (fun () ->
              let data =
                Ip.Gsp.gsp_system_info ~gpu_phys:0x10000000
                  ~gpu_phys_fb:0x20000000 ~gpu_phys_inst:0x30000000
                  ~fmc_boot:false ~bdf:0x300 ~pci_device_id:0x220310de
                  ~pci_subdevice_id:0x0 ~pci_revision_id:0xa1
              in
              equal int 0x3a0 (Bytes.length data);
              equal int 0x10000000 (get64 data 0) (* gpuPhysAddr *);
              equal int 0x20000000 (get64 data 8) (* gpuPhysFbAddr *);
              equal int 0x88000 (get32 data 0x50) (* pciConfigMirrorBase *);
              equal int 0x300 (get64 data 0x20) (* bdf *);
              equal int 0x220310de (get32 data 0x58) (* PCIDeviceID *);
              equal int 0xa1 (get32 data 0x60) (* PCIRevisionID *);
              equal int 0x7ffffffff000 (get64 data 0x48) (* maxUserVa *));
          test "the bus address packs into the domain-bus-device-function"
            (fun () ->
              equal int 0x300 (Ip.Gsp.bdf_as_int "0000:03:00.0");
              equal int 0x4101 (Ip.Gsp.bdf_as_int "0000:41:00.1");
              equal int 0 (Ip.Gsp.bdf_as_int "usb:0"));
          test "the falcon wpr metadata packs down from the top of vram"
            (fun () ->
              (* frts is vram - 0x200000; the falcon boot asserts it matches *)
              let m =
                Ip.Gsp.wpr_meta ~vram_size:0x10000000 ~fmc_boot:false
                  ~radix3_addr:0x1000 ~radix3_size:0x900000 ~booter_addr:0x2000
                  ~booter_size:0x8000 ~signature_addr:0x3000 ~code_off:0x111
                  ~data_off:0x222 ~manifest_off:0x333 ~frts_offset:0xfe00000
              in
              equal string
                "b3601a3721ae3adc010000000000000000100000000000000000900000000000002000000000000000800000000000001101000000000000220200000000000033030000000000000030000000000000001000000000000000001007000000000000100700000000000010000000000000002007000000000000300700000000000010080000000000004f0f000000000080df0f000000000000e00f0000000000001000000000000000f00f0000000000000010000000000000f00f0000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                (hex m));
          test "the wpr metadata rejects a mismatched frts offset" (fun () ->
              raises_failure_with [ "FRTS mismatch" ] (fun () ->
                  ignore
                    (Ip.Gsp.wpr_meta ~vram_size:0x10000000 ~fmc_boot:false
                       ~radix3_addr:0x1000 ~radix3_size:0x900000
                       ~booter_addr:0x2000 ~booter_size:0x8000
                       ~signature_addr:0x3000 ~code_off:0x111 ~data_off:0x222
                       ~manifest_off:0x333 ~frts_offset:0x0)));
          test "the chain-of-trust wpr metadata uses the fixed reservation"
            (fun () ->
              let m =
                Ip.Gsp.wpr_meta ~vram_size:0x20000000 ~fmc_boot:true
                  ~radix3_addr:0x4000 ~radix3_size:0x900000 ~booter_addr:0x5000
                  ~booter_size:0x9000 ~signature_addr:0x6000 ~code_off:0x1
                  ~data_off:0x2 ~manifest_off:0x3 ~frts_offset:0
              in
              equal string
                "b3601a3721ae3adc0100000000000000004000000000000000009000000000000050000000000000009000000000000001000000000000000200000000000000030000000000000000600000000000000010000000000000000000000000000000000000000000000000220000000000000000000000000000000000000000000000700800000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082010000000000000000"
                (hex m));
          test "the radix3 fill copies the image and links the levels"
            (fun () ->
              let image = Bytes.init 0x1000 (fun i -> Char.chr (((i * 3) + 1) land 0xff)) in
              let layout = Ip.Gsp.radix3 ~image_len:0x1000 in
              let region =
                Ip.Gsp.radix3_fill ~image ~layout
                  ~page_addrs:[| 0xa000; 0xb000; 0xc000; 0xd000 |]
              in
              equal int 0x4000 (Bytes.length region);
              (* each directory level points at the next level's page *)
              equal int 0xb000 (get64 region 0);
              equal int 0xc000 (get64 region 0x1000);
              equal int 0xd000 (get64 region 0x2000);
              equal string (hex image)
                (hex (Bytes.sub region 0x3000 0x1000)));
          test "the rm_alloc payload frames the envelope and params" (fun () ->
              let params = Bytes.init 16 (fun i -> Char.chr (0x11 + i)) in
              equal string
                "000000c1010000c1000000cf80000000000000001000000000000000000000001112131415161718191a1b1c1d1e1f20"
                (hex
                   (Ip.Gsp.rm_alloc_request ~client:0xc1000000 ~hparent:0xc1000001
                      ~hobject:0xcf000000 ~hclass:0x80 ~params)));
          test "the rm_control payload frames the envelope and params"
            (fun () ->
              let params = Bytes.make 16 '\x22' in
              equal string
                "000000c15d0000000112802000000000100000000000000022222222222222222222222222222222"
                (hex
                   (Ip.Gsp.rm_control_request ~client:0xc1000000 ~hobject:0x5d
                      ~cmd:0x20801201 ~params)));
          test "the control response is copied back with the gb20x token patch"
            (fun () ->
              (* the response is the envelope echo, the parameters, then the
                 declared-length trailing ring bytes *)
              let resp = Bytes.make (0x18 + 4 + 0x20) '\000' in
              set32 resp 0x18 0x5 (* workSubmitToken *);
              let cmd = 0xc36f0108 in
              let apply chip =
                let p = Tables.create_blob 4 in
                Ip.Gsp.rm_control_apply ~chip_name:chip ~cmd ~response:resp
                  ~params:p;
                Tables.get_field p (0, 4)
              in
              (* gb20x sets the work-submit enable bit (1<<30) *)
              equal int 0x40000005 (apply "GB202");
              (* other parts keep the returned token unchanged *)
              equal int 0x5 (apply "GA102");
              (* and so does a different control command on gb20x *)
              let p = Tables.create_blob 4 in
              Ip.Gsp.rm_control_apply ~chip_name:"GB202" ~cmd:0x1234
                ~response:resp ~params:p;
              equal int 0x5 (Tables.get_field p (0, 4)));
        ];
      (* The core boot actions the GSP CPU sequencer drives, over the fake
         falcon device; the expected register traffic composes the falcon
         reset, start, halt-wait and RISC-V resume primitives. *)
      group "gsp core actions"
        [
          test "reset detaches the falcon and opens context-free dma"
            (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_HWCFG2"
                    (1 lsl 10);
                  set_read fd ~base:falcon_base "NV_PRISCV_RISCV_BCR_CTRL" 1;
                  let ca =
                    Ip.Gsp.falcon_core_actions flcn ~libos_args_sysmem:0x123456789
                  in
                  ca.core_reset ();
                  equal (list string)
                    [
                      "1103c0:1"; "1103c0:0"; "111668:0"; "110084:174000a1";
                      "110624:80"; "11010c:0";
                    ]
                    (show_writes fd)));
          test "start and halt-wait drive the falcon core" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_CPUCTL"
                    (1 lsl 4);
                  let ca =
                    Ip.Gsp.falcon_core_actions flcn ~libos_args_sysmem:0x0
                  in
                  ca.core_start ();
                  equal (list string) [ "110100:2" ] (show_writes fd);
                  fd.log := [];
                  ca.core_wait_halted ();
                  equal (list string) [] (show_writes fd)));
          test "resume restarts as risc-v and runs the sec2 booter" (fun () ->
              with_fake_dev (fun fd ->
                  include_falcon fd;
                  let flcn = Ip.Flcn.create fd.dev in
                  set_read fd ~base:falcon_base "NV_PFALCON_FALCON_HWCFG2" 0;
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_CPUCTL" 0;
                  set_read fd "NV_PGC6_BSI_SECURE_SCRATCH_14" (1 lsl 26);
                  set_read fd ~base:sec2_base "NV_PFALCON_FALCON_MAILBOX0" 0;
                  let ca =
                    Ip.Gsp.falcon_core_actions flcn ~libos_args_sysmem:0x123456789
                  in
                  ca.core_resume ();
                  equal (list string)
                    [
                      "1103c0:1"; "1103c0:0"; "111668:110"; "110040:23456789";
                      "110044:1"; "840100:2";
                    ]
                    (show_writes fd)));
        ];
      (* The golden-image parameter structures, generated by driving the
         pinned nv_570 autogen (ip.py:456-504) on these exact inputs. *)
      group "gsp golden image builders"
        [
          test "the channel memory descriptors point at their allocations"
            (fun () ->
              let module C = Gsp_defs.Nv_channelgpfifo_allocation_parameters in
              let module M = Gsp_defs.Nv_memory_desc_params in
              let gg = Tables.create_blob C.sizeof in
              Tables.set_field gg C.hobjecterror 0x1234;
              Tables.set_field gg
                (C.huserdmemory_offset, C.huserdmemory_elem_size)
                0x70000;
              Tables.set_field gg (C.userdoffset_offset, C.userdoffset_elem_size)
                0x100;
              Ip.Gsp.set_channel_gpfifo_descs ~params:gg ~ramfc_paddr:0x50000
                ~method_paddr:0x60000 ~userd:(Some (0x70000 + 0x100));
              let desc region f = Tables.get_field ~base:(fst region) gg f in
              equal int 0x50000 (desc C.ramfcmem M.base);
              equal int 0x200 (desc C.ramfcmem M.size);
              equal int 2 (desc C.ramfcmem M.addressspace);
              equal int 0x50000 (desc C.instancemem M.base);
              equal int 0x1000 (desc C.instancemem M.size);
              equal int 0x60000 (desc C.mthdbufmem M.base);
              equal int 0x5000 (desc C.mthdbufmem M.size);
              equal int 0 (desc C.errornotifiermem M.base);
              equal int 0xecc (desc C.errornotifiermem M.size);
              equal int 0x70100 (desc C.userdmem M.base);
              equal int 0x400 (desc C.userdmem M.size));
          test "a privileged channel fills no error notifier or user-d"
            (fun () ->
              let module C = Gsp_defs.Nv_channelgpfifo_allocation_parameters in
              let module M = Gsp_defs.Nv_memory_desc_params in
              let gg = Tables.create_blob C.sizeof in
              Ip.Gsp.set_channel_gpfifo_descs ~params:gg ~ramfc_paddr:0x50000
                ~method_paddr:0x60000 ~userd:None;
              let desc region f = Tables.get_field ~base:(fst region) gg f in
              equal int 0x5000 (desc C.mthdbufmem M.size);
              equal int 0 (desc C.errornotifiermem M.size);
              equal int 0 (desc C.userdmem M.base));
          test "the reserved-pde copy carries the level chain" (fun () ->
              let res_sz = 512 lsl 20 in
              let res_va = 0x100000000 in
              equal string
                "000000000000000000000020000000000000000001000000ffffff1f01000000030000000000000000a00a00000000002000000000000000010000002f00000000b00b00000000000010000000000000010000002600000000c00c00000000000010000000000000010000001d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                (hex
                   (Ip.Gsp.reserved_pdes_params ~page_size:res_sz
                      ~virt_addr_lo:res_va
                      ~virt_addr_hi:(res_va + res_sz - 1) ~num_levels:3
                      ~levels:
                        [
                          (0xaa000, 0x20, 47, 1); (0xbb000, 0x1000, 38, 1);
                          (0xcc000, 0x1000, 29, 1);
                        ])));
          test "the context promotion binds each buffer" (fun () ->
              equal string
                "0100000000000000000000000400e0c1050000cf000000000000000000000000000000000000000002000000000000000000300000000000000000000200000000000400000000000400000000000100000000000000000000000400020000000000000000000000000000000200000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                (hex
                   (Ip.Gsp.promote_ctx_params ~client:0xc1e00004
                      ~obj:0xcf000005
                      ~entries:
                        [
                          {
                            Ip.Gsp.buffer_id = 0;
                            gpu_virt_addr = 0x200000000;
                            gpu_phys_addr = 0x300000;
                            size = 0x40000;
                            phys_attr = 0x4;
                            b_initialize = true;
                            b_nonmapped = false;
                          };
                          {
                            Ip.Gsp.buffer_id = 2;
                            gpu_virt_addr = 0x200040000;
                            gpu_phys_addr = 0;
                            size = 0;
                            phys_attr = 0;
                            b_initialize = false;
                            b_nonmapped = true;
                          };
                        ])));
        ];
    ]
