#!/usr/bin/env python3
"""Generate the expected token ids that brot is checked against.

Run from anywhere:

    uv run --with tokenizers python3 packages/brot/test/scripts/gen_parity_expected.py

The reference is the HuggingFace `tokenizers` library. `test_parity.ml` reads
the files this writes and requires brot to produce exactly the same ids, so
regenerate only when a fixture changes or when a divergence has been confirmed
to be a bug in the reference rather than in brot.

Corpora
-------

`fixtures/parity/sample.txt` is ordinary prose: the unique block of
`bench/data/wiki_64k.txt` (that file is a 2533-byte block repeated to fill
64 KB), `bench/data/news_1k.txt`, and a few of the project's own English
documentation pages, which add code identifiers, URLs and punctuation.
`fixtures/parity/edge_cases.txt` is hand-written and covers whitespace runs,
contractions, digits, scripts, combining marks, emoji, over-long words and
special tokens.

Fixture format
--------------

A corpus file holds several documents separated by a line containing exactly
`====`; documents may therefore contain newlines, and a document may be empty.
The last byte of the file is a newline that belongs to the format, not to the
final document. Splitting is line-based, so a separator at the start or end of
the file, and two adjacent separators, all denote empty documents; a line that
merely starts with `====` is ordinary text. See `documents` below.

Expected-ids format
-------------------

For corpus `<corpus>.txt` and tokenizer `<name>` this writes
`fixtures/parity/<corpus>.<name>.ids`:

    # a header comment, recording the reference version
    <ids of document 0, space separated>
    ...
    ALL <ids of the whole corpus file as a single document>

Lines starting with `#` are comments. Every other line is one document's ids in
order, and may be empty when a document encodes to no tokens at all. The final
line is prefixed `ALL ` and holds the whole corpus file (again minus its final
newline) encoded as one document, which exercises the long-input paths.
"""

from __future__ import annotations

import sys
from pathlib import Path

import tokenizers
from tokenizers import Tokenizer

CORPORA = ("sample", "edge_cases")
TOKENIZERS = ("gpt2", "llama", "bert_base")


def documents(text: str) -> list[str]:
    docs: list[str] = []
    current: list[str] = []
    for line in text.removesuffix("\n").split("\n"):
        if line == "====":
            docs.append("\n".join(current))
            current = []
        else:
            current.append(line)
    docs.append("\n".join(current))
    return docs


def main() -> int:
    test_root = Path(__file__).resolve().parents[1]
    parity_dir = test_root / "fixtures" / "parity"
    models_dir = test_root.parent / "bench" / "data"

    for name in TOKENIZERS:
        model = models_dir / f"{name}.json"
        if not model.exists():
            print(
                f"missing {model}; run packages/brot/bench/download_data.sh",
                file=sys.stderr,
            )
            return 1
        tokenizer = Tokenizer.from_file(str(model))

        for corpus in CORPORA:
            text = (parity_dir / f"{corpus}.txt").read_bytes().decode("utf-8")
            lines = [
                (
                    "# generated by gen_parity_expected.py with tokenizers "
                    f"{tokenizers.__version__}"
                ),
                f"# corpus {corpus}.txt, tokenizer {name}, add_special_tokens=False",
            ]
            for document in documents(text):
                ids = tokenizer.encode(document, add_special_tokens=False).ids
                lines.append(" ".join(map(str, ids)))
            whole = tokenizer.encode(
                text.removesuffix("\n"), add_special_tokens=False
            ).ids
            lines.append("ALL " + " ".join(map(str, whole)))

            out = parity_dir / f"{corpus}.{name}.ids"
            out.write_text(
                "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
            )
            print(f"wrote {out} ({out.stat().st_size} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
