(* Generated by gen/gen.py from the excerpts in gen/headers; do not edit. *)

(* The discovery table *)

let binary_signature = 0x28211407
let discovery_table_signature = 0x53445049
let gc_table_id = 0x4347
let harvest_table_signature = 0x56524148
let discovery_tmr_offset = 0x10000
let discovery_tmr_size = 0x2800

(* The tables the binary header lists, by index. *)
let ip_discovery_table = 0
let gc_table = 1
let harvest_info_table = 2

(* Layouts: each field as (byte offset, bytes), or (bit offset, bits) for a
   bit field; an array's bytes are its element's. *)
module Binary_header = struct
  let sizeof = 60
  let binary_signature = (0, 4)
  let binary_checksum = (8, 2)
  let binary_size = (10, 2)
  let table_list = (12, 8)
end

module Table_info = struct
  let sizeof = 8
  let offset = (0, 2)
  let checksum = (2, 2)
end

module Ip_discovery_header = struct
  let sizeof = 80
  let signature = (0, 4)
  let version = (4, 2)
  let size = (6, 2)
  let num_dies = (12, 2)
  let die_info = (14, 4)
  let base_addr_64_bit = (624, 1)
end

module Die_info = struct
  let sizeof = 4
  let die_offset = (2, 2)
end

module Die_header = struct
  let sizeof = 4
  let die_id = (0, 2)
  let num_ips = (2, 2)
end

module Ip_v4 = struct
  let sizeof = 8
  let hw_id = (0, 2)
  let instance_number = (2, 1)
  let num_base_address = (3, 1)
  let major = (4, 1)
  let minor = (5, 1)
  let revision = (6, 1)
end

module Gpu_info_header = struct
  let sizeof = 12
  let table_id = (0, 4)
  let version_major = (4, 2)
  let size = (8, 4)
end

module Gc_info_v1_0 = struct
  let sizeof = 88
  let gc_num_se = (12, 4)
  let gc_num_wgp0_per_sa = (16, 4)
  let gc_num_wgp1_per_sa = (20, 4)
  let gc_max_waves_per_simd = (60, 4)
  let gc_max_scratch_slots_per_cu = (64, 4)
  let gc_lds_size = (68, 4)
  let gc_num_sa_per_se = (76, 4)
end

module Gc_info_v2_0 = struct
  let sizeof = 80
  let gc_num_se = (12, 4)
  let gc_num_cu_per_sh = (16, 4)
  let gc_num_sh_per_se = (20, 4)
  let gc_max_waves_per_simd = (60, 4)
  let gc_max_scratch_slots_per_cu = (64, 4)
  let gc_lds_size = (68, 4)
end

module Harvest_info_header = struct
  let sizeof = 8
  let signature = (0, 4)
end

module Harvest_info = struct
  let sizeof = 4
  let hw_id = (0, 2)
  let number_instance = (2, 1)
end

module Harvest_table = struct
  let sizeof = 136
  let list = (8, 4)
end

(* The blocks' hardware IDs, and their names *)

let gc_hwid = 11
let sdma0_hwid = 42
let sdma1_hwid = 43
let sdma2_hwid = 68
let sdma3_hwid = 69
let mp0_hwid = 255
let mp1_hwid = 1
let mmhub_hwid = 34
let osssys_hwid = 40
let nbif_hwid = 108
let hdp_hwid = 41

let hwid_name = function
  | 1 -> "MP1"
  | 2 -> "MP2"
  | 3 -> "THM"
  | 4 -> "SMUIO"
  | 5 -> "FUSE"
  | 6 -> "CLKA"
  | 10 -> "PWR"
  | 11 -> "GC"
  | 12 -> "UVD"
  | 13 -> "AUDIO_AZ"
  | 14 -> "ACP"
  | 15 -> "DCI"
  | 16 -> "DCO"
  | 17 -> "XDMA"
  | 18 -> "DCEAZ"
  | 19 -> "SDPMUX"
  | 20 -> "NTB"
  | 21 -> "VPE"
  | 24 -> "IOHC"
  | 28 -> "L2IMU"
  | 32 -> "VCE"
  | 34 -> "MMHUB"
  | 35 -> "ATHUB"
  | 36 -> "DBGU_NBIO"
  | 37 -> "DFX"
  | 38 -> "DBGU0"
  | 39 -> "DBGU1"
  | 40 -> "OSSSYS"
  | 41 -> "HDP"
  | 42 -> "SDMA0"
  | 43 -> "SDMA1"
  | 44 -> "ISP"
  | 45 -> "DBGU_IO"
  | 46 -> "DF"
  | 47 -> "CLKB"
  | 48 -> "FCH"
  | 49 -> "DFX_DAP"
  | 50 -> "L1IMU_PCIE"
  | 51 -> "L1IMU_NBIF"
  | 52 -> "L1IMU_IOAGR"
  | 53 -> "L1IMU3"
  | 54 -> "L1IMU4"
  | 55 -> "L1IMU5"
  | 56 -> "L1IMU6"
  | 57 -> "L1IMU7"
  | 58 -> "L1IMU8"
  | 59 -> "L1IMU9"
  | 60 -> "L1IMU10"
  | 61 -> "L1IMU11"
  | 62 -> "L1IMU12"
  | 63 -> "L1IMU13"
  | 64 -> "L1IMU14"
  | 65 -> "L1IMU15"
  | 66 -> "WAFLC"
  | 67 -> "FCH_USB_PD"
  | 68 -> "SDMA2"
  | 69 -> "SDMA3"
  | 70 -> "PCIE"
  | 80 -> "PCS"
  | 89 -> "DDCL"
  | 90 -> "SST"
  | 91 -> "LSDMA"
  | 100 -> "IOAGR"
  | 108 -> "NBIF"
  | 124 -> "IOAPIC"
  | 128 -> "SYSTEMHUB"
  | 144 -> "NTBCCP"
  | 150 -> "UMC"
  | 168 -> "SATA"
  | 170 -> "USB"
  | 176 -> "CCXSEC"
  | 200 -> "XGMI"
  | 216 -> "XGBE"
  | 255 -> "MP0"
  | 271 -> "DMU"
  | 272 -> "DIO"
  | 274 -> "DAZ"
  | _ -> ""
