(* Generated by gen/gen.py from the excerpts in gen/headers; do not edit. *)

(* The discovery table *)

let binary_signature = 0x28211407
let discovery_table_signature = 0x53445049
let gc_table_id = 0x4347
let harvest_table_signature = 0x56524148
let discovery_tmr_offset = 0x10000
let discovery_tmr_size = 0x2800

(* The tables the binary header lists, by index. *)
let ip_discovery_table = 0
let gc_table = 1
let harvest_info_table = 2

(* Layouts: each field as (byte offset, bytes), or (bit offset, bits) for a
   bit field; an array's bytes are its element's. *)
module Binary_header = struct
  let sizeof = 60
  let binary_signature = (0, 4)
  let binary_checksum = (8, 2)
  let binary_size = (10, 2)
  let table_list = (12, 8)
end

module Table_info = struct
  let sizeof = 8
  let offset = (0, 2)
  let checksum = (2, 2)
end

module Ip_discovery_header = struct
  let sizeof = 80
  let signature = (0, 4)
  let version = (4, 2)
  let size = (6, 2)
  let num_dies = (12, 2)
  let die_info = (14, 4)
  let base_addr_64_bit = (624, 1)
end

module Die_info = struct
  let sizeof = 4
  let die_offset = (2, 2)
end

module Die_header = struct
  let sizeof = 4
  let die_id = (0, 2)
  let num_ips = (2, 2)
end

module Ip_v4 = struct
  let sizeof = 8
  let hw_id = (0, 2)
  let instance_number = (2, 1)
  let num_base_address = (3, 1)
  let major = (4, 1)
  let minor = (5, 1)
  let revision = (6, 1)
end

module Gpu_info_header = struct
  let sizeof = 12
  let table_id = (0, 4)
  let version_major = (4, 2)
  let size = (8, 4)
end

module Gc_info_v1_0 = struct
  let sizeof = 88
  let gc_num_se = (12, 4)
  let gc_num_wgp0_per_sa = (16, 4)
  let gc_num_wgp1_per_sa = (20, 4)
  let gc_max_waves_per_simd = (60, 4)
  let gc_max_scratch_slots_per_cu = (64, 4)
  let gc_lds_size = (68, 4)
  let gc_num_sa_per_se = (76, 4)
end

module Gc_info_v2_0 = struct
  let sizeof = 80
  let gc_num_se = (12, 4)
  let gc_num_cu_per_sh = (16, 4)
  let gc_num_sh_per_se = (20, 4)
  let gc_max_waves_per_simd = (60, 4)
  let gc_max_scratch_slots_per_cu = (64, 4)
  let gc_lds_size = (68, 4)
end

module Harvest_info_header = struct
  let sizeof = 8
  let signature = (0, 4)
end

module Harvest_info = struct
  let sizeof = 4
  let hw_id = (0, 2)
  let number_instance = (2, 1)
end

module Harvest_table = struct
  let sizeof = 136
  let list = (8, 4)
end

(* The blocks' hardware IDs, and their names *)

let gc_hwid = 11
let sdma0_hwid = 42
let sdma1_hwid = 43
let sdma2_hwid = 68
let sdma3_hwid = 69
let mp0_hwid = 255
let mp1_hwid = 1
let mmhub_hwid = 34
let osssys_hwid = 40
let nbif_hwid = 108
let hdp_hwid = 41

let hwid_name = function
  | 1 -> "MP1"
  | 2 -> "MP2"
  | 3 -> "THM"
  | 4 -> "SMUIO"
  | 5 -> "FUSE"
  | 6 -> "CLKA"
  | 10 -> "PWR"
  | 11 -> "GC"
  | 12 -> "UVD"
  | 13 -> "AUDIO_AZ"
  | 14 -> "ACP"
  | 15 -> "DCI"
  | 16 -> "DCO"
  | 17 -> "XDMA"
  | 18 -> "DCEAZ"
  | 19 -> "SDPMUX"
  | 20 -> "NTB"
  | 21 -> "VPE"
  | 24 -> "IOHC"
  | 28 -> "L2IMU"
  | 32 -> "VCE"
  | 34 -> "MMHUB"
  | 35 -> "ATHUB"
  | 36 -> "DBGU_NBIO"
  | 37 -> "DFX"
  | 38 -> "DBGU0"
  | 39 -> "DBGU1"
  | 40 -> "OSSSYS"
  | 41 -> "HDP"
  | 42 -> "SDMA0"
  | 43 -> "SDMA1"
  | 44 -> "ISP"
  | 45 -> "DBGU_IO"
  | 46 -> "DF"
  | 47 -> "CLKB"
  | 48 -> "FCH"
  | 49 -> "DFX_DAP"
  | 50 -> "L1IMU_PCIE"
  | 51 -> "L1IMU_NBIF"
  | 52 -> "L1IMU_IOAGR"
  | 53 -> "L1IMU3"
  | 54 -> "L1IMU4"
  | 55 -> "L1IMU5"
  | 56 -> "L1IMU6"
  | 57 -> "L1IMU7"
  | 58 -> "L1IMU8"
  | 59 -> "L1IMU9"
  | 60 -> "L1IMU10"
  | 61 -> "L1IMU11"
  | 62 -> "L1IMU12"
  | 63 -> "L1IMU13"
  | 64 -> "L1IMU14"
  | 65 -> "L1IMU15"
  | 66 -> "WAFLC"
  | 67 -> "FCH_USB_PD"
  | 68 -> "SDMA2"
  | 69 -> "SDMA3"
  | 70 -> "PCIE"
  | 80 -> "PCS"
  | 89 -> "DDCL"
  | 90 -> "SST"
  | 91 -> "LSDMA"
  | 100 -> "IOAGR"
  | 108 -> "NBIF"
  | 124 -> "IOAPIC"
  | 128 -> "SYSTEMHUB"
  | 144 -> "NTBCCP"
  | 150 -> "UMC"
  | 168 -> "SATA"
  | 170 -> "USB"
  | 176 -> "CCXSEC"
  | 200 -> "XGMI"
  | 216 -> "XGBE"
  | 255 -> "MP0"
  | 271 -> "DMU"
  | 272 -> "DIO"
  | 274 -> "DAZ"
  | _ -> ""

(* Firmware images *)

(* The headers of images, laid out as the discovery table's. *)
module Common_firmware_header = struct
  let sizeof = 32
  let header_version_major = (8, 2)
  let header_version_minor = (10, 2)
  let ucode_version = (16, 4)
  let ucode_size_bytes = (20, 4)
  let ucode_array_offset_bytes = (24, 4)
end

module Psp_fw_bin_desc = struct
  let sizeof = 16
  let fw_type = (0, 4)
  let offset_bytes = (8, 4)
  let size_bytes = (12, 4)
end

module Psp_firmware_header_v2_0 = struct
  let sizeof = 36
  let psp_fw_bin_count = (32, 4)
  let psp_fw_bin = (36, 16)
end

module Psp_firmware_header_v2_1 = struct
  let sizeof = 40
  let psp_fw_bin_count = (32, 4)
  let psp_aux_fw_bin_index = (36, 4)
  let psp_fw_bin = (40, 16)
end

module Smc_soft_pptable_entry = struct
  let sizeof = 12
  let id = (0, 4)
  let ppt_offset_bytes = (4, 4)
  let ppt_size_bytes = (8, 4)
end

module Smc_firmware_header_v2_1 = struct
  let sizeof = 44
  let pptable_count = (36, 4)
  let pptable_entry_offset = (40, 4)
end

module Sdma_firmware_header_v2_0 = struct
  let sizeof = 64
  let ctx_ucode_size_bytes = (36, 4)
  let ctl_ucode_offset = (48, 4)
  let ctl_ucode_size_bytes = (52, 4)
end

module Sdma_firmware_header_v3_0 = struct
  let sizeof = 44
  let ucode_size_bytes = (40, 4)
end

module Gfx_firmware_header_v1_0 = struct
  let sizeof = 44
  let jt_offset = (36, 4)
  let jt_size = (40, 4)
end

module Gfx_firmware_header_v2_0 = struct
  let sizeof = 60
  let ucode_size_bytes = (36, 4)
  let data_size_bytes = (44, 4)
  let data_offset_bytes = (48, 4)
  let ucode_start_addr_lo = (52, 4)
  let ucode_start_addr_hi = (56, 4)
end

module Imu_firmware_header_v1_0 = struct
  let sizeof = 48
  let imu_iram_ucode_size_bytes = (32, 4)
  let imu_dram_ucode_size_bytes = (40, 4)
end

module Rlc_firmware_header_v2_1 = struct
  let sizeof = 156
  let save_restore_list_cntl_size_bytes = (116, 4)
  let save_restore_list_cntl_offset_bytes = (120, 4)
  let save_restore_list_gpm_size_bytes = (132, 4)
  let save_restore_list_gpm_offset_bytes = (136, 4)
  let save_restore_list_srm_size_bytes = (148, 4)
  let save_restore_list_srm_offset_bytes = (152, 4)
end

module Rlc_firmware_header_v2_2 = struct
  let sizeof = 172
  let rlc_iram_ucode_size_bytes = (156, 4)
  let rlc_iram_ucode_offset_bytes = (160, 4)
  let rlc_dram_ucode_size_bytes = (164, 4)
  let rlc_dram_ucode_offset_bytes = (168, 4)
end

module Rlc_firmware_header_v2_3 = struct
  let sizeof = 204
  let rlcp_ucode_size_bytes = (180, 4)
  let rlcp_ucode_offset_bytes = (184, 4)
  let rlcv_ucode_size_bytes = (196, 4)
  let rlcv_ucode_offset_bytes = (200, 4)
end

(* The components of the PSP's own image, by type. *)
let psp_fw_type_psp_sos = 1
let psp_fw_type_psp_sys_drv = 2
let psp_fw_type_psp_kdb = 3
let psp_fw_type_psp_toc = 4
let psp_fw_type_psp_spl = 5
let psp_fw_type_psp_rl = 6
let psp_fw_type_psp_soc_drv = 7
let psp_fw_type_psp_intf_drv = 8
let psp_fw_type_psp_dbg_drv = 9
let psp_fw_type_psp_ras_drv = 10

(* The types the PSP loads the other images' pieces as. *)
let gfx_fw_type_cp_me = 1
let gfx_fw_type_cp_pfp = 2
let gfx_fw_type_cp_mec = 4
let gfx_fw_type_cp_mec_me1 = 5
let gfx_fw_type_rlc_v = 7
let gfx_fw_type_rlc_g = 8
let gfx_fw_type_sdma0 = 9
let gfx_fw_type_sdma1 = 10
let gfx_fw_type_sdma2 = 52
let gfx_fw_type_sdma3 = 53
let gfx_fw_type_smu = 18
let gfx_fw_type_rlc_restore_list_gpm_mem = 20
let gfx_fw_type_rlc_restore_list_srm_mem = 21
let gfx_fw_type_rlc_restore_list_srm_cntl = 22
let gfx_fw_type_rlc_p = 25
let gfx_fw_type_rlc_iram = 26
let gfx_fw_type_rlc_dram_boot = 48
let gfx_fw_type_p2s_table = 129
let gfx_fw_type_reg_list = 67
let gfx_fw_type_imu_i = 68
let gfx_fw_type_imu_d = 69
let gfx_fw_type_sdma_ucode_th0 = 71
let gfx_fw_type_sdma_ucode_th1 = 72
let gfx_fw_type_rs64_pfp = 87
let gfx_fw_type_rs64_me = 88
let gfx_fw_type_rs64_mec = 89
let gfx_fw_type_rs64_pfp_p0_stack = 90
let gfx_fw_type_rs64_me_p0_stack = 92
let gfx_fw_type_rs64_mec_p0_stack = 94

(* The pinned images of linux-firmware at 0a6871b19abf: path, BLAKE2b-256
   digest and URL. *)
let pinned = [
  ("amdgpu/gc_11_0_0_imu.bin", "493bf7818bd22b0f26be3035ab5b55f758157481a6067400b8d51b07f1afee0c", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_0_imu.bin");
  ("amdgpu/gc_11_0_0_mec.bin", "56c801ca9770385d631c9e18f2f2d930a377fefc3f2de3267387392730319853", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_0_mec.bin");
  ("amdgpu/gc_11_0_0_rlc.bin", "9c943f9b61361743a159b92a1939f3e1394064fe59406f9035f49088548d65ff", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_0_rlc.bin");
  ("amdgpu/gc_11_0_2_imu.bin", "5ada64386c344a47d9867d0c3c38e02a96f00f535f3f0e4cfd6703739a3ff7e0", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_2_imu.bin");
  ("amdgpu/gc_11_0_2_mec.bin", "ebcf431e393ca5ea4621a3eff94824d4450c61931883dcfb792d57eea4f7495f", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_2_mec.bin");
  ("amdgpu/gc_11_0_2_rlc.bin", "98418cc76bc8de4fa8e3f748a672e70a86a7dd8ba1c39b5bb3b8f29c46f9bce7", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_11_0_2_rlc.bin");
  ("amdgpu/gc_12_0_0_imu.bin", "8b675e9fe016e0161280f2e4fffd51790ce7154107b575f71599b68ee5fe05e0", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_0_imu.bin");
  ("amdgpu/gc_12_0_0_me.bin", "46c635167af58fe9b7ed69c64cdd240dffde5afdb533fbc87d15979d8bb59152", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_0_me.bin");
  ("amdgpu/gc_12_0_0_mec.bin", "3457c6be3043af4f6efb7a4c542ff6764275d3c2ce18a9551b5047eb2b16d0b0", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_0_mec.bin");
  ("amdgpu/gc_12_0_0_pfp.bin", "869e95753a76cecddb52f56134337117431eeb8b3e4e7ce43f20b6a56f8152ba", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_0_pfp.bin");
  ("amdgpu/gc_12_0_0_rlc.bin", "66f56aff8a7f0a85eddc652284c8b03f4efef6574d241561945949471bad9e82", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_0_rlc.bin");
  ("amdgpu/gc_12_0_1_imu.bin", "59432404403e2380195d9d05a08521394d68150cdad1689fd74c1565c0df64c9", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_1_imu.bin");
  ("amdgpu/gc_12_0_1_me.bin", "7ecef1c20442c1e0123b99dbf61793cb30817c603f749ec42ce764029aff011b", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_1_me.bin");
  ("amdgpu/gc_12_0_1_mec.bin", "38e038f4f003a9583334764dba3ccf4351f7ce70859595754084becd9be60115", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_1_mec.bin");
  ("amdgpu/gc_12_0_1_pfp.bin", "9e5e25507d5a5082ea525de8ca01aab80303c57d139c40dc5318f2a5b2a9e0da", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_1_pfp.bin");
  ("amdgpu/gc_12_0_1_rlc.bin", "facd943921bce257c6c57b82d33bba6b092fad02cb337703e230b1ea314604ce", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_12_0_1_rlc.bin");
  ("amdgpu/gc_9_4_3_mec.bin", "7953fe2bd6e89061ab17040520d5a36d847fdcae7a0854ef6839d81c3242c8f3", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_9_4_3_mec.bin");
  ("amdgpu/gc_9_4_3_rlc.bin", "0c57739326e3e61404d0bcc826b50704c15346946094cb239fe77e0297741b3e", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_9_4_3_rlc.bin");
  ("amdgpu/gc_9_5_0_mec.bin", "b8bd1f38b94fd9e181f55eb783a6132cb973f0cf0b6fc7137a6d146189a4559a", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_9_5_0_mec.bin");
  ("amdgpu/gc_9_5_0_rlc.bin", "5e46fc47c19beb074002a03a99841eada46237d98669702d9be5e63a4327ae82", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/gc_9_5_0_rlc.bin");
  ("amdgpu/psp_13_0_0_sos.bin", "b8eda8b2f60b19cbe0832cf51a85ec545b0897baaaa351ffb512f2e02b93f239", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_0_sos.bin");
  ("amdgpu/psp_13_0_10_sos.bin", "4ba040408368e13a6f52e73c1c9c9e5deb1ec9e163ddfd8c61cde975c736e61f", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_10_sos.bin");
  ("amdgpu/psp_13_0_12_sos.bin", "ea250b493c351cc03bb4ece20c9d13eb40b8d2817031bcbd143c35135979808a", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_12_sos.bin");
  ("amdgpu/psp_13_0_14_sos.bin", "1212346d3919e2b81ce313b43a5380c5041e2d5d4901490792c0e4a46f7e3885", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_14_sos.bin");
  ("amdgpu/psp_13_0_15_sos.bin", "d24ca1297219478b1c09976ed8cc014998110dcc4f402a5405878311d3b59571", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_15_sos.bin");
  ("amdgpu/psp_13_0_6_sos.bin", "b1a1621e0c81ab04b6aecdf5bb646dda8bb23ba46a4f86088888ef1d805de503", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_6_sos.bin");
  ("amdgpu/psp_13_0_7_sos.bin", "89240f0e13de94fb9ec48b29cf05ff3612df08444172fb6024edf220180b3cf8", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_13_0_7_sos.bin");
  ("amdgpu/psp_14_0_2_sos.bin", "3ccc02c37acdad15b19b0c82d10c8b7c8cb3f62a8ba39d11cd7a7c569e1b630e", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_14_0_2_sos.bin");
  ("amdgpu/psp_14_0_3_sos.bin", "f931608c2609330d87b67da69f964a25158f7cc05603cfaf5387f1a41ca15734", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/psp_14_0_3_sos.bin");
  ("amdgpu/sdma_4_4_2.bin", "96893a8c3e9ccdc4739f0f16f44ae9718b06d71c52184281aa630a9710cfdc1e", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_4_4_2.bin");
  ("amdgpu/sdma_4_4_4.bin", "627b82c9e6765f5a50cda1f7d2ef4842b8635b8153b98b04656b6b0d80f6b1dc", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_4_4_4.bin");
  ("amdgpu/sdma_4_4_5.bin", "3c994e0a8d7529733b552c3124eca3d5779dfdc3dc17d2a9545531787957125d", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_4_4_5.bin");
  ("amdgpu/sdma_6_0_0.bin", "5790bdb221eff6b029ac225b81b2231d94941edc29396d62795955096d21a619", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_6_0_0.bin");
  ("amdgpu/sdma_6_0_1.bin", "ccb1403ad8732f3bb50e702e7dfb61728e712e4a9cf797a24f5e42c509d6b36f", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_6_0_1.bin");
  ("amdgpu/sdma_6_0_2.bin", "e19edd4a60da684c9addffbbc3ef9a9e1fdaf741d7e31c1f5a86e3bfb32f10e2", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_6_0_2.bin");
  ("amdgpu/sdma_6_0_3.bin", "87f73abd7a21a05338355077946ba9b1a88fddc6cbb399533e9b6afc132fb63a", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_6_0_3.bin");
  ("amdgpu/sdma_7_0_0.bin", "5f68478ba78dad131a1fd1cb42a589479be9fcef38c547f48fd3e91eb25f314b", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_7_0_0.bin");
  ("amdgpu/sdma_7_0_1.bin", "6b801a9fad988b477218d2fad6997917504b9c5ff450424347c35df3a78ee7e3", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/sdma_7_0_1.bin");
  ("amdgpu/smu_13_0_0.bin", "fa7c9299dfc0e0965eb6c8fb91a29881b30265a3ceb1690b4fe7f86d8609fa0f", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_13_0_0.bin");
  ("amdgpu/smu_13_0_10.bin", "d6c5a9fa211985ab00438955931adff5eaf456794d38b198ce92ff39d283dc26", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_13_0_10.bin");
  ("amdgpu/smu_13_0_14.bin", "03efa4555167f71cb1cb6057a67fdf0ea08dbbe9712e3e53c0a13dccdd7fd37c", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_13_0_14.bin");
  ("amdgpu/smu_13_0_6.bin", "1402d6bc695bb2a7234c46ab4f6a936962980ff3ad6b244f1b7ab5a4c421bd0d", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_13_0_6.bin");
  ("amdgpu/smu_13_0_7.bin", "d7ac3008455192671058e383abd015c3f539c920e084ac05cb334e1c886e0735", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_13_0_7.bin");
  ("amdgpu/smu_14_0_2.bin", "42107345f8e0f82a654001ec6a400928a8ae7e5d215bf8016267ce26655dd484", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_14_0_2.bin");
  ("amdgpu/smu_14_0_3.bin", "1baabe29c0db29828858305d49ec3b931fa020d723f7362c522c62af5e85a918", "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/amdgpu/smu_14_0_3.bin");
]
