# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generates the vendor constants tolk.next's queue encoders read, from
tinygrad's autogen modules.

    uv run packages/tolk/next/lib/runtime/autogen/gen.py [--check]

It imports tinygrad from `_tinygrad_next`, which must be at TINYGRAD, and
writes each vendor's module beside this script: `nv_gpu.ml`. With --check it
writes nothing and fails if a committed module differs.

A module holds only the constants its encoder reads, as the inventories below
name them, lowercased: a method or a value as an integer, a field of a method's
word as its bit range `(hi, lo)`. NV's launch descriptors (QMDs) are tables of
the fields the encoder writes, by name, for each descriptor version, as
tinygrad's `QMD` reads them: a field that takes an index is named once for each
of 0 to 7, with the index after an underscore. NV's constants are the same in
the driver releases 570, 580 and 610, which the script checks.
"""

import argparse
import pathlib
import subprocess
import sys

TINYGRAD = "79af1ca70e7021f504919c4ff5631245acc33ed6"
HERE = pathlib.Path(__file__).resolve().parent
ROOT = pathlib.Path(subprocess.check_output(
    ["git", "-C", str(HERE), "rev-parse", "--path-format=absolute", "--git-common-dir"], text=True).strip()).parent
TINYGRAD_DIR = ROOT / "_tinygrad_next"

HEADER = f"""(* Generated by gen.py from tinygrad {TINYGRAD}'s
   autogen modules. Do not edit. *)
"""

# NV

NV_CONSTANTS = [
    "BLACKWELL_COMPUTE_A",
    # host methods, on every channel
    "NVC56F_SEM_ADDR_LO", "NVC56F_SEM_EXECUTE", "NVC56F_SEM_EXECUTE_OPERATION",
    "NVC56F_SEM_EXECUTE_OPERATION_ACQ_CIRC_GEQ", "NVC56F_SEM_EXECUTE_OPERATION_RELEASE",
    "NVC56F_SEM_EXECUTE_PAYLOAD_SIZE", "NVC56F_SEM_EXECUTE_PAYLOAD_SIZE_64BIT",
    "NVC56F_SEM_EXECUTE_RELEASE_WFI", "NVC56F_SEM_EXECUTE_RELEASE_WFI_EN",
    "NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP", "NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP_EN",
    "NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP_DIS", "NVC56F_NON_STALL_INTERRUPT",
    # the compute engine
    "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI", "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION",
    "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION_TRUE", "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_GLOBAL_DATA",
    "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_GLOBAL_DATA_TRUE", "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT",
    "NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT_TRUE", "NVC6C0_SEND_PCAS_A", "NVC6C0_SEND_SIGNALING_PCAS2_B",
    "NVC6C0_SEND_SIGNALING_PCAS2_B_PCAS_ACTION_PREFETCH_SCHEDULE",
    "NVC6C0_QMDV03_00_CWD_MEMBAR_TYPE_L1_SYSMEMBAR", "NVCEC0_QMDV05_00_QMD_TYPE_GRID_CTA",
    # the copy engine
    "NVC6B5_OFFSET_IN_UPPER", "NVC6B5_LINE_LENGTH_IN", "NVC6B5_SET_SEMAPHORE_A", "NVC6B5_LAUNCH_DMA",
    "NVC6B5_LAUNCH_DMA_DATA_TRANSFER_TYPE", "NVC6B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED",
    "NVC6B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT", "NVC6B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH",
    "NVC6B5_LAUNCH_DMA_DST_MEMORY_LAYOUT", "NVC6B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH",
    "NVC6B5_LAUNCH_DMA_FLUSH_ENABLE", "NVC6B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE",
    "NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE", "NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE",
    "NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_FOUR_WORD_SEMAPHORE",
]

# The fields of the launch descriptors the encoder writes, as QMD names them.
QMD_FIELDS = [
    "grid_width", "grid_height", "grid_depth", "cta_raster_width", "cta_raster_height", "cta_raster_depth",
    *[f"cta_thread_dimension{j}" for j in range(3)],
    "program_address_lower", "program_address_upper", "program_address_lower_shifted4", "program_address_upper_shifted4",
    "program_prefetch_addr_lower_shifted", "program_prefetch_addr_upper_shifted", "program_prefetch_size",
    *[f"{f}_{i}" for f in ("constant_buffer_addr_lower", "constant_buffer_addr_upper", "constant_buffer_addr_lower_shifted6",
                             "constant_buffer_addr_upper_shifted6", "constant_buffer_size_shifted4", "constant_buffer_valid")
      for i in range(8)],
    *[f for i in range(2) for f in (f"release{i}_enable", f"release{i}_address_lower", f"release{i}_address_upper",
                                     f"release{i}_payload_lower", f"release{i}_payload_upper", f"release{i}_structure_size",
                                     f"release{i}_payload64b", f"release_semaphore{i}_addr_lower", f"release_semaphore{i}_addr_upper",
                                     f"release_semaphore{i}_payload_lower", f"release_semaphore{i}_payload_upper",
                                     f"release_structure_size_{i}")],
    "dependent_qmd0_pointer", "dependent_qmd0_action", "dependent_qmd0_prefetch", "dependent_qmd0_enable",
    "qmd_major_version", "qmd_type", "register_count", "register_count_v", "shared_memory_size", "shared_memory_size_shifted7",
    "shader_local_memory_high_size", "shader_local_memory_high_size_shifted4", "sm_global_caching_enable", "qmd_group_id",
    "invalidate_texture_header_cache", "invalidate_texture_sampler_cache", "invalidate_texture_data_cache",
    "invalidate_shader_data_cache", "api_visible_call_limit", "sampler_index", "barrier_count", "cwd_membar_type",
    "constant_buffer_invalidate_0", "min_sm_config_shared_mem_size", "target_sm_config_shared_mem_size",
    "max_sm_config_shared_mem_size", "sass_version",
]
QMD_VERSIONS = {"qmd_v3": "NVC6C0_QMDV03_00", "qmd_v5": "NVCEC0_QMDV05_00"}


def qmd_fields(mod, pref):
    """The fields of a descriptor version, as tinygrad's QMD builds them."""
    return {**{name[len(pref) + 1:]: dt for name, dt in mod.__dict__.items() if name.startswith(pref) and isinstance(dt, tuple)},
            **{name[len(pref) + 1:] + f"_{i}": dt(i) for name, dt in mod.__dict__.items() for i in range(8)
               if name.startswith(pref) and callable(dt)}}


def ml_value(v):
    if isinstance(v, tuple): return f"({v[0]}, {v[1]})"
    return f"0x{v:x}" if v >= 16 else str(v)


def nv():
    from tinygrad.runtime.autogen import nv_570, nv_580, nv_610
    for name in NV_CONSTANTS:
        values = {getattr(m, name) for m in (nv_570, nv_580, nv_610)}
        if len(values) != 1: sys.exit(f"{name} differs across the driver releases: {values}")
    lines = [HEADER]
    lines += [f"let {name.lower()} = {ml_value(getattr(nv_570, name))}" for name in NV_CONSTANTS]
    for ml_name, pref in QMD_VERSIONS.items():
        tables = [qmd_fields(m, pref) for m in (nv_570, nv_580, nv_610)]
        if any(t != tables[0] for t in tables): sys.exit(f"{pref} differs across the driver releases")
        rows = [f'    ("{f}", {ml_value(tables[0][f.upper()])});' for f in QMD_FIELDS if f.upper() in tables[0]]
        lines += ["", f"(* The fields of {pref}'s launch descriptors, by name. *)", f"let {ml_name} =", "  [", *rows, "  ]"]
    return "\n".join(lines) + "\n"


MODULES = {"nv_gpu.ml": nv}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="write nothing; fail if a committed module differs")
    args = parser.parse_args()
    head = subprocess.check_output(["git", "-C", str(TINYGRAD_DIR), "rev-parse", "HEAD"], text=True).strip()
    if head != TINYGRAD: sys.exit(f"{TINYGRAD_DIR} is at {head}, not at {TINYGRAD}")
    sys.path.insert(0, str(TINYGRAD_DIR))
    stale = []
    for name, make in MODULES.items():
        text, path = make(), HERE / name
        if args.check:
            if not path.is_file() or path.read_text() != text: stale.append(name)
        else:
            path.write_text(text)
    if stale: sys.exit(f"stale: {', '.join(stale)}; run gen.py")


if __name__ == "__main__":
    main()
