(* Generated by gen.py from tinygrad 79af1ca70e7021f504919c4ff5631245acc33ed6's
   autogen modules. Do not edit. *)

let blackwell_compute_a = 0xcdc0
let nvc56f_sem_addr_lo = 0x5c
let nvc56f_sem_execute = 0x6c
let nvc56f_sem_execute_operation = (2, 0)
let nvc56f_sem_execute_operation_acq_circ_geq = 3
let nvc56f_sem_execute_operation_release = 1
let nvc56f_sem_execute_payload_size = (24, 24)
let nvc56f_sem_execute_payload_size_64bit = 1
let nvc56f_sem_execute_release_wfi = (20, 20)
let nvc56f_sem_execute_release_wfi_en = 1
let nvc56f_sem_execute_release_timestamp = (25, 25)
let nvc56f_sem_execute_release_timestamp_en = 1
let nvc56f_sem_execute_release_timestamp_dis = 0
let nvc56f_non_stall_interrupt = 0x20
let nvc6c0_invalidate_shader_caches_no_wfi = 0x1698
let nvc6c0_invalidate_shader_caches_no_wfi_instruction = (0, 0)
let nvc6c0_invalidate_shader_caches_no_wfi_instruction_true = 1
let nvc6c0_invalidate_shader_caches_no_wfi_global_data = (4, 4)
let nvc6c0_invalidate_shader_caches_no_wfi_global_data_true = 1
let nvc6c0_invalidate_shader_caches_no_wfi_constant = (12, 12)
let nvc6c0_invalidate_shader_caches_no_wfi_constant_true = 1
let nvc6c0_send_pcas_a = 0x2b4
let nvc6c0_send_signaling_pcas2_b = 0x2c0
let nvc6c0_send_signaling_pcas2_b_pcas_action_prefetch_schedule = 9
let nvc6c0_qmdv03_00_cwd_membar_type_l1_sysmembar = 1
let nvcec0_qmdv05_00_qmd_type_grid_cta = 2
let nvc6b5_offset_in_upper = 0x400
let nvc6b5_line_length_in = 0x418
let nvc6b5_set_semaphore_a = 0x240
let nvc6b5_launch_dma = 0x300
let nvc6b5_launch_dma_data_transfer_type = (1, 0)
let nvc6b5_launch_dma_data_transfer_type_non_pipelined = 2
let nvc6b5_launch_dma_src_memory_layout = (7, 7)
let nvc6b5_launch_dma_src_memory_layout_pitch = 1
let nvc6b5_launch_dma_dst_memory_layout = (8, 8)
let nvc6b5_launch_dma_dst_memory_layout_pitch = 1
let nvc6b5_launch_dma_flush_enable = (2, 2)
let nvc6b5_launch_dma_flush_enable_true = 1
let nvc6b5_launch_dma_semaphore_type = (4, 3)
let nvc6b5_launch_dma_semaphore_type_release_one_word_semaphore = 1
let nvc6b5_launch_dma_semaphore_type_release_four_word_semaphore = 2

(* The fields of NVC6C0_QMDV03_00's launch descriptors, by name. *)
let qmd_v3 =
  [
    ("cta_raster_width", (415, 384));
    ("cta_raster_height", (431, 416));
    ("cta_raster_depth", (463, 448));
    ("cta_thread_dimension0", (607, 592));
    ("cta_thread_dimension1", (623, 608));
    ("cta_thread_dimension2", (639, 624));
    ("program_address_lower", (1567, 1536));
    ("program_address_upper", (1584, 1568));
    ("program_prefetch_addr_lower_shifted", (287, 256));
    ("program_prefetch_addr_upper_shifted", (1640, 1632));
    ("program_prefetch_size", (1649, 1641));
    ("constant_buffer_addr_lower_0", (1055, 1024));
    ("constant_buffer_addr_lower_1", (1119, 1088));
    ("constant_buffer_addr_lower_2", (1183, 1152));
    ("constant_buffer_addr_lower_3", (1247, 1216));
    ("constant_buffer_addr_lower_4", (1311, 1280));
    ("constant_buffer_addr_lower_5", (1375, 1344));
    ("constant_buffer_addr_lower_6", (1439, 1408));
    ("constant_buffer_addr_lower_7", (1503, 1472));
    ("constant_buffer_addr_upper_0", (1072, 1056));
    ("constant_buffer_addr_upper_1", (1136, 1120));
    ("constant_buffer_addr_upper_2", (1200, 1184));
    ("constant_buffer_addr_upper_3", (1264, 1248));
    ("constant_buffer_addr_upper_4", (1328, 1312));
    ("constant_buffer_addr_upper_5", (1392, 1376));
    ("constant_buffer_addr_upper_6", (1456, 1440));
    ("constant_buffer_addr_upper_7", (1520, 1504));
    ("constant_buffer_size_shifted4_0", (1087, 1075));
    ("constant_buffer_size_shifted4_1", (1151, 1139));
    ("constant_buffer_size_shifted4_2", (1215, 1203));
    ("constant_buffer_size_shifted4_3", (1279, 1267));
    ("constant_buffer_size_shifted4_4", (1343, 1331));
    ("constant_buffer_size_shifted4_5", (1407, 1395));
    ("constant_buffer_size_shifted4_6", (1471, 1459));
    ("constant_buffer_size_shifted4_7", (1535, 1523));
    ("constant_buffer_valid_0", (640, 640));
    ("constant_buffer_valid_1", (641, 641));
    ("constant_buffer_valid_2", (642, 642));
    ("constant_buffer_valid_3", (643, 643));
    ("constant_buffer_valid_4", (644, 644));
    ("constant_buffer_valid_5", (645, 645));
    ("constant_buffer_valid_6", (646, 646));
    ("constant_buffer_valid_7", (647, 647));
    ("release0_enable", (823, 823));
    ("release0_address_lower", (799, 768));
    ("release0_address_upper", (807, 800));
    ("release0_payload_lower", (863, 832));
    ("release0_payload_upper", (895, 864));
    ("release0_structure_size", (831, 830));
    ("release0_payload64b", (829, 829));
    ("release1_enable", (951, 951));
    ("release1_address_lower", (927, 896));
    ("release1_address_upper", (935, 928));
    ("release1_payload_lower", (991, 960));
    ("release1_payload_upper", (1023, 992));
    ("release1_structure_size", (959, 958));
    ("release1_payload64b", (957, 957));
    ("dependent_qmd0_pointer", (511, 480));
    ("dependent_qmd0_action", (515, 513));
    ("dependent_qmd0_prefetch", (516, 516));
    ("dependent_qmd0_enable", (512, 512));
    ("qmd_major_version", (583, 580));
    ("register_count_v", (656, 648));
    ("shared_memory_size", (561, 544));
    ("shader_local_memory_high_size", (1623, 1600));
    ("sm_global_caching_enable", (134, 134));
    ("qmd_group_id", (133, 128));
    ("invalidate_texture_header_cache", (186, 186));
    ("invalidate_texture_sampler_cache", (187, 187));
    ("invalidate_texture_data_cache", (188, 188));
    ("invalidate_shader_data_cache", (189, 189));
    ("api_visible_call_limit", (378, 378));
    ("sampler_index", (382, 382));
    ("barrier_count", (767, 763));
    ("cwd_membar_type", (369, 368));
    ("constant_buffer_invalidate_0", (1074, 1074));
    ("min_sm_config_shared_mem_size", (567, 562));
    ("target_sm_config_shared_mem_size", (662, 657));
    ("max_sm_config_shared_mem_size", (574, 569));
    ("sass_version", (1663, 1656));
  ]

(* The fields of NVCEC0_QMDV05_00's launch descriptors, by name. *)
let qmd_v5 =
  [
    ("grid_width", (1279, 1248));
    ("grid_height", (1295, 1280));
    ("grid_depth", (1327, 1312));
    ("cta_thread_dimension0", (1103, 1088));
    ("cta_thread_dimension1", (1119, 1104));
    ("cta_thread_dimension2", (1127, 1120));
    ("program_address_lower_shifted4", (1055, 1024));
    ("program_address_upper_shifted4", (1076, 1056));
    ("program_prefetch_addr_lower_shifted", (1919, 1888));
    ("program_prefetch_addr_upper_shifted", (1936, 1920));
    ("program_prefetch_size", (1085, 1077));
    ("constant_buffer_addr_lower_shifted6_0", (1375, 1344));
    ("constant_buffer_addr_lower_shifted6_1", (1439, 1408));
    ("constant_buffer_addr_lower_shifted6_2", (1503, 1472));
    ("constant_buffer_addr_lower_shifted6_3", (1567, 1536));
    ("constant_buffer_addr_lower_shifted6_4", (1631, 1600));
    ("constant_buffer_addr_lower_shifted6_5", (1695, 1664));
    ("constant_buffer_addr_lower_shifted6_6", (1759, 1728));
    ("constant_buffer_addr_lower_shifted6_7", (1823, 1792));
    ("constant_buffer_addr_upper_shifted6_0", (1394, 1376));
    ("constant_buffer_addr_upper_shifted6_1", (1458, 1440));
    ("constant_buffer_addr_upper_shifted6_2", (1522, 1504));
    ("constant_buffer_addr_upper_shifted6_3", (1586, 1568));
    ("constant_buffer_addr_upper_shifted6_4", (1650, 1632));
    ("constant_buffer_addr_upper_shifted6_5", (1714, 1696));
    ("constant_buffer_addr_upper_shifted6_6", (1778, 1760));
    ("constant_buffer_addr_upper_shifted6_7", (1842, 1824));
    ("constant_buffer_size_shifted4_0", (1407, 1395));
    ("constant_buffer_size_shifted4_1", (1471, 1459));
    ("constant_buffer_size_shifted4_2", (1535, 1523));
    ("constant_buffer_size_shifted4_3", (1599, 1587));
    ("constant_buffer_size_shifted4_4", (1663, 1651));
    ("constant_buffer_size_shifted4_5", (1727, 1715));
    ("constant_buffer_size_shifted4_6", (1791, 1779));
    ("constant_buffer_size_shifted4_7", (1855, 1843));
    ("constant_buffer_valid_0", (1856, 1856));
    ("constant_buffer_valid_1", (1860, 1860));
    ("constant_buffer_valid_2", (1864, 1864));
    ("constant_buffer_valid_3", (1868, 1868));
    ("constant_buffer_valid_4", (1872, 1872));
    ("constant_buffer_valid_5", (1876, 1876));
    ("constant_buffer_valid_6", (1880, 1880));
    ("constant_buffer_valid_7", (1884, 1884));
    ("release0_enable", (288, 288));
    ("release_semaphore0_addr_lower", (511, 480));
    ("release_semaphore0_addr_upper", (536, 512));
    ("release_semaphore0_payload_lower", (575, 544));
    ("release_semaphore0_payload_upper", (607, 576));
    ("release_structure_size_0", (290, 289));
    ("release1_enable", (304, 304));
    ("release_semaphore1_addr_lower", (799, 768));
    ("release_semaphore1_addr_upper", (824, 800));
    ("release_semaphore1_payload_lower", (863, 832));
    ("release_semaphore1_payload_upper", (895, 864));
    ("release_structure_size_1", (306, 305));
    ("dependent_qmd0_pointer", (415, 384));
    ("dependent_qmd0_action", (339, 337));
    ("dependent_qmd0_prefetch", (340, 340));
    ("dependent_qmd0_enable", (336, 336));
    ("qmd_major_version", (471, 468));
    ("qmd_type", (153, 151));
    ("register_count", (1136, 1128));
    ("shared_memory_size_shifted7", (1162, 1152));
    ("shader_local_memory_high_size_shifted4", (1215, 1200));
    ("qmd_group_id", (149, 144));
    ("invalidate_texture_header_cache", (472, 472));
    ("invalidate_texture_sampler_cache", (473, 473));
    ("invalidate_texture_data_cache", (474, 474));
    ("invalidate_shader_data_cache", (475, 475));
    ("api_visible_call_limit", (456, 456));
    ("sampler_index", (457, 457));
    ("barrier_count", (1141, 1137));
    ("cwd_membar_type", (625, 624));
    ("constant_buffer_invalidate_0", (1859, 1859));
    ("min_sm_config_shared_mem_size", (1168, 1163));
    ("target_sm_config_shared_mem_size", (1180, 1175));
    ("max_sm_config_shared_mem_size", (1174, 1169));
    ("sass_version", (455, 448));
  ]
