(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by ../gen/gen.py from the excerpts in ../gen/headers/nvidia;
   do not edit. The command that regenerates this file is in ../gen/gen.py.

   The values are NVIDIA's, copied from its headers under the MIT licence:

   Copyright (c) 1993-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1993-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1993-2026 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1999-2021 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1999-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2001-2022 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2001-2022, NVIDIA CORPORATION
   Copyright (c) 2002-2022 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2003-2016 NVIDIA Corporation
   Copyright (c) 2004-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2004-2026 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2005-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2005-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2005-2026 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2006-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2006-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2006-2026 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2013 NVidia Corporation
   Copyright (c) 2013-2024 NVidia Corporation
   Copyright (c) 2013-2025 NVidia Corporation
   Copyright (c) 2014-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2014-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2014-2026 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2015-2021 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2017 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2017-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2020-2023 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2020-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2020-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2021-2021 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES

   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE. *)

(* The releases whose layouts are below: 570.144, 580.105.08, 610.43.03, 615.71.09. *)
let releases = [ 570; 580; 610; 615 ]

(* Constants, the same in every release. *)
let nv01_root_client = 0x41
let nv01_device_0 = 0x80
let nv20_subdevice_0 = 0x2080
let nv01_memory_virtual = 0x70
let nv01_memory_system_os_descriptor = 0x71
let nv1_memory_system = 0x3e
let nv1_memory_user = 0x40
let fermi_vaspace_a = 0x90f1
let turing_usermode_a = 0xc461
let hopper_usermode_a = 0xc661
let ampere_channel_gpfifo_a = 0xc56f
let blackwell_channel_gpfifo_a = 0xc96f
let ampere_compute_b = 0xc7c0
let ada_compute_a = 0xc9c0
let blackwell_compute_b = 0xcec0
let ampere_dma_copy_b = 0xc7b5
let blackwell_dma_copy_b = 0xcab5
let nv_ioctl_magic = 0x46
let nv_esc_card_info = 0xc8
let nv_esc_register_fd = 0xc9
let nv_esc_rm_alloc = 0x2b
let nv_esc_rm_alloc_memory = 0x27
let nv_esc_rm_control = 0x2a
let nv_esc_rm_free = 0x29
let nv_esc_rm_map_memory = 0x4e
let nv_esc_rm_map_memory_dma = 0x57
let nv_max_devices = 0x20
let nv_mmu_pte_kind_generic_memory = 6
let nvos02_flags_physicality_noncontiguous = 1
let nvos02_flags_coherency_cached = 1
let nvos02_flags_mapping_no_map = 1
let nvos32_attr_physicality_contiguous = 2
let nvos32_attr_physicality_allow_noncontiguous = 3
let nvos32_attr_page_size_huge = 3
let nvos32_attr_location_vidmem = 0
let nvos32_attr_location_pci = 1
let nvos32_attr2_gpu_cacheable_yes = 1
let nvos32_attr2_gpu_cacheable_no = 2
let nvos32_attr2_page_size_huge_2mb = 1
let nvos32_attr2_zbc_prefer_no_zbc = 1
let nvos32_alloc_flags_map_not_required = 0x8000
let nvos32_alloc_flags_memory_handle_provided = 0x4000
let nvos32_alloc_flags_alignment_force = 0x100
let nvos32_alloc_flags_ignore_bank_placement = 1
let nvos32_alloc_flags_persistent_vidmem = 0x10000
let nvos32_type_image = 0
let nvos32_type_notifier = 0xd
let nvos33_flags_caching_type_cached = 0
let nvos33_flags_caching_type_uncached = 1
let nvos33_flags_caching_type_writecombined = 2
let nvos46_flags_page_size_4kb = 1
let nvos46_flags_cache_snoop_enable = 1
let nvos46_flags_dma_offset_fixed_true = 1
let nv0000_ctrl_cmd_system_get_build_version_v2 = 0x13e
let nv0000_ctrl_cmd_gpu_get_id_info_v2 = 0x205
let nv0080_ctrl_cmd_gpu_get_classlist = 0x800201
let nv2080_ctrl_cmd_gpu_get_gid_info = 0x2080014a
let nv2080_gpu_cmd_gpu_get_gid_flags_format_binary = 2
let nv2080_ctrl_cmd_gr_get_info = 0x20801201
let nv2080_ctrl_gr_info_index_litter_num_gpcs = 0x14
let nv2080_ctrl_gr_info_index_litter_num_tpc_per_gpc = 0x17
let nv2080_ctrl_gr_info_index_litter_num_sm_per_tpc = 0x20
let nv2080_ctrl_gr_info_index_max_warps_per_sm = 0xd
let nv2080_ctrl_gr_info_index_sm_version = 0xc
let nv2080_ctrl_cmd_fb_get_info_v2 = 0x20801303
let nv2080_ctrl_fb_info_index_heap_size = 9
let nv2080_ctrl_fb_info_index_bar1_size = 5
let nv_device_allocation_vamode_optional_multiple_vaspaces = 0
let nv_vaspace_allocation_flags_enable_page_faulting = 0x40
let nv_vaspace_allocation_flags_is_externally_owned = 8
let uvm_initialize = 0x30000001
let uvm_mm_initialize = 0x4b
let uvm_register_gpu = 0x25
let uvm_unregister_gpu = 0x26
let uvm_register_gpu_vaspace = 0x19
let uvm_unregister_gpu_vaspace = 0x1a
let uvm_enable_peer_access = 0x1d
let uvm_register_channel = 0x1b
let uvm_unregister_channel = 0x1c
let uvm_create_external_range = 0x49
let uvm_map_external_allocation = 0x21
let uvm_unmap_external = 0x42
let uvm_free = 0x22
let uvm_gpu_mapping_type_read_write_atomic = 1

(* Statuses, the same in every release. *)
let nv_ok = 0
let nv_err_no_memory = 0x51
let nv_err_invalid_address = 0x1e
let nv_err_invalid_argument = 0x1f

(* Bit fields of their words: (lowest bit, bits). *)
let nvos02_flags_physicality = (4, 4)
let nvos02_flags_coherency = (0xc, 4)
let nvos02_flags_mapping = (0x1e, 2)
let nvos32_attr_physicality = (0x1b, 2)
let nvos32_attr_page_size = (0x17, 2)
let nvos32_attr_location = (0x19, 2)
let nvos32_attr2_gpu_cacheable = (2, 2)
let nvos32_attr2_page_size_huge = (0x14, 2)
let nvos32_attr2_zbc = (0, 2)
let nvos33_flags_caching_type = (0x17, 3)
let nvos46_flags_page_size = (8, 4)
let nvos46_flags_cache_snoop = (4, 1)
let nvos46_flags_dma_offset_fixed = (0xf, 1)
let nv2080_gpu_cmd_gpu_get_gid_flags_format = (0, 2)

(* Structs: each field is (byte offset, bytes), an array's (offset, bytes
   of an element, elements). *)
module Card_info = struct
  let sizeof = 72
  let valid = (0, 1)
  let pci_info_domain = (4, 4)
  let pci_info_bus = (8, 1)
  let pci_info_slot = (9, 1)
  let gpu_id = (0x10, 4)
  let minor_number = (0x38, 4)
end

module Register_fd = struct
  let sizeof = 4
  let ctl_fd = (0, 4)
end

module Nvos00 = struct
  let sizeof = 16
  let h_root = (0, 4)
  let h_object_parent = (4, 4)
  let h_object_old = (8, 4)
  let status = (0xc, 4)
end

module Nvos02 = struct
  let sizeof = 48
  let h_root = (0, 4)
  let h_object_parent = (4, 4)
  let h_object_new = (8, 4)
  let h_class = (0xc, 4)
  let flags = (0x10, 4)
  let p_memory = (0x18, 8)
  let limit = (0x20, 8)
  let status = (0x28, 4)
end

module Nvos21 = struct
  let sizeof = 32
  let h_root = (0, 4)
  let h_object_parent = (4, 4)
  let h_object_new = (8, 4)
  let h_class = (0xc, 4)
  let p_alloc_parms = (0x10, 8)
  let params_size = (0x18, 4)
  let status = (0x1c, 4)
end

module Nvos33 = struct
  let sizeof = 48
  let h_client = (0, 4)
  let h_device = (4, 4)
  let h_memory = (8, 4)
  let offset = (0x10, 8)
  let length = (0x18, 8)
  let p_linear_address = (0x20, 8)
  let status = (0x28, 4)
  let flags = (0x2c, 4)
end

module Nvos54 = struct
  let sizeof = 32
  let h_client = (0, 4)
  let h_object = (4, 4)
  let cmd = (8, 4)
  let flags = (0xc, 4)
  let params = (0x10, 8)
  let params_size = (0x18, 4)
  let status = (0x1c, 4)
end

module Nvos02_with_fd = struct
  let sizeof = 56
  let params = (0, 0x30)
  let fd = (0x30, 4)
end

module Nvos33_with_fd = struct
  let sizeof = 56
  let params = (0, 0x30)
  let fd = (0x30, 4)
end

module Nv0080_alloc = struct
  let sizeof = 56
  let device_id = (0, 4)
  let h_client_share = (4, 4)
  let va_mode = (0x30, 4)
end

module Nv2080_alloc = struct
  let sizeof = 4
  let sub_device_id = (0, 4)
end

module Memory_virtual_alloc = struct
  let sizeof = 24
  let offset = (0, 8)
  let limit = (8, 8)
  let h_va_space = (0x10, 4)
end

module Memory_alloc = struct
  let sizeof = 128
  let owner = (0, 4)
  let type_ = (4, 4)
  let flags = (8, 4)
  let attr = (0x18, 4)
  let attr2 = (0x1c, 4)
  let format = (0x20, 4)
  let size = (0x40, 8)
  let alignment = (0x48, 8)
  let offset = (0x50, 8)
  let limit = (0x58, 8)
end

module Build_version = struct
  let sizeof = 1032
  let driver_version_buffer = (0, 1, 0x100)
end

module Id_info = struct
  let sizeof = 32
  let gpu_id = (0, 4)
  let device_instance = (8, 4)
end

module Classlist = struct
  let sizeof = 16
  let num_classes = (0, 4)
  let class_list = (8, 8)
end

module Gid_info = struct
  let sizeof = 268
  let flags = (4, 4)
  let length = (8, 4)
  let data = (0xc, 1, 0x100)
end

module Gr_info = struct
  let sizeof = 8
  let index = (0, 4)
  let data = (4, 4)
end

module Gr_get_info = struct
  let sizeof = 32
  let gr_info_list_size = (0, 4)
  let gr_info_list = (8, 8)
end

module Fb_info = struct
  let sizeof = 8
  let index = (0, 4)
  let data = (4, 4)
end

module Uvm_initialize = struct
  let sizeof = 16
  let flags = (0, 8)
  let rm_status = (8, 4)
end

module Uvm_mm_initialize = struct
  let sizeof = 8
  let uvm_fd = (0, 4)
  let rm_status = (4, 4)
end

module Uvm_register_gpu = struct
  let sizeof = 40
  let gpu_uuid = (0, 0x10)
  let rm_ctrl_fd = (0x18, 4)
  let h_client = (0x1c, 4)
  let h_smc_part_ref = (0x20, 4)
  let rm_status = (0x24, 4)
end

module Uvm_register_gpu_vaspace = struct
  let sizeof = 32
  let gpu_uuid = (0, 0x10)
  let rm_ctrl_fd = (0x10, 4)
  let h_client = (0x14, 4)
  let h_va_space = (0x18, 4)
  let rm_status = (0x1c, 4)
end

module Uvm_unregister_gpu = struct
  let sizeof = 20
  let gpu_uuid = (0, 0x10)
  let rm_status = (0x10, 4)
end

module Uvm_unregister_gpu_vaspace = struct
  let sizeof = 20
  let gpu_uuid = (0, 0x10)
  let rm_status = (0x10, 4)
end

module Uvm_enable_peer_access = struct
  let sizeof = 36
  let gpu_uuid_a = (0, 0x10)
  let gpu_uuid_b = (0x10, 0x10)
  let rm_status = (0x20, 4)
end

module Uvm_register_channel = struct
  let sizeof = 56
  let gpu_uuid = (0, 0x10)
  let rm_ctrl_fd = (0x10, 4)
  let h_client = (0x14, 4)
  let h_channel = (0x18, 4)
  let base = (0x20, 8)
  let length = (0x28, 8)
  let rm_status = (0x30, 4)
end

module Uvm_create_external_range = struct
  let sizeof = 24
  let base = (0, 8)
  let length = (8, 8)
  let rm_status = (0x10, 4)
end

module Uvm_map_external_allocation = struct
  let sizeof = 9264
  let base = (0, 8)
  let length = (8, 8)
  let offset = (0x10, 8)
  let per_gpu_attributes = (0x18, 0x24, 0x100)
  let gpu_attributes_count = (0x2418, 8)
  let rm_ctrl_fd = (0x2420, 4)
  let h_client = (0x2424, 4)
  let h_memory = (0x2428, 4)
  let rm_status = (0x242c, 4)
end

module Uvm_gpu_mapping = struct
  let sizeof = 36
  let gpu_uuid = (0, 0x10)
  let gpu_mapping_type = (0x10, 4)
end

module Uvm_unmap_external = struct
  let sizeof = 40
  let base = (0, 8)
  let length = (8, 8)
  let gpu_uuid = (0x10, 0x10)
  let rm_status = (0x20, 4)
end

(* What differs between the releases. *)
module type RELEASE = sig
  module Fb_get_info : sig
    val sizeof : int
    val fb_info_list_size : int * int
    val fb_info_list : int * int * int
  end

  module Nvos46 : sig
    val sizeof : int
    val h_client : int * int
    val h_device : int * int
    val h_dma : int * int
    val h_memory : int * int
    val offset : int * int
    val length : int * int
    val flags : int * int
    val dma_offset : int * int
    val status : int * int
  end

  module Vaspace_alloc : sig
    val sizeof : int
    val index : int * int
    val flags : int * int
    val va_size : int * int
    val va_base : int * int
  end

  module Uvm_free : sig
    val sizeof : int
    val base : int * int
    val length : (int * int) option
    val rm_status : int * int
  end

  module Uvm_unregister_channel : sig
    val sizeof : int
    val gpu_uuid : (int * int) option
    val h_client : int * int
    val h_channel : int * int
    val rm_status : int * int
  end

  (* nvstatuscodes.h's statuses: (value, name). *)
  val statuses : (int * string) list
end

module R570 : RELEASE = struct
  module Fb_get_info = struct
    let sizeof = 460
    let fb_info_list_size = (0, 4)
    let fb_info_list = (4, 8, 0x39)
  end

  module Nvos46 = struct
    let sizeof = 56
    let h_client = (0, 4)
    let h_device = (4, 4)
    let h_dma = (8, 4)
    let h_memory = (0xc, 4)
    let offset = (0x10, 8)
    let length = (0x18, 8)
    let flags = (0x20, 4)
    let dma_offset = (0x28, 8)
    let status = (0x30, 4)
  end

  module Vaspace_alloc = struct
    let sizeof = 48
    let index = (0, 4)
    let flags = (4, 4)
    let va_size = (8, 8)
    let va_base = (0x28, 8)
  end

  module Uvm_free = struct
    let sizeof = 24
    let base = (0, 8)
    let length = Some (8, 8)
    let rm_status = (0x10, 4)
  end

  module Uvm_unregister_channel = struct
    let sizeof = 28
    let gpu_uuid = Some (0, 0x10)
    let h_client = (0x10, 4)
    let h_channel = (0x14, 4)
    let rm_status = (0x18, 4)
  end

  let statuses = [
    (0, "NV_OK");
    (0xffff, "NV_ERR_GENERIC");
    (1, "NV_ERR_BROKEN_FB");
    (2, "NV_ERR_BUFFER_TOO_SMALL");
    (3, "NV_ERR_BUSY_RETRY");
    (4, "NV_ERR_CALLBACK_NOT_SCHEDULED");
    (5, "NV_ERR_CARD_NOT_PRESENT");
    (6, "NV_ERR_CYCLE_DETECTED");
    (7, "NV_ERR_DMA_IN_USE");
    (8, "NV_ERR_DMA_MEM_NOT_LOCKED");
    (9, "NV_ERR_DMA_MEM_NOT_UNLOCKED");
    (0xa, "NV_ERR_DUAL_LINK_INUSE");
    (0xb, "NV_ERR_ECC_ERROR");
    (0xc, "NV_ERR_FIFO_BAD_ACCESS");
    (0xd, "NV_ERR_FREQ_NOT_SUPPORTED");
    (0xe, "NV_ERR_GPU_DMA_NOT_INITIALIZED");
    (0xf, "NV_ERR_GPU_IS_LOST");
    (0x10, "NV_ERR_GPU_IN_FULLCHIP_RESET");
    (0x11, "NV_ERR_GPU_NOT_FULL_POWER");
    (0x12, "NV_ERR_GPU_UUID_NOT_FOUND");
    (0x13, "NV_ERR_HOT_SWITCH");
    (0x14, "NV_ERR_I2C_ERROR");
    (0x15, "NV_ERR_I2C_SPEED_TOO_HIGH");
    (0x16, "NV_ERR_ILLEGAL_ACTION");
    (0x17, "NV_ERR_IN_USE");
    (0x18, "NV_ERR_INFLATE_COMPRESSED_DATA_FAILED");
    (0x19, "NV_ERR_INSERT_DUPLICATE_NAME");
    (0x1a, "NV_ERR_INSUFFICIENT_RESOURCES");
    (0x1b, "NV_ERR_INSUFFICIENT_PERMISSIONS");
    (0x1c, "NV_ERR_INSUFFICIENT_POWER");
    (0x1d, "NV_ERR_INVALID_ACCESS_TYPE");
    (0x1e, "NV_ERR_INVALID_ADDRESS");
    (0x1f, "NV_ERR_INVALID_ARGUMENT");
    (0x20, "NV_ERR_INVALID_BASE");
    (0x21, "NV_ERR_INVALID_CHANNEL");
    (0x22, "NV_ERR_INVALID_CLASS");
    (0x23, "NV_ERR_INVALID_CLIENT");
    (0x24, "NV_ERR_INVALID_COMMAND");
    (0x25, "NV_ERR_INVALID_DATA");
    (0x26, "NV_ERR_INVALID_DEVICE");
    (0x27, "NV_ERR_INVALID_DMA_SPECIFIER");
    (0x28, "NV_ERR_INVALID_EVENT");
    (0x29, "NV_ERR_INVALID_FLAGS");
    (0x2a, "NV_ERR_INVALID_FUNCTION");
    (0x2b, "NV_ERR_INVALID_HEAP");
    (0x2c, "NV_ERR_INVALID_INDEX");
    (0x2d, "NV_ERR_INVALID_IRQ_LEVEL");
    (0x2e, "NV_ERR_INVALID_LIMIT");
    (0x2f, "NV_ERR_INVALID_LOCK_STATE");
    (0x30, "NV_ERR_INVALID_METHOD");
    (0x31, "NV_ERR_INVALID_OBJECT");
    (0x32, "NV_ERR_INVALID_OBJECT_BUFFER");
    (0x33, "NV_ERR_INVALID_OBJECT_HANDLE");
    (0x34, "NV_ERR_INVALID_OBJECT_NEW");
    (0x35, "NV_ERR_INVALID_OBJECT_OLD");
    (0x36, "NV_ERR_INVALID_OBJECT_PARENT");
    (0x37, "NV_ERR_INVALID_OFFSET");
    (0x38, "NV_ERR_INVALID_OPERATION");
    (0x39, "NV_ERR_INVALID_OWNER");
    (0x3a, "NV_ERR_INVALID_PARAM_STRUCT");
    (0x3b, "NV_ERR_INVALID_PARAMETER");
    (0x3c, "NV_ERR_INVALID_PATH");
    (0x3d, "NV_ERR_INVALID_POINTER");
    (0x3e, "NV_ERR_INVALID_REGISTRY_KEY");
    (0x3f, "NV_ERR_INVALID_REQUEST");
    (0x40, "NV_ERR_INVALID_STATE");
    (0x41, "NV_ERR_INVALID_STRING_LENGTH");
    (0x42, "NV_ERR_INVALID_READ");
    (0x43, "NV_ERR_INVALID_WRITE");
    (0x44, "NV_ERR_INVALID_XLATE");
    (0x45, "NV_ERR_IRQ_NOT_FIRING");
    (0x46, "NV_ERR_IRQ_EDGE_TRIGGERED");
    (0x47, "NV_ERR_MEMORY_TRAINING_FAILED");
    (0x48, "NV_ERR_MISMATCHED_SLAVE");
    (0x49, "NV_ERR_MISMATCHED_TARGET");
    (0x4a, "NV_ERR_MISSING_TABLE_ENTRY");
    (0x4b, "NV_ERR_MODULE_LOAD_FAILED");
    (0x4c, "NV_ERR_MORE_DATA_AVAILABLE");
    (0x4d, "NV_ERR_MORE_PROCESSING_REQUIRED");
    (0x4e, "NV_ERR_MULTIPLE_MEMORY_TYPES");
    (0x4f, "NV_ERR_NO_FREE_FIFOS");
    (0x50, "NV_ERR_NO_INTR_PENDING");
    (0x51, "NV_ERR_NO_MEMORY");
    (0x52, "NV_ERR_NO_SUCH_DOMAIN");
    (0x53, "NV_ERR_NO_VALID_PATH");
    (0x54, "NV_ERR_NOT_COMPATIBLE");
    (0x55, "NV_ERR_NOT_READY");
    (0x56, "NV_ERR_NOT_SUPPORTED");
    (0x57, "NV_ERR_OBJECT_NOT_FOUND");
    (0x58, "NV_ERR_OBJECT_TYPE_MISMATCH");
    (0x59, "NV_ERR_OPERATING_SYSTEM");
    (0x5a, "NV_ERR_OTHER_DEVICE_FOUND");
    (0x5b, "NV_ERR_OUT_OF_RANGE");
    (0x5c, "NV_ERR_OVERLAPPING_UVM_COMMIT");
    (0x5d, "NV_ERR_PAGE_TABLE_NOT_AVAIL");
    (0x5e, "NV_ERR_PID_NOT_FOUND");
    (0x5f, "NV_ERR_PROTECTION_FAULT");
    (0x60, "NV_ERR_RC_ERROR");
    (0x61, "NV_ERR_REJECTED_VBIOS");
    (0x62, "NV_ERR_RESET_REQUIRED");
    (0x63, "NV_ERR_STATE_IN_USE");
    (0x64, "NV_ERR_SIGNAL_PENDING");
    (0x65, "NV_ERR_TIMEOUT");
    (0x66, "NV_ERR_TIMEOUT_RETRY");
    (0x67, "NV_ERR_TOO_MANY_PRIMARIES");
    (0x68, "NV_ERR_UVM_ADDRESS_IN_USE");
    (0x69, "NV_ERR_MAX_SESSION_LIMIT_REACHED");
    (0x6a, "NV_ERR_LIB_RM_VERSION_MISMATCH");
    (0x6b, "NV_ERR_PRIV_SEC_VIOLATION");
    (0x6c, "NV_ERR_GPU_IN_DEBUG_MODE");
    (0x6d, "NV_ERR_FEATURE_NOT_ENABLED");
    (0x6e, "NV_ERR_RESOURCE_LOST");
    (0x6f, "NV_ERR_PMU_NOT_READY");
    (0x70, "NV_ERR_FLCN_ERROR");
    (0x71, "NV_ERR_FATAL_ERROR");
    (0x72, "NV_ERR_MEMORY_ERROR");
    (0x73, "NV_ERR_INVALID_LICENSE");
    (0x74, "NV_ERR_NVLINK_INIT_ERROR");
    (0x75, "NV_ERR_NVLINK_MINION_ERROR");
    (0x76, "NV_ERR_NVLINK_CLOCK_ERROR");
    (0x77, "NV_ERR_NVLINK_TRAINING_ERROR");
    (0x78, "NV_ERR_NVLINK_CONFIGURATION_ERROR");
    (0x79, "NV_ERR_RISCV_ERROR");
    (0x7a, "NV_ERR_FABRIC_MANAGER_NOT_PRESENT");
    (0x7b, "NV_ERR_ALREADY_SIGNALLED");
    (0x7c, "NV_ERR_QUEUE_TASK_SLOT_NOT_AVAILABLE");
    (0x7d, "NV_ERR_KEY_ROTATION_IN_PROGRESS");
    (0x7e, "NV_ERR_TEST_ONLY_CODE_NOT_ENABLED");
    (0x7f, "NV_ERR_SECURE_BOOT_FAILED");
    (0x80, "NV_ERR_INSUFFICIENT_ZBC_ENTRY");
    (0x81, "NV_ERR_NVLINK_FABRIC_NOT_READY");
    (0x82, "NV_ERR_NVLINK_FABRIC_FAILURE");
    (0x83, "NV_ERR_GPU_MEMORY_ONLINING_FAILURE");
    (0x84, "NV_ERR_REDUCTION_MANAGER_NOT_AVAILABLE");
    (0x86, "NV_ERR_RESOURCE_RETIREMENT_ERROR");
    (0x10001, "NV_WARN_HOT_SWITCH");
    (0x10002, "NV_WARN_INCORRECT_PERFMON_DATA");
    (0x10003, "NV_WARN_MISMATCHED_SLAVE");
    (0x10004, "NV_WARN_MISMATCHED_TARGET");
    (0x10005, "NV_WARN_MORE_PROCESSING_REQUIRED");
    (0x10006, "NV_WARN_NOTHING_TO_DO");
    (0x10007, "NV_WARN_NULL_OBJECT");
    (0x10008, "NV_WARN_OUT_OF_RANGE");
  ]
end

module R580 : RELEASE = struct
  module Fb_get_info = struct
    let sizeof = 1028
    let fb_info_list_size = (0, 4)
    let fb_info_list = (4, 8, 0x80)
  end

  module Nvos46 = struct
    let sizeof = 64
    let h_client = (0, 4)
    let h_device = (4, 4)
    let h_dma = (8, 4)
    let h_memory = (0xc, 4)
    let offset = (0x10, 8)
    let length = (0x18, 8)
    let flags = (0x20, 4)
    let dma_offset = (0x30, 8)
    let status = (0x38, 4)
  end

  module Vaspace_alloc = struct
    let sizeof = 56
    let index = (0, 4)
    let flags = (4, 4)
    let va_size = (8, 8)
    let va_base = (0x28, 8)
  end

  module Uvm_free = struct
    let sizeof = 24
    let base = (0, 8)
    let length = Some (8, 8)
    let rm_status = (0x10, 4)
  end

  module Uvm_unregister_channel = struct
    let sizeof = 28
    let gpu_uuid = Some (0, 0x10)
    let h_client = (0x10, 4)
    let h_channel = (0x14, 4)
    let rm_status = (0x18, 4)
  end

  let statuses = [
    (0, "NV_OK");
    (0xffff, "NV_ERR_GENERIC");
    (1, "NV_ERR_BROKEN_FB");
    (2, "NV_ERR_BUFFER_TOO_SMALL");
    (3, "NV_ERR_BUSY_RETRY");
    (4, "NV_ERR_CALLBACK_NOT_SCHEDULED");
    (5, "NV_ERR_CARD_NOT_PRESENT");
    (6, "NV_ERR_CYCLE_DETECTED");
    (7, "NV_ERR_DMA_IN_USE");
    (8, "NV_ERR_DMA_MEM_NOT_LOCKED");
    (9, "NV_ERR_DMA_MEM_NOT_UNLOCKED");
    (0xa, "NV_ERR_DUAL_LINK_INUSE");
    (0xb, "NV_ERR_ECC_ERROR");
    (0xc, "NV_ERR_FIFO_BAD_ACCESS");
    (0xd, "NV_ERR_FREQ_NOT_SUPPORTED");
    (0xe, "NV_ERR_GPU_DMA_NOT_INITIALIZED");
    (0xf, "NV_ERR_GPU_IS_LOST");
    (0x10, "NV_ERR_GPU_IN_FULLCHIP_RESET");
    (0x11, "NV_ERR_GPU_NOT_FULL_POWER");
    (0x12, "NV_ERR_GPU_UUID_NOT_FOUND");
    (0x13, "NV_ERR_HOT_SWITCH");
    (0x14, "NV_ERR_I2C_ERROR");
    (0x15, "NV_ERR_I2C_SPEED_TOO_HIGH");
    (0x16, "NV_ERR_ILLEGAL_ACTION");
    (0x17, "NV_ERR_IN_USE");
    (0x18, "NV_ERR_INFLATE_COMPRESSED_DATA_FAILED");
    (0x19, "NV_ERR_INSERT_DUPLICATE_NAME");
    (0x1a, "NV_ERR_INSUFFICIENT_RESOURCES");
    (0x1b, "NV_ERR_INSUFFICIENT_PERMISSIONS");
    (0x1c, "NV_ERR_INSUFFICIENT_POWER");
    (0x1d, "NV_ERR_INVALID_ACCESS_TYPE");
    (0x1e, "NV_ERR_INVALID_ADDRESS");
    (0x1f, "NV_ERR_INVALID_ARGUMENT");
    (0x20, "NV_ERR_INVALID_BASE");
    (0x21, "NV_ERR_INVALID_CHANNEL");
    (0x22, "NV_ERR_INVALID_CLASS");
    (0x23, "NV_ERR_INVALID_CLIENT");
    (0x24, "NV_ERR_INVALID_COMMAND");
    (0x25, "NV_ERR_INVALID_DATA");
    (0x26, "NV_ERR_INVALID_DEVICE");
    (0x27, "NV_ERR_INVALID_DMA_SPECIFIER");
    (0x28, "NV_ERR_INVALID_EVENT");
    (0x29, "NV_ERR_INVALID_FLAGS");
    (0x2a, "NV_ERR_INVALID_FUNCTION");
    (0x2b, "NV_ERR_INVALID_HEAP");
    (0x2c, "NV_ERR_INVALID_INDEX");
    (0x2d, "NV_ERR_INVALID_IRQ_LEVEL");
    (0x2e, "NV_ERR_INVALID_LIMIT");
    (0x2f, "NV_ERR_INVALID_LOCK_STATE");
    (0x30, "NV_ERR_INVALID_METHOD");
    (0x31, "NV_ERR_INVALID_OBJECT");
    (0x32, "NV_ERR_INVALID_OBJECT_BUFFER");
    (0x33, "NV_ERR_INVALID_OBJECT_HANDLE");
    (0x34, "NV_ERR_INVALID_OBJECT_NEW");
    (0x35, "NV_ERR_INVALID_OBJECT_OLD");
    (0x36, "NV_ERR_INVALID_OBJECT_PARENT");
    (0x37, "NV_ERR_INVALID_OFFSET");
    (0x38, "NV_ERR_INVALID_OPERATION");
    (0x39, "NV_ERR_INVALID_OWNER");
    (0x3a, "NV_ERR_INVALID_PARAM_STRUCT");
    (0x3b, "NV_ERR_INVALID_PARAMETER");
    (0x3c, "NV_ERR_INVALID_PATH");
    (0x3d, "NV_ERR_INVALID_POINTER");
    (0x3e, "NV_ERR_INVALID_REGISTRY_KEY");
    (0x3f, "NV_ERR_INVALID_REQUEST");
    (0x40, "NV_ERR_INVALID_STATE");
    (0x41, "NV_ERR_INVALID_STRING_LENGTH");
    (0x42, "NV_ERR_INVALID_READ");
    (0x43, "NV_ERR_INVALID_WRITE");
    (0x44, "NV_ERR_INVALID_XLATE");
    (0x45, "NV_ERR_IRQ_NOT_FIRING");
    (0x46, "NV_ERR_IRQ_EDGE_TRIGGERED");
    (0x47, "NV_ERR_MEMORY_TRAINING_FAILED");
    (0x48, "NV_ERR_MISMATCHED_SLAVE");
    (0x49, "NV_ERR_MISMATCHED_TARGET");
    (0x4a, "NV_ERR_MISSING_TABLE_ENTRY");
    (0x4b, "NV_ERR_MODULE_LOAD_FAILED");
    (0x4c, "NV_ERR_MORE_DATA_AVAILABLE");
    (0x4d, "NV_ERR_MORE_PROCESSING_REQUIRED");
    (0x4e, "NV_ERR_MULTIPLE_MEMORY_TYPES");
    (0x4f, "NV_ERR_NO_FREE_FIFOS");
    (0x50, "NV_ERR_NO_INTR_PENDING");
    (0x51, "NV_ERR_NO_MEMORY");
    (0x52, "NV_ERR_NO_SUCH_DOMAIN");
    (0x53, "NV_ERR_NO_VALID_PATH");
    (0x54, "NV_ERR_NOT_COMPATIBLE");
    (0x55, "NV_ERR_NOT_READY");
    (0x56, "NV_ERR_NOT_SUPPORTED");
    (0x57, "NV_ERR_OBJECT_NOT_FOUND");
    (0x58, "NV_ERR_OBJECT_TYPE_MISMATCH");
    (0x59, "NV_ERR_OPERATING_SYSTEM");
    (0x5a, "NV_ERR_OTHER_DEVICE_FOUND");
    (0x5b, "NV_ERR_OUT_OF_RANGE");
    (0x5c, "NV_ERR_OVERLAPPING_UVM_COMMIT");
    (0x5d, "NV_ERR_PAGE_TABLE_NOT_AVAIL");
    (0x5e, "NV_ERR_PID_NOT_FOUND");
    (0x5f, "NV_ERR_PROTECTION_FAULT");
    (0x60, "NV_ERR_RC_ERROR");
    (0x61, "NV_ERR_REJECTED_VBIOS");
    (0x62, "NV_ERR_RESET_REQUIRED");
    (0x63, "NV_ERR_STATE_IN_USE");
    (0x64, "NV_ERR_SIGNAL_PENDING");
    (0x65, "NV_ERR_TIMEOUT");
    (0x66, "NV_ERR_TIMEOUT_RETRY");
    (0x67, "NV_ERR_TOO_MANY_PRIMARIES");
    (0x68, "NV_ERR_UVM_ADDRESS_IN_USE");
    (0x69, "NV_ERR_MAX_SESSION_LIMIT_REACHED");
    (0x6a, "NV_ERR_LIB_RM_VERSION_MISMATCH");
    (0x6b, "NV_ERR_PRIV_SEC_VIOLATION");
    (0x6c, "NV_ERR_GPU_IN_DEBUG_MODE");
    (0x6d, "NV_ERR_FEATURE_NOT_ENABLED");
    (0x6e, "NV_ERR_RESOURCE_LOST");
    (0x6f, "NV_ERR_PMU_NOT_READY");
    (0x70, "NV_ERR_FLCN_ERROR");
    (0x71, "NV_ERR_FATAL_ERROR");
    (0x72, "NV_ERR_MEMORY_ERROR");
    (0x73, "NV_ERR_INVALID_LICENSE");
    (0x74, "NV_ERR_NVLINK_INIT_ERROR");
    (0x75, "NV_ERR_NVLINK_MINION_ERROR");
    (0x76, "NV_ERR_NVLINK_CLOCK_ERROR");
    (0x77, "NV_ERR_NVLINK_TRAINING_ERROR");
    (0x78, "NV_ERR_NVLINK_CONFIGURATION_ERROR");
    (0x79, "NV_ERR_RISCV_ERROR");
    (0x7a, "NV_ERR_FABRIC_MANAGER_NOT_PRESENT");
    (0x7b, "NV_ERR_ALREADY_SIGNALLED");
    (0x7c, "NV_ERR_QUEUE_TASK_SLOT_NOT_AVAILABLE");
    (0x7d, "NV_ERR_KEY_ROTATION_IN_PROGRESS");
    (0x7e, "NV_ERR_TEST_ONLY_CODE_NOT_ENABLED");
    (0x7f, "NV_ERR_SECURE_BOOT_FAILED");
    (0x80, "NV_ERR_INSUFFICIENT_ZBC_ENTRY");
    (0x81, "NV_ERR_NVLINK_FABRIC_NOT_READY");
    (0x82, "NV_ERR_NVLINK_FABRIC_FAILURE");
    (0x83, "NV_ERR_GPU_MEMORY_ONLINING_FAILURE");
    (0x84, "NV_ERR_REDUCTION_MANAGER_NOT_AVAILABLE");
    (0x85, "NV_ERR_THRESHOLD_CROSSED");
    (0x86, "NV_ERR_RESOURCE_RETIREMENT_ERROR");
    (0x87, "NV_ERR_FABRIC_STATE_OUT_OF_SYNC");
    (0x88, "NV_ERR_BUFFER_FULL");
    (0x89, "NV_ERR_BUFFER_EMPTY");
    (0x8a, "NV_ERR_MC_FLA_OFFSET_TABLE_FULL");
    (0x8b, "NV_ERR_DMA_XFER_FAILED");
    (0x10001, "NV_WARN_HOT_SWITCH");
    (0x10002, "NV_WARN_INCORRECT_PERFMON_DATA");
    (0x10003, "NV_WARN_MISMATCHED_SLAVE");
    (0x10004, "NV_WARN_MISMATCHED_TARGET");
    (0x10005, "NV_WARN_MORE_PROCESSING_REQUIRED");
    (0x10006, "NV_WARN_NOTHING_TO_DO");
    (0x10007, "NV_WARN_NULL_OBJECT");
    (0x10008, "NV_WARN_OUT_OF_RANGE");
    (0x10009, "NV_WARN_THRESHOLD_CROSSED");
  ]
end

module R610 : RELEASE = struct
  module Fb_get_info = struct
    let sizeof = 1028
    let fb_info_list_size = (0, 4)
    let fb_info_list = (4, 8, 0x80)
  end

  module Nvos46 = struct
    let sizeof = 64
    let h_client = (0, 4)
    let h_device = (4, 4)
    let h_dma = (8, 4)
    let h_memory = (0xc, 4)
    let offset = (0x10, 8)
    let length = (0x18, 8)
    let flags = (0x20, 4)
    let dma_offset = (0x30, 8)
    let status = (0x38, 4)
  end

  module Vaspace_alloc = struct
    let sizeof = 56
    let index = (0, 4)
    let flags = (4, 4)
    let va_size = (8, 8)
    let va_base = (0x28, 8)
  end

  module Uvm_free = struct
    let sizeof = 16
    let base = (0, 8)
    let length = None
    let rm_status = (8, 4)
  end

  module Uvm_unregister_channel = struct
    let sizeof = 12
    let gpu_uuid = None
    let h_client = (0, 4)
    let h_channel = (4, 4)
    let rm_status = (8, 4)
  end

  let statuses = [
    (0, "NV_OK");
    (0xffff, "NV_ERR_GENERIC");
    (1, "NV_ERR_BROKEN_FB");
    (2, "NV_ERR_BUFFER_TOO_SMALL");
    (3, "NV_ERR_BUSY_RETRY");
    (4, "NV_ERR_CALLBACK_NOT_SCHEDULED");
    (5, "NV_ERR_CARD_NOT_PRESENT");
    (6, "NV_ERR_CYCLE_DETECTED");
    (7, "NV_ERR_DMA_IN_USE");
    (8, "NV_ERR_DMA_MEM_NOT_LOCKED");
    (9, "NV_ERR_DMA_MEM_NOT_UNLOCKED");
    (0xa, "NV_ERR_DUAL_LINK_INUSE");
    (0xb, "NV_ERR_ECC_ERROR");
    (0xc, "NV_ERR_FIFO_BAD_ACCESS");
    (0xd, "NV_ERR_FREQ_NOT_SUPPORTED");
    (0xe, "NV_ERR_GPU_DMA_NOT_INITIALIZED");
    (0xf, "NV_ERR_GPU_IS_LOST");
    (0x10, "NV_ERR_GPU_IN_FULLCHIP_RESET");
    (0x11, "NV_ERR_GPU_NOT_FULL_POWER");
    (0x12, "NV_ERR_GPU_UUID_NOT_FOUND");
    (0x13, "NV_ERR_HOT_SWITCH");
    (0x14, "NV_ERR_I2C_ERROR");
    (0x15, "NV_ERR_I2C_SPEED_TOO_HIGH");
    (0x16, "NV_ERR_ILLEGAL_ACTION");
    (0x17, "NV_ERR_IN_USE");
    (0x18, "NV_ERR_INFLATE_COMPRESSED_DATA_FAILED");
    (0x19, "NV_ERR_INSERT_DUPLICATE_NAME");
    (0x1a, "NV_ERR_INSUFFICIENT_RESOURCES");
    (0x1b, "NV_ERR_INSUFFICIENT_PERMISSIONS");
    (0x1c, "NV_ERR_INSUFFICIENT_POWER");
    (0x1d, "NV_ERR_INVALID_ACCESS_TYPE");
    (0x1e, "NV_ERR_INVALID_ADDRESS");
    (0x1f, "NV_ERR_INVALID_ARGUMENT");
    (0x20, "NV_ERR_INVALID_BASE");
    (0x21, "NV_ERR_INVALID_CHANNEL");
    (0x22, "NV_ERR_INVALID_CLASS");
    (0x23, "NV_ERR_INVALID_CLIENT");
    (0x24, "NV_ERR_INVALID_COMMAND");
    (0x25, "NV_ERR_INVALID_DATA");
    (0x26, "NV_ERR_INVALID_DEVICE");
    (0x27, "NV_ERR_INVALID_DMA_SPECIFIER");
    (0x28, "NV_ERR_INVALID_EVENT");
    (0x29, "NV_ERR_INVALID_FLAGS");
    (0x2a, "NV_ERR_INVALID_FUNCTION");
    (0x2b, "NV_ERR_INVALID_HEAP");
    (0x2c, "NV_ERR_INVALID_INDEX");
    (0x2d, "NV_ERR_INVALID_IRQ_LEVEL");
    (0x2e, "NV_ERR_INVALID_LIMIT");
    (0x2f, "NV_ERR_INVALID_LOCK_STATE");
    (0x30, "NV_ERR_INVALID_METHOD");
    (0x31, "NV_ERR_INVALID_OBJECT");
    (0x32, "NV_ERR_INVALID_OBJECT_BUFFER");
    (0x33, "NV_ERR_INVALID_OBJECT_HANDLE");
    (0x34, "NV_ERR_INVALID_OBJECT_NEW");
    (0x35, "NV_ERR_INVALID_OBJECT_OLD");
    (0x36, "NV_ERR_INVALID_OBJECT_PARENT");
    (0x37, "NV_ERR_INVALID_OFFSET");
    (0x38, "NV_ERR_INVALID_OPERATION");
    (0x39, "NV_ERR_INVALID_OWNER");
    (0x3a, "NV_ERR_INVALID_PARAM_STRUCT");
    (0x3b, "NV_ERR_INVALID_PARAMETER");
    (0x3c, "NV_ERR_INVALID_PATH");
    (0x3d, "NV_ERR_INVALID_POINTER");
    (0x3e, "NV_ERR_INVALID_REGISTRY_KEY");
    (0x3f, "NV_ERR_INVALID_REQUEST");
    (0x40, "NV_ERR_INVALID_STATE");
    (0x41, "NV_ERR_INVALID_STRING_LENGTH");
    (0x42, "NV_ERR_INVALID_READ");
    (0x43, "NV_ERR_INVALID_WRITE");
    (0x44, "NV_ERR_INVALID_XLATE");
    (0x45, "NV_ERR_IRQ_NOT_FIRING");
    (0x46, "NV_ERR_IRQ_EDGE_TRIGGERED");
    (0x47, "NV_ERR_MEMORY_TRAINING_FAILED");
    (0x48, "NV_ERR_MISMATCHED_SLAVE");
    (0x49, "NV_ERR_MISMATCHED_TARGET");
    (0x4a, "NV_ERR_MISSING_TABLE_ENTRY");
    (0x4b, "NV_ERR_MODULE_LOAD_FAILED");
    (0x4c, "NV_ERR_MORE_DATA_AVAILABLE");
    (0x4d, "NV_ERR_MORE_PROCESSING_REQUIRED");
    (0x4e, "NV_ERR_MULTIPLE_MEMORY_TYPES");
    (0x4f, "NV_ERR_NO_FREE_FIFOS");
    (0x50, "NV_ERR_NO_INTR_PENDING");
    (0x51, "NV_ERR_NO_MEMORY");
    (0x52, "NV_ERR_NO_SUCH_DOMAIN");
    (0x53, "NV_ERR_NO_VALID_PATH");
    (0x54, "NV_ERR_NOT_COMPATIBLE");
    (0x55, "NV_ERR_NOT_READY");
    (0x56, "NV_ERR_NOT_SUPPORTED");
    (0x57, "NV_ERR_OBJECT_NOT_FOUND");
    (0x58, "NV_ERR_OBJECT_TYPE_MISMATCH");
    (0x59, "NV_ERR_OPERATING_SYSTEM");
    (0x5a, "NV_ERR_OTHER_DEVICE_FOUND");
    (0x5b, "NV_ERR_OUT_OF_RANGE");
    (0x5c, "NV_ERR_OVERLAPPING_UVM_COMMIT");
    (0x5d, "NV_ERR_PAGE_TABLE_NOT_AVAIL");
    (0x5e, "NV_ERR_PID_NOT_FOUND");
    (0x5f, "NV_ERR_PROTECTION_FAULT");
    (0x60, "NV_ERR_RC_ERROR");
    (0x61, "NV_ERR_REJECTED_VBIOS");
    (0x62, "NV_ERR_RESET_REQUIRED");
    (0x63, "NV_ERR_STATE_IN_USE");
    (0x64, "NV_ERR_SIGNAL_PENDING");
    (0x65, "NV_ERR_TIMEOUT");
    (0x66, "NV_ERR_TIMEOUT_RETRY");
    (0x67, "NV_ERR_TOO_MANY_PRIMARIES");
    (0x68, "NV_ERR_UVM_ADDRESS_IN_USE");
    (0x69, "NV_ERR_MAX_SESSION_LIMIT_REACHED");
    (0x6a, "NV_ERR_LIB_RM_VERSION_MISMATCH");
    (0x6b, "NV_ERR_PRIV_SEC_VIOLATION");
    (0x6c, "NV_ERR_GPU_IN_DEBUG_MODE");
    (0x6d, "NV_ERR_FEATURE_NOT_ENABLED");
    (0x6e, "NV_ERR_RESOURCE_LOST");
    (0x6f, "NV_ERR_PMU_NOT_READY");
    (0x70, "NV_ERR_FLCN_ERROR");
    (0x71, "NV_ERR_FATAL_ERROR");
    (0x72, "NV_ERR_MEMORY_ERROR");
    (0x73, "NV_ERR_INVALID_LICENSE");
    (0x74, "NV_ERR_NVLINK_INIT_ERROR");
    (0x75, "NV_ERR_NVLINK_MINION_ERROR");
    (0x76, "NV_ERR_NVLINK_CLOCK_ERROR");
    (0x77, "NV_ERR_NVLINK_TRAINING_ERROR");
    (0x78, "NV_ERR_NVLINK_CONFIGURATION_ERROR");
    (0x79, "NV_ERR_RISCV_ERROR");
    (0x7a, "NV_ERR_FABRIC_MANAGER_NOT_PRESENT");
    (0x7b, "NV_ERR_ALREADY_SIGNALLED");
    (0x7c, "NV_ERR_QUEUE_TASK_SLOT_NOT_AVAILABLE");
    (0x7d, "NV_ERR_KEY_ROTATION_IN_PROGRESS");
    (0x7e, "NV_ERR_TEST_ONLY_CODE_NOT_ENABLED");
    (0x7f, "NV_ERR_SECURE_BOOT_FAILED");
    (0x80, "NV_ERR_INSUFFICIENT_ZBC_ENTRY");
    (0x81, "NV_ERR_NVLINK_FABRIC_NOT_READY");
    (0x82, "NV_ERR_NVLINK_FABRIC_FAILURE");
    (0x83, "NV_ERR_GPU_MEMORY_ONLINING_FAILURE");
    (0x84, "NV_ERR_REDUCTION_MANAGER_NOT_AVAILABLE");
    (0x85, "NV_ERR_THRESHOLD_CROSSED");
    (0x86, "NV_ERR_RESOURCE_RETIREMENT_ERROR");
    (0x87, "NV_ERR_FABRIC_STATE_OUT_OF_SYNC");
    (0x88, "NV_ERR_BUFFER_FULL");
    (0x89, "NV_ERR_BUFFER_EMPTY");
    (0x8a, "NV_ERR_MC_FLA_OFFSET_TABLE_FULL");
    (0x8b, "NV_ERR_OPERATION_ABORTED");
    (0x8c, "NV_ERR_DMA_XFER_FAILED");
    (0x8d, "NV_ERR_RESOURCE_ACCOUNTING_HARD_LIMIT_EXCEEDED");
    (0x10001, "NV_WARN_HOT_SWITCH");
    (0x10002, "NV_WARN_INCORRECT_PERFMON_DATA");
    (0x10003, "NV_WARN_MISMATCHED_SLAVE");
    (0x10004, "NV_WARN_MISMATCHED_TARGET");
    (0x10005, "NV_WARN_MORE_PROCESSING_REQUIRED");
    (0x10006, "NV_WARN_NOTHING_TO_DO");
    (0x10007, "NV_WARN_NULL_OBJECT");
    (0x10008, "NV_WARN_OUT_OF_RANGE");
    (0x10009, "NV_WARN_THRESHOLD_CROSSED");
    (0x1000a, "NV_WARN_RESOURCE_ACCOUNTING_SOFT_LIMIT_EXCEEDED");
  ]
end

module R615 : RELEASE = struct
  module Fb_get_info = struct
    let sizeof = 1028
    let fb_info_list_size = (0, 4)
    let fb_info_list = (4, 8, 0x80)
  end

  module Nvos46 = struct
    let sizeof = 64
    let h_client = (0, 4)
    let h_device = (4, 4)
    let h_dma = (8, 4)
    let h_memory = (0xc, 4)
    let offset = (0x10, 8)
    let length = (0x18, 8)
    let flags = (0x20, 4)
    let dma_offset = (0x30, 8)
    let status = (0x38, 4)
  end

  module Vaspace_alloc = struct
    let sizeof = 56
    let index = (0, 4)
    let flags = (4, 4)
    let va_size = (8, 8)
    let va_base = (0x28, 8)
  end

  module Uvm_free = struct
    let sizeof = 16
    let base = (0, 8)
    let length = None
    let rm_status = (8, 4)
  end

  module Uvm_unregister_channel = struct
    let sizeof = 12
    let gpu_uuid = None
    let h_client = (0, 4)
    let h_channel = (4, 4)
    let rm_status = (8, 4)
  end

  let statuses = [
    (0, "NV_OK");
    (0xffff, "NV_ERR_GENERIC");
    (1, "NV_ERR_BROKEN_FB");
    (2, "NV_ERR_BUFFER_TOO_SMALL");
    (3, "NV_ERR_BUSY_RETRY");
    (4, "NV_ERR_CALLBACK_NOT_SCHEDULED");
    (5, "NV_ERR_CARD_NOT_PRESENT");
    (6, "NV_ERR_CYCLE_DETECTED");
    (7, "NV_ERR_DMA_IN_USE");
    (8, "NV_ERR_DMA_MEM_NOT_LOCKED");
    (9, "NV_ERR_DMA_MEM_NOT_UNLOCKED");
    (0xa, "NV_ERR_DUAL_LINK_INUSE");
    (0xb, "NV_ERR_ECC_ERROR");
    (0xc, "NV_ERR_FIFO_BAD_ACCESS");
    (0xd, "NV_ERR_FREQ_NOT_SUPPORTED");
    (0xe, "NV_ERR_GPU_DMA_NOT_INITIALIZED");
    (0xf, "NV_ERR_GPU_IS_LOST");
    (0x10, "NV_ERR_GPU_IN_FULLCHIP_RESET");
    (0x11, "NV_ERR_GPU_NOT_FULL_POWER");
    (0x12, "NV_ERR_GPU_UUID_NOT_FOUND");
    (0x13, "NV_ERR_HOT_SWITCH");
    (0x14, "NV_ERR_I2C_ERROR");
    (0x15, "NV_ERR_I2C_SPEED_TOO_HIGH");
    (0x16, "NV_ERR_ILLEGAL_ACTION");
    (0x17, "NV_ERR_IN_USE");
    (0x18, "NV_ERR_INFLATE_COMPRESSED_DATA_FAILED");
    (0x19, "NV_ERR_INSERT_DUPLICATE_NAME");
    (0x1a, "NV_ERR_INSUFFICIENT_RESOURCES");
    (0x1b, "NV_ERR_INSUFFICIENT_PERMISSIONS");
    (0x1c, "NV_ERR_INSUFFICIENT_POWER");
    (0x1d, "NV_ERR_INVALID_ACCESS_TYPE");
    (0x1e, "NV_ERR_INVALID_ADDRESS");
    (0x1f, "NV_ERR_INVALID_ARGUMENT");
    (0x20, "NV_ERR_INVALID_BASE");
    (0x21, "NV_ERR_INVALID_CHANNEL");
    (0x22, "NV_ERR_INVALID_CLASS");
    (0x23, "NV_ERR_INVALID_CLIENT");
    (0x24, "NV_ERR_INVALID_COMMAND");
    (0x25, "NV_ERR_INVALID_DATA");
    (0x26, "NV_ERR_INVALID_DEVICE");
    (0x27, "NV_ERR_INVALID_DMA_SPECIFIER");
    (0x28, "NV_ERR_INVALID_EVENT");
    (0x29, "NV_ERR_INVALID_FLAGS");
    (0x2a, "NV_ERR_INVALID_FUNCTION");
    (0x2b, "NV_ERR_INVALID_HEAP");
    (0x2c, "NV_ERR_INVALID_INDEX");
    (0x2d, "NV_ERR_INVALID_IRQ_LEVEL");
    (0x2e, "NV_ERR_INVALID_LIMIT");
    (0x2f, "NV_ERR_INVALID_LOCK_STATE");
    (0x30, "NV_ERR_INVALID_METHOD");
    (0x31, "NV_ERR_INVALID_OBJECT");
    (0x32, "NV_ERR_INVALID_OBJECT_BUFFER");
    (0x33, "NV_ERR_INVALID_OBJECT_HANDLE");
    (0x34, "NV_ERR_INVALID_OBJECT_NEW");
    (0x35, "NV_ERR_INVALID_OBJECT_OLD");
    (0x36, "NV_ERR_INVALID_OBJECT_PARENT");
    (0x37, "NV_ERR_INVALID_OFFSET");
    (0x38, "NV_ERR_INVALID_OPERATION");
    (0x39, "NV_ERR_INVALID_OWNER");
    (0x3a, "NV_ERR_INVALID_PARAM_STRUCT");
    (0x3b, "NV_ERR_INVALID_PARAMETER");
    (0x3c, "NV_ERR_INVALID_PATH");
    (0x3d, "NV_ERR_INVALID_POINTER");
    (0x3e, "NV_ERR_INVALID_REGISTRY_KEY");
    (0x3f, "NV_ERR_INVALID_REQUEST");
    (0x40, "NV_ERR_INVALID_STATE");
    (0x41, "NV_ERR_INVALID_STRING_LENGTH");
    (0x42, "NV_ERR_INVALID_READ");
    (0x43, "NV_ERR_INVALID_WRITE");
    (0x44, "NV_ERR_INVALID_XLATE");
    (0x45, "NV_ERR_IRQ_NOT_FIRING");
    (0x46, "NV_ERR_IRQ_EDGE_TRIGGERED");
    (0x47, "NV_ERR_MEMORY_TRAINING_FAILED");
    (0x48, "NV_ERR_MISMATCHED_SLAVE");
    (0x49, "NV_ERR_MISMATCHED_TARGET");
    (0x4a, "NV_ERR_MISSING_TABLE_ENTRY");
    (0x4b, "NV_ERR_MODULE_LOAD_FAILED");
    (0x4c, "NV_ERR_MORE_DATA_AVAILABLE");
    (0x4d, "NV_ERR_MORE_PROCESSING_REQUIRED");
    (0x4e, "NV_ERR_MULTIPLE_MEMORY_TYPES");
    (0x4f, "NV_ERR_NO_FREE_FIFOS");
    (0x50, "NV_ERR_NO_INTR_PENDING");
    (0x51, "NV_ERR_NO_MEMORY");
    (0x52, "NV_ERR_NO_SUCH_DOMAIN");
    (0x53, "NV_ERR_NO_VALID_PATH");
    (0x54, "NV_ERR_NOT_COMPATIBLE");
    (0x55, "NV_ERR_NOT_READY");
    (0x56, "NV_ERR_NOT_SUPPORTED");
    (0x57, "NV_ERR_OBJECT_NOT_FOUND");
    (0x58, "NV_ERR_OBJECT_TYPE_MISMATCH");
    (0x59, "NV_ERR_OPERATING_SYSTEM");
    (0x5a, "NV_ERR_OTHER_DEVICE_FOUND");
    (0x5b, "NV_ERR_OUT_OF_RANGE");
    (0x5c, "NV_ERR_OVERLAPPING_UVM_COMMIT");
    (0x5d, "NV_ERR_PAGE_TABLE_NOT_AVAIL");
    (0x5e, "NV_ERR_PID_NOT_FOUND");
    (0x5f, "NV_ERR_PROTECTION_FAULT");
    (0x60, "NV_ERR_RC_ERROR");
    (0x61, "NV_ERR_REJECTED_VBIOS");
    (0x62, "NV_ERR_RESET_REQUIRED");
    (0x63, "NV_ERR_STATE_IN_USE");
    (0x64, "NV_ERR_SIGNAL_PENDING");
    (0x65, "NV_ERR_TIMEOUT");
    (0x66, "NV_ERR_TIMEOUT_RETRY");
    (0x67, "NV_ERR_TOO_MANY_PRIMARIES");
    (0x68, "NV_ERR_UVM_ADDRESS_IN_USE");
    (0x69, "NV_ERR_MAX_SESSION_LIMIT_REACHED");
    (0x6a, "NV_ERR_LIB_RM_VERSION_MISMATCH");
    (0x6b, "NV_ERR_PRIV_SEC_VIOLATION");
    (0x6c, "NV_ERR_GPU_IN_DEBUG_MODE");
    (0x6d, "NV_ERR_FEATURE_NOT_ENABLED");
    (0x6e, "NV_ERR_RESOURCE_LOST");
    (0x6f, "NV_ERR_PMU_NOT_READY");
    (0x70, "NV_ERR_FLCN_ERROR");
    (0x71, "NV_ERR_FATAL_ERROR");
    (0x72, "NV_ERR_MEMORY_ERROR");
    (0x73, "NV_ERR_INVALID_LICENSE");
    (0x74, "NV_ERR_NVLINK_INIT_ERROR");
    (0x75, "NV_ERR_NVLINK_MINION_ERROR");
    (0x76, "NV_ERR_NVLINK_CLOCK_ERROR");
    (0x77, "NV_ERR_NVLINK_TRAINING_ERROR");
    (0x78, "NV_ERR_NVLINK_CONFIGURATION_ERROR");
    (0x79, "NV_ERR_RISCV_ERROR");
    (0x7a, "NV_ERR_FABRIC_MANAGER_NOT_PRESENT");
    (0x7b, "NV_ERR_ALREADY_SIGNALLED");
    (0x7c, "NV_ERR_QUEUE_TASK_SLOT_NOT_AVAILABLE");
    (0x7d, "NV_ERR_KEY_ROTATION_IN_PROGRESS");
    (0x7e, "NV_ERR_TEST_ONLY_CODE_NOT_ENABLED");
    (0x7f, "NV_ERR_SECURE_BOOT_FAILED");
    (0x80, "NV_ERR_INSUFFICIENT_ZBC_ENTRY");
    (0x81, "NV_ERR_NVLINK_FABRIC_NOT_READY");
    (0x82, "NV_ERR_NVLINK_FABRIC_FAILURE");
    (0x83, "NV_ERR_GPU_MEMORY_ONLINING_FAILURE");
    (0x84, "NV_ERR_REDUCTION_MANAGER_NOT_AVAILABLE");
    (0x85, "NV_ERR_THRESHOLD_CROSSED");
    (0x86, "NV_ERR_RESOURCE_RETIREMENT_ERROR");
    (0x87, "NV_ERR_FABRIC_STATE_OUT_OF_SYNC");
    (0x88, "NV_ERR_BUFFER_FULL");
    (0x89, "NV_ERR_BUFFER_EMPTY");
    (0x8a, "NV_ERR_MC_FLA_OFFSET_TABLE_FULL");
    (0x8b, "NV_ERR_OPERATION_ABORTED");
    (0x8c, "NV_ERR_DMA_XFER_FAILED");
    (0x8d, "NV_ERR_RESOURCE_ACCOUNTING_HARD_LIMIT_EXCEEDED");
    (0x8e, "NV_ERR_NVLINK_FW_NOT_LOADED");
    (0x8f, "NV_ERR_INTR_STUCK");
    (0x90, "NV_ERR_GMCAPI_INVALID_MCTP");
    (0x91, "NV_ERR_GMCAPI_INVALID_NVDM_TYPE");
    (0x92, "NV_ERR_GMCAPI_INVALID_COMMAND_ID");
    (0x93, "NV_ERR_GMCAPI_REQUEST_SIZE_TOO_LARGE");
    (0x94, "NV_ERR_GMCAPI_REQUEST_SIZE_TOO_SMALL");
    (0x95, "NV_ERR_GMCAPI_MAX_RESPONSE_SIZE_TOO_SMALL");
    (0x9e, "NV_ERR_GMCAPI_INTERNAL_RM_ERROR");
    (0x9f, "NV_ERR_GMCAPI_GENERIC_ERROR");
    (0x10001, "NV_WARN_HOT_SWITCH");
    (0x10002, "NV_WARN_INCORRECT_PERFMON_DATA");
    (0x10003, "NV_WARN_MISMATCHED_SLAVE");
    (0x10004, "NV_WARN_MISMATCHED_TARGET");
    (0x10005, "NV_WARN_MORE_PROCESSING_REQUIRED");
    (0x10006, "NV_WARN_NOTHING_TO_DO");
    (0x10007, "NV_WARN_NULL_OBJECT");
    (0x10008, "NV_WARN_OUT_OF_RANGE");
    (0x10009, "NV_WARN_THRESHOLD_CROSSED");
    (0x1000a, "NV_WARN_RESOURCE_ACCOUNTING_SOFT_LIMIT_EXCEEDED");
  ]
end

(* The layouts of release [r], if it is one of {!releases}. *)
let release = function
  | 570 -> Some (module R570 : RELEASE)
  | 580 -> Some (module R580 : RELEASE)
  | 610 -> Some (module R610 : RELEASE)
  | 615 -> Some (module R615 : RELEASE)
  | _ -> None
