(tests
 (names test_window smoke test_memory test_machine test_function)
 (libraries device_pci unix windtrap)
 (foreign_stubs
  (language c)
  (names test_stubs)
  (extra_deps ../device_pci.h)
  (flags :standard -std=c11 -Wall -Wextra -I ..)))

(tests
 (names test_space test_page_table)
 (libraries device_pci windtrap))

(tests
 (names test_firmware)
 (libraries device_pci unix windtrap))
