(* This file is selected when nx.metal is not available *)

let is_available = false

let not_available () =
  failwith "Metal backend is not available on this platform"

type context = unit
type ('a, 'b) t = unit

let create_context () = not_available ()
let view _t = not_available ()
let dtype _t = not_available ()
let context _t = not_available ()
let data _t = not_available ()
let op_buffer _t = not_available ()
let op_const_scalar _t = not_available ()
let op_const_array _t = not_available ()
let op_add _t = not_available ()
let op_mul _t = not_available ()
let op_idiv _t = not_available ()
let op_fdiv _t = not_available ()
let op_max _t = not_available ()
let op_mod _t = not_available ()
let op_pow _t = not_available ()
let op_cmplt _t = not_available ()
let op_cmpne _t = not_available ()
let op_xor _t = not_available ()
let op_or _t = not_available ()
let op_and _t = not_available ()
let op_neg _t = not_available ()
let op_log2 _t = not_available ()
let op_exp2 _t = not_available ()
let op_sin _t = not_available ()
let op_sqrt _t = not_available ()
let op_recip _t = not_available ()
let op_where _t = not_available ()
let op_reduce_sum ~axes:_ ~keepdims:_ _t = not_available ()
let op_reduce_max ~axes:_ ~keepdims:_ _t = not_available ()
let op_reduce_prod ~axes:_ ~keepdims:_ _t = not_available ()
let op_expand _t = not_available ()
let op_reshape _t = not_available ()
let op_permute _t = not_available ()
let op_pad _t = not_available ()
let op_shrink _t = not_available ()
let op_flip _t = not_available ()
let op_cat _t = not_available ()
let op_cast _t = not_available ()
let op_contiguous _t = not_available ()
let op_copy _t = not_available ()
let op_assign _t = not_available ()
let op_threefry _t = not_available ()
let op_gather _t = not_available ()
let op_scatter _t = not_available ()
