(library
 (name rig_disk_bench)
 (modules)
 (foreign_stubs
  (language c)
  (names rig_disk_bench_stubs)))

(executable
 (name bench_disk)
 (modules bench_disk)
 (libraries rig rig_disk rig_disk_bench thumper))

(rule
 (alias bench)
 (locks %{workspace_root}/bench)
 (deps
  (glob_files *.thumper))
 (action
  (run %{exe:bench_disk.exe})))
