(tests
 (names test_packet test_method test_gpfifo test_launch test_local)
 (modules test_packet test_method test_gpfifo test_launch test_local)
 (libraries device_nv_abi windtrap))

(test
 (name test_cubin)
 (modules test_cubin)
 (libraries device_nv_abi windtrap)
 (deps ../../../elf/test/fixtures/simple_add_sm89.cubin))
