(* generated by packages/nx/test/gen/special.py; do not edit *)

(* erfinv's guess below [w = erfinv_w_split], [w = -log ((1 - p)(1 + p))], a
   polynomial in [w - erfinv_central_shift]: Giles, Approximating the erfinv
   function, GPU Computing Gems Jade (2011), single precision. *)
let erfinv_central =
  [|
    0x1.e2cb1p-26;
    0x1.70966cp-22;
    -0x1.d8e6aep-19;
    -0x1.26b582p-18;
    0x1.ca65b6p-13;
    -0x1.48a81p-10;
    -0x1.11c9dep-8;
    0x1.f91ec6p-3;
    0x1.805c5ep+0;
  |]

(* Its guess from [w = erfinv_w_split], a polynomial in [sqrt w -
   erfinv_tail_shift]. *)
let erfinv_tail =
  [|
    -0x1.a3e136p-13;
    0x1.a76ad6p-14;
    0x1.61b8e4p-10;
    -0x1.e17bcep-9;
    0x1.7824f6p-8;
    -0x1.f38baep-8;
    0x1.354afcp-7;
    0x1.006db6p+0;
    0x1.6a9efcp+1;
  |]

(* Where the guess changes polynomial. *)
let erfinv_w_split =
  0x1.4p+2

(* The central polynomial's origin in [w]. *)
let erfinv_central_shift =
  0x1.4p+1

(* The tail polynomial's origin in [sqrt w]. *)
let erfinv_tail_shift =
  0x1.8p+1

(* erf 2, below which in [|p|] the float64 refinement runs Newton on erf's
   series, and from which on erfc's continued fraction. *)
let erfinv_erf2 =
  0x1.fd9ae142795e3p-1

(* The series' terms. *)
let erf_series_terms =
  80

(* The continued fraction's terms. *)
let erfc_fraction_terms =
  64
