(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by gen/gen.py from the excerpts in gen/headers; do not
   edit. The command that regenerates this file is in gen/gen.py.

   The values are copied from rdma-core's and Linux's headers, which
   offer the GNU General Public License version 2 or the OpenIB.org BSD
   licence; raven takes the BSD licence:

   Copyright (c) 2013-2015, Mellanox Technologies. All rights reserved.
   Copyright (c) 2012 Mellanox Technologies, Inc.  All rights reserved.
   Copyright (c) 2020 Intel Corporation.  All rights reserved.
   Copyright (c) 2013-2020, Mellanox Technologies inc. All rights reserved.
   Copyright (c) 2020, Intel Corporation. All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

    - Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    - Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE. *)

(* Constants *)

let mlx5_lib_cap_4k_uar = 1
let mlx5_non_fp_bfregs_per_uar = 2
let mlx5_cqe_version_v0 = 0
let mlx5_ib_default_uidx = 0xffffff

(* Structures: each field is (byte offset, bytes). *)

module Ucontext_req = struct
  let sizeof = 32
  let total_num_bfregs = (0, 4)
  let num_low_latency_bfregs = (4, 4)
  let flags = (8, 4)
  let comp_mask = (12, 4)
  let max_cqe_version = (16, 1)
  let reserved0 = (17, 1)
  let reserved1 = (18, 2)
  let reserved2 = (20, 4)
  let lib_caps = (24, 8)
end

module Ucontext_resp = struct
  let sizeof = 72
  let qp_tab_size = (0, 4)
  let bf_reg_size = (4, 4)
  let tot_bfregs = (8, 4)
  let cache_line_size = (12, 4)
  let max_sq_desc_sz = (16, 2)
  let max_rq_desc_sz = (18, 2)
  let max_send_wqebb = (20, 4)
  let max_recv_wr = (24, 4)
  let max_srq_recv_wr = (28, 4)
  let num_ports = (32, 2)
  let flow_action_flags = (34, 2)
  let comp_mask = (36, 4)
  let response_length = (40, 4)
  let cqe_version = (44, 1)
  let cmds_supp_uhw = (45, 1)
  let eth_min_inline = (46, 1)
  let clock_info_versions = (47, 1)
  let hca_core_clock_offset = (48, 8)
  let log_uar_size = (56, 4)
  let num_uars_per_page = (60, 4)
  let num_dyn_bfregs = (64, 4)
  let dump_fill_mkey = (68, 4)
end

module Create_cq = struct
  let sizeof = 32
  let buf_addr = (0, 8)
  let db_addr = (8, 8)
  let cqe_size = (16, 4)
  let cqe_comp_en = (20, 1)
  let cqe_comp_res_format = (21, 1)
  let flags = (22, 2)
  let uar_page_index = (24, 2)
  let reserved0 = (26, 2)
  let reserved1 = (28, 4)
end

module Create_cq_resp = struct
  let sizeof = 8
  let cqn = (0, 4)
  let reserved = (4, 4)
end

module Create_qp = struct
  let sizeof = 56
  let buf_addr = (0, 8)
  let db_addr = (8, 8)
  let sq_wqe_count = (16, 4)
  let rq_wqe_count = (20, 4)
  let rq_wqe_shift = (24, 4)
  let flags = (28, 4)
  let uidx = (32, 4)
  let bfreg_index = (36, 4)
  let sq_buf_addr = (40, 8)
  let access_key = (40, 8)
  let ece_options = (48, 4)
  let dci_streams = (52, 2)
  let dci_streams__log_num_concurent = (52, 1)
  let dci_streams__log_num_errored = (53, 1)
  let reserved = (54, 2)
end

module Create_qp_resp = struct
  let sizeof = 40
  let bfreg_index = (0, 4)
  let ece_options = (4, 4)
  let comp_mask = (8, 4)
  let tirn = (12, 4)
  let tisn = (16, 4)
  let rqn = (20, 4)
  let sqn = (24, 4)
  let reserved1 = (28, 4)
  let tir_icm_addr = (32, 8)
end
