# soupault.toml

[settings]
  site_dir = "site"
  build_dir = "build"
  default_template_file = "templates/main.html"
  default_content_selector = "main"
  complete_page_selector = "html"
  generator_mode = true
  clean_urls = true
  page_file_extensions = ["htm", "html"]
  markdown_extensions = ["md"]
  keep_doctype = true
  pretty_print_html = true
  plugin_discovery = true # Or load explicitly
  plugin_dirs = ["plugins"] # Default

[templates.hugin_project_config]
  file = "templates/layout_hugin.html"
  section = "hugin/"
  include_subsections = true
  content_selector = "main"

[templates.ndarray_project_config]
  file = "templates/layout_ndarray.html"
  section = "ndarray/"
  include_subsections = true
  content_selector = "main"

[templates.rune_project_config]
  file = "templates/layout_rune.html"
  section = "rune/"
  include_subsections = true
  content_selector = "main"

[templates.quill_project_config]
  file = "templates/layout_quill.html"
  section = "quill/"
  include_subsections = true
  content_selector = "main"

[templates.kaun_project_config]
  file = "templates/layout_kaun.html"
  section = "kaun/"
  include_subsections = true
  content_selector = "main"

[templates.sowilo_project_config]
  file = "templates/layout_sowilo.html"
  section = "sowilo/"
  include_subsections = true
  content_selector = "main"

[templates.docs_config]
  file = "templates/layout_docs.html"
  section = "docs/"
  include_subsections = true
  content_selector = "main"

[widgets.page_title]
  widget = "title"
  selector = "h1"
  default = "Raven Ecosystem"
  append = " - Raven"
  # keep = false # Add if you want to force overwrite existing <title> tags

[widgets.clean_empty_paragraphs]
  widget = "delete_element"
  selector = "p:empty"

[widgets.append_current_page_to_breadcrumbs]
  widget = "append_page_title_to_breadcrumbs"
  selector = "#breadcrumbs"

[widgets.include_footer]
  widget = "include"
  file = "templates/partials/footer.html"
  selector = "#footer"
  action = "replace_element"

[widgets.include_project_nav]
  widget = "include"
  file = "templates/partials/project-nav.html"
  selector = "#project-nav"
  action = "replace_element"

[widgets.style_documentation_main_tag]
  widget = "style_doc_main"
  selector = "main"