(* Generated by gen.py; do not edit. The inputs and the command that
   regenerates this file are in gen.py; their digests are in pins.json. *)

(* The kernel descriptor: each field is (byte offset, bytes). *)
module Kernel_descriptor = struct
  let sizeof = 64
  let group_segment_fixed_size = (0, 4)
  let private_segment_fixed_size = (4, 4)
  let kernarg_size = (8, 4)
  let kernel_code_entry_byte_offset = (16, 8)
  let compute_pgm_rsrc3 = (44, 4)
  let compute_pgm_rsrc1 = (48, 4)
  let compute_pgm_rsrc2 = (52, 4)
  let kernel_code_properties = (56, 2)
end

(* Its code properties. *)
let amd_kernel_code_properties_enable_sgpr_private_segment_buffer = 1
let amd_kernel_code_properties_enable_sgpr_dispatch_ptr = 2
let amd_kernel_code_properties_enable_wavefront_size32 = 0x400
