(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Differential test against HuggingFace [tokenizers]. The expected encodings
   are generated by test/scripts/gen_parity_expected.py, which documents both
   fixture formats. *)

open Brot
open Windtrap

let corpora = [ "sample"; "edge_cases" ]
let models = [ "gpt2"; "llama"; "bert_base" ]
let corpus_path corpus = Filename.concat "fixtures/parity" (corpus ^ ".txt")

let ids_path corpus model =
  Filename.concat "fixtures/parity" (corpus ^ "." ^ model ^ ".ids")

let model_path model = Filename.concat "../bench/data" (model ^ ".json")

(* Fixtures *)

(* The last byte of a fixture is a newline that belongs to the file, not to the
   last document or the last row. *)

let drop_final_newline text =
  let n = String.length text in
  if n > 0 && text.[n - 1] = '\n' then String.sub text 0 (n - 1) else text

let lines text = String.split_on_char '\n' (drop_final_newline text)

let documents corpus =
  let text = Fixture.read (corpus_path corpus) in
  let join current = String.concat "\n" (List.rev current) in
  let rec split docs current = function
    | [] -> List.rev (join current :: docs)
    | "====" :: rest -> split (join current :: docs) [] rest
    | line :: rest -> split docs (line :: current) rest
  in
  (drop_final_newline text, Array.of_list (split [] [] (lines text)))

(* Expected encodings. Every row is a kind followed by its value, the five
   per-document kinds once per document in document order, then the whole file
   as a single document under ALL. [ids] and [offsets] are what
   [add_special_tokens:false] must produce, [offsets] holding one byte span per
   [ids] token; [decode] is the [ids] row decoded back to text; [special] and
   [mask] are what [add_special_tokens:true] must produce; [whole] is the whole
   file with [add_special_tokens:false]. *)

type expected = {
  ids : int array array;
  offsets : (int * int) array array;
  decode : string array;
  special : int array array;
  mask : int array array;
  whole : int array;
}

let row line =
  match String.index_opt line ' ' with
  | None -> (line, "")
  | Some i ->
      (String.sub line 0 i, String.sub line (i + 1) (String.length line - i - 1))

let fields rest =
  List.filter (fun field -> field <> "") (String.split_on_char ' ' rest)

let number relative field =
  match int_of_string_opt field with
  | Some value -> value
  | None -> failf "%s: malformed number %S" relative field

let numbers relative fields = Array.of_list (List.map (number relative) fields)

let spans relative fields =
  Array.of_list
    (List.map
       (fun field ->
         match String.index_opt field ',' with
         | None -> failf "%s: malformed span %S" relative field
         | Some i ->
             ( number relative (String.sub field 0 i),
               number relative
                 (String.sub field (i + 1) (String.length field - i - 1)) ))
       fields)

(* The DECODE row is a JSON string: the quotes keep leading and trailing spaces
   visible, and the escapes keep a newline or a tab in decoded text from
   breaking the line-based format. *)
let unescape relative quoted =
  let n = String.length quoted in
  if n < 2 || quoted.[0] <> '"' || quoted.[n - 1] <> '"' then
    failf "%s: text is not a quoted string: %S" relative quoted;
  let buffer = Buffer.create (n - 2) in
  let hex at =
    let value = ref 0 in
    for i = at to at + 3 do
      if i >= n - 1 then failf "%s: truncated \\u escape" relative;
      value :=
        (!value * 16)
        +
        match quoted.[i] with
        | '0' .. '9' as c -> Char.code c - Char.code '0'
        | 'a' .. 'f' as c -> Char.code c - Char.code 'a' + 10
        | 'A' .. 'F' as c -> Char.code c - Char.code 'A' + 10
        | c -> failf "%s: %C is not a hex digit" relative c
    done;
    !value
  in
  let at = ref 1 in
  while !at < n - 1 do
    match quoted.[!at] with
    | '\\' when !at + 1 < n - 1 -> (
        let escaped = quoted.[!at + 1] in
        at := !at + 2;
        let literal c = Buffer.add_char buffer c in
        match escaped with
        | '"' -> literal '"'
        | '\\' -> literal '\\'
        | '/' -> literal '/'
        | 'b' -> literal '\b'
        | 'f' -> literal '\012'
        | 'n' -> literal '\n'
        | 'r' -> literal '\r'
        | 't' -> literal '\t'
        | 'u' ->
            let code = hex !at in
            at := !at + 4;
            (* A scalar above the BMP is written as a surrogate pair. *)
            let scalar =
              if code < 0xd800 || code > 0xdfff then code
              else if
                code <= 0xdbff
                && !at + 6 <= n - 1
                && quoted.[!at] = '\\'
                && quoted.[!at + 1] = 'u'
              then begin
                let low = hex (!at + 2) in
                if low < 0xdc00 || low > 0xdfff then
                  failf "%s: \\u%04x is not a low surrogate" relative low;
                at := !at + 6;
                0x10000 + ((code - 0xd800) * 0x400) + (low - 0xdc00)
              end
              else failf "%s: \\u%04x is an unpaired surrogate" relative code
            in
            Buffer.add_utf_8_uchar buffer (Uchar.of_int scalar)
        | c -> failf "%s: unknown escape \\%c" relative c)
    | '\\' -> failf "%s: text ends in a backslash" relative
    | c ->
        Buffer.add_char buffer c;
        incr at
  done;
  Buffer.contents buffer

(* The rows of a document are zipped by position, so the file has to hold them
   in this order and complete. *)
let order = [| "IDS"; "OFFSETS"; "DECODE"; "SPECIAL"; "MASK" |]

let expected corpus model =
  let relative = ids_path corpus model in
  let ids = ref []
  and offsets = ref []
  and decode = ref []
  and special = ref []
  and mask = ref []
  and whole = ref None
  and position = ref 0 in
  List.iter
    (fun line ->
      if not (String.starts_with ~prefix:"#" line) then begin
        let kind, rest = row line in
        if Option.is_some !whole then
          failf "%s: %S row after the ALL row" relative kind;
        let in_order () =
          if kind <> order.(!position) then
            failf "%s: %S row where a %s row was expected" relative kind
              order.(!position);
          position := (!position + 1) mod Array.length order
        in
        match kind with
        | "IDS" ->
            in_order ();
            ids := numbers relative (fields rest) :: !ids
        | "OFFSETS" ->
            in_order ();
            offsets := spans relative (fields rest) :: !offsets
        | "DECODE" ->
            in_order ();
            decode := unescape relative rest :: !decode
        | "SPECIAL" ->
            in_order ();
            special := numbers relative (fields rest) :: !special
        | "MASK" ->
            in_order ();
            mask := numbers relative (fields rest) :: !mask
        | "ALL" ->
            if !position <> 0 then
              failf "%s: ALL row where a %s row was expected" relative
                order.(!position);
            whole := Some (numbers relative (fields rest))
        | _ -> failf "%s: unknown row kind %S" relative kind
      end)
    (lines (Fixture.read relative));
  let ids = Array.of_list (List.rev !ids) in
  let aligned kind rows =
    let rows = Array.of_list (List.rev rows) in
    if Array.length rows <> Array.length ids then
      failf "%s: %d %s rows for %d IDS rows" relative (Array.length rows) kind
        (Array.length ids);
    rows
  in
  match !whole with
  | None -> failf "%s: no ALL row" relative
  | Some whole ->
      {
        ids;
        offsets = aligned "OFFSETS" !offsets;
        decode = aligned "DECODE" !decode;
        special = aligned "SPECIAL" !special;
        mask = aligned "MASK" !mask;
        whole;
      }

(* Reporting *)

type document = Numbered of int | Whole

let describe = function
  | Numbered index -> Printf.sprintf "document %d" index
  | Whole -> "whole file"

let label = function
  | Numbered index -> string_of_int index
  | Whole -> "whole file"

let window render values index =
  let n = Array.length values in
  if index >= n then "(past end)"
  else
    let first = max 0 (index - 3) and last = min (n - 1) (index + 3) in
    let buffer = Buffer.create 64 in
    if first > 0 then Buffer.add_string buffer "… ";
    for i = first to last do
      if i > first then Buffer.add_char buffer ' ';
      if i = index then
        Buffer.add_string buffer (Printf.sprintf "[%s]" (render values.(i)))
      else Buffer.add_string buffer (render values.(i))
    done;
    if last < n - 1 then Buffer.add_string buffer " …";
    Buffer.contents buffer

let render_span (start, stop) = Printf.sprintf "%d,%d" start stop

(* Escape what would break the message, and leave the rest of the UTF-8 alone so
   that a mismatch inside non-Latin text stays readable. *)
let escape text =
  let buffer = Buffer.create (String.length text + 8) in
  String.iter
    (fun c ->
      match c with
      | '"' | '\\' ->
          Buffer.add_char buffer '\\';
          Buffer.add_char buffer c
      | '\n' -> Buffer.add_string buffer "\\n"
      | '\r' -> Buffer.add_string buffer "\\r"
      | '\t' -> Buffer.add_string buffer "\\t"
      | c when Char.code c < 0x20 || Char.code c = 0x7f ->
          Buffer.add_string buffer (Printf.sprintf "\\x%02x" (Char.code c))
      | c -> Buffer.add_char buffer c)
    text;
  Buffer.contents buffer

let text_window text (start, stop) =
  let n = String.length text in
  let is_continuation i = Char.code text.[i] land 0xc0 = 0x80 in
  let first = ref (max 0 (min n start - 24)) in
  while !first > 0 && !first < n && is_continuation !first do
    decr first
  done;
  let last = ref (max !first (min n (stop + 24))) in
  while !last > !first && !last < n && is_continuation !last do
    decr last
  done;
  Printf.sprintf "%s\"%s\"%s"
    (if !first > 0 then "… " else "")
    (escape (String.sub text !first (!last - !first)))
    (if !last < n then " …" else "")

let token tokenizer ids index =
  if index >= Array.length ids then "(past end)"
  else
    match id_to_token tokenizer ids.(index) with
    | Some token -> Printf.sprintf "\"%s\"" (escape token)
    | None -> Printf.sprintf "(id %d not in vocabulary)" ids.(index)

(* [detail] adds lines that only make sense for some kinds, such as the token
   text behind a differing id. *)
let compare_rows ~what ~kind ~via ~text ~offsets ~render ~detail ~expected
    ~actual =
  let common = min (Array.length expected) (Array.length actual) in
  let rec first_difference i =
    if i = common then
      if Array.length expected = Array.length actual then None else Some i
    else if expected.(i) <> actual.(i) then Some i
    else first_difference (i + 1)
  in
  match first_difference 0 with
  | None -> None
  | Some i ->
      let region =
        if i < Array.length offsets then offsets.(i)
        else (String.length text, String.length text)
      in
      let body =
        [
          Printf.sprintf "  text:     %s" (text_window text region);
          Printf.sprintf "  expected: %s" (window render expected i);
          Printf.sprintf "  actual:   %s" (window render actual i);
        ]
        @ detail i
        @ [
            Printf.sprintf "  lengths:  expected %d, actual %d"
              (Array.length expected) (Array.length actual);
          ]
      in
      Some
        (Printf.sprintf "%s (%s): %s differ at index %d\n%s" what via kind i
           (String.concat "\n" body))

let compare_text ~what ~via ~expected ~actual =
  let common = min (String.length expected) (String.length actual) in
  let rec first_difference i =
    if i = common then
      if String.length expected = String.length actual then None else Some i
    else if expected.[i] <> actual.[i] then Some i
    else first_difference (i + 1)
  in
  match first_difference 0 with
  | None -> None
  | Some i ->
      Some
        (Printf.sprintf
           "%s (%s): text differs at byte %d\n\
           \  expected: %s\n\
           \  actual:   %s\n\
           \  lengths:  expected %d, actual %d"
           what via i
           (text_window expected (i, i))
           (text_window actual (i, i))
           (String.length expected) (String.length actual))

(* Every document is checked, so that a fix can be measured by how much of the
   corpus it recovers, not just by which document now fails first. *)
let survey check =
  let differing = ref [] and checked = ref 0 in
  check (fun document difference ->
      incr checked;
      match difference with
      | None -> ()
      | Some message -> differing := (document, message) :: !differing);
  match List.rev !differing with
  | [] -> ()
  | (_, first) :: _ as all ->
      let rec distinct = function
        | (a, _) :: ((b, _) :: _ as rest) when a = b -> distinct rest
        | (a, _) :: rest -> label a :: distinct rest
        | [] -> []
      in
      let labels = distinct all in
      let shown = List.filteri (fun i _ -> i < 12) labels in
      failf
        "%d of %d comparisons differ, in documents: %s%s; the first is:\n\n%s"
        (List.length all) !checked (String.concat ", " shown)
        (if List.length labels > List.length shown then
           Printf.sprintf " and %d more" (List.length labels - List.length shown)
         else "")
        first

(* Tests *)

let what corpus model document =
  Printf.sprintf "%s.txt/%s %s" corpus model (describe document)

let one_row_per_document corpus model docs rows =
  equal
    ~msg:(Printf.sprintf "%s: one row per document" (ids_path corpus model))
    int (Array.length docs) (Array.length rows)

let ids_detail tokenizer ~expected ~actual i =
  [
    Printf.sprintf "  token:    expected %s, actual %s"
      (token tokenizer expected i)
      (token tokenizer actual i);
  ]

(* [add_special_tokens:false] ids, through both entry points, plus the whole
   file, which the other kinds have no row for and so has no reference spans to
   place a mismatch with. *)
let check_ids model corpus tokenizer =
  let text, docs = documents corpus in
  let rows = expected corpus model in
  one_row_per_document corpus model docs rows.ids;
  survey (fun record ->
      let check document text ~expected ~offsets =
        let against ~via ~actual =
          compare_rows
            ~what:(what corpus model document)
            ~kind:"ids" ~via ~text ~offsets ~render:string_of_int
            ~detail:(ids_detail tokenizer ~expected ~actual)
            ~expected ~actual
        in
        record document
          (against ~via:"encode"
             ~actual:
               (Encoding.ids (encode tokenizer ~add_special_tokens:false text)));
        record document
          (against ~via:"encode_ids"
             ~actual:(encode_ids tokenizer ~add_special_tokens:false text))
      in
      Array.iteri
        (fun index text ->
          check (Numbered index) text ~expected:rows.ids.(index)
            ~offsets:rows.offsets.(index))
        docs;
      check Whole text ~expected:rows.whole ~offsets:[||])

(* Reference spans for an [add_special_tokens:true] row: the post-processor's
   own tokens cover nothing, and the rest keep the spans of the row without
   them, in order. *)
let spans_with_specials ~mask ~offsets =
  let taken = ref 0 in
  Array.map
    (fun flag ->
      if flag <> 0 then (0, 0)
      else begin
        let span =
          if !taken < Array.length offsets then offsets.(!taken) else (0, 0)
        in
        incr taken;
        span
      end)
    mask

(* A mismatch is placed in the text with the reference spans, never with the
   ones under test. *)
let check_kind ~kind ~add_special_tokens ~rows_of ~spans_of ~select ~render
    ~detail model corpus tokenizer =
  let _, docs = documents corpus in
  let all = expected corpus model in
  let rows = rows_of all in
  one_row_per_document corpus model docs rows;
  survey (fun record ->
      Array.iteri
        (fun index text ->
          let encoding = encode tokenizer ~add_special_tokens text in
          let actual = select encoding in
          record (Numbered index)
            (compare_rows
               ~what:(what corpus model (Numbered index))
               ~kind ~via:"encode" ~text ~offsets:(spans_of all index) ~render
               ~detail:(detail tokenizer encoding rows.(index))
               ~expected:rows.(index) ~actual))
        docs)

(* Byte spans of the [add_special_tokens:false] tokens. The reference reports
   character spans; the generator converts them. *)
let check_offsets model corpus tokenizer =
  check_kind ~kind:"offsets" ~add_special_tokens:false
    ~rows_of:(fun rows -> rows.offsets)
    ~spans_of:(fun rows index -> rows.offsets.(index))
    ~select:Encoding.offsets ~render:render_span
    ~detail:(fun tokenizer encoding _ i ->
      [
        Printf.sprintf "  token:    %s"
          (token tokenizer (Encoding.ids encoding) i);
      ])
    model corpus tokenizer

(* The decoder is driven by the reference ids rather than by brot's own
   encoding, so that a decoder divergence stays visible where the encoder is
   still wrong. *)
let check_decode model corpus tokenizer =
  let _, docs = documents corpus in
  let rows = expected corpus model in
  one_row_per_document corpus model docs rows.decode;
  survey (fun record ->
      Array.iteri
        (fun index expected ->
          record (Numbered index)
            (compare_text
               ~what:(what corpus model (Numbered index))
               ~via:"decode" ~expected
               ~actual:(decode tokenizer rows.ids.(index))))
        rows.decode)

(* What the post-processor adds: [add_special_tokens:true] ids, and the mask
   that goes with them. *)

let special_spans rows index =
  spans_with_specials ~mask:rows.mask.(index) ~offsets:rows.offsets.(index)

let check_special model corpus tokenizer =
  check_kind ~kind:"ids" ~add_special_tokens:true
    ~rows_of:(fun rows -> rows.special)
    ~spans_of:special_spans ~select:Encoding.ids ~render:string_of_int
    ~detail:(fun tokenizer encoding expected i ->
      ids_detail tokenizer ~expected ~actual:(Encoding.ids encoding) i)
    model corpus tokenizer

let no_detail _ _ _ _ = []

let check_mask model corpus tokenizer =
  check_kind ~kind:"mask flags" ~add_special_tokens:true
    ~rows_of:(fun rows -> rows.mask)
    ~spans_of:special_spans ~select:Encoding.special_tokens_mask
    ~render:string_of_int ~detail:no_detail model corpus tokenizer

(* Every document here is a single sequence, so its type ids are all 0 and its
   attention mask all 1, and both run the whole length of the ids: a
   post-processor that appends a special token to the ids alone must not pass.
   Asserting that costs nothing, where recording it would be tens of thousands
   of constants in the fixtures. *)
let check_constant ~kind ~select ~value model corpus tokenizer =
  let _, docs = documents corpus in
  survey (fun record ->
      Array.iteri
        (fun index text ->
          let encoding = encode tokenizer ~add_special_tokens:true text in
          let actual = select encoding in
          let ids = Encoding.ids encoding in
          let what = what corpus model (Numbered index) in
          let rec first_difference i =
            if i = Array.length actual then None
            else if actual.(i) <> value then Some i
            else first_difference (i + 1)
          in
          record (Numbered index)
            (if Array.length actual <> Array.length ids then
               Some
                 (Printf.sprintf
                    "%s (encode): %d %ss for %d ids\n\
                    \  actual:   %s\n\
                    \  ids:      %s"
                    what (Array.length actual) kind (Array.length ids)
                    (window string_of_int actual 0)
                    (window string_of_int ids 0))
             else
               match first_difference 0 with
               | None -> None
               | Some i ->
                   Some
                     (Printf.sprintf
                        "%s (encode): %s is %d at index %d, expected %d \
                         throughout\n\
                        \  token:    %s\n\
                        \  actual:   %s"
                        what kind actual.(i) i value (token tokenizer ids i)
                        (window string_of_int actual i))))
        docs)

let check_types model corpus tokenizer =
  check_constant ~kind:"type id" ~select:Encoding.type_ids ~value:0 model corpus
    tokenizer

let check_attention model corpus tokenizer =
  check_constant ~kind:"attention flag" ~select:Encoding.attention_mask ~value:1
    model corpus tokenizer

let with_tokenizer model check () =
  Fixture.with_download (model_path model)
    ~from:"packages/brot/bench/download_data.sh" (fun path ->
      match from_file path with
      | Error msg -> failf "failed to load %s: %s" path msg
      | Ok tokenizer -> check tokenizer)

(* One test per (tokenizer, corpus, kind), so that a kind that brot does not yet
   match shows up on its own instead of hiding the kinds after it. *)
let () =
  run "HF parity"
    (List.map
       (fun model ->
         group model
           (List.map
              (fun corpus ->
                group corpus
                  (List.map
                     (fun (kind, check) ->
                       test kind (with_tokenizer model (check model corpus)))
                     [
                       ("ids", check_ids);
                       ("offsets", check_offsets);
                       ("decode", check_decode);
                       ("special ids", check_special);
                       ("special tokens mask", check_mask);
                       ("type ids", check_types);
                       ("attention mask", check_attention);
                     ]))
              corpora))
       models)
