(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by gen/gen.py from the excerpts in gen/headers; do not edit.
   The command that regenerates this file is in gen/gen.py.

   The values are NVIDIA's, copied from its headers under the MIT licence:

   clc56f.h: Copyright (c) 2020-2022 NVIDIA CORPORATION & AFFILIATES
   clc7c0.h: Copyright (c) 2020-2022 NVIDIA CORPORATION & AFFILIATES
   clc9c0.h: Copyright (c) 2003-2022 NVIDIA CORPORATION & AFFILIATES
   clcec0.h: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES
   clc7b5.h: Copyright (c) 2020, NVIDIA CORPORATION
   clc9b5.h: Copyright (c) 1993-2004 NVIDIA Corporation
   clc7c0qmd.h: Copyright (c) 2020, NVIDIA CORPORATION
   clc9c0qmd.h: Copyright (c) 2023, NVIDIA CORPORATION
   clcec0qmd.h: Copyright (c) 2025, NVIDIA CORPORATION

   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE. *)

(* A bit field of a word or a descriptor: its lowest bit and its bits. *)
type field = { lo : int; bits : int }

(* A field for each constant bank: bank i's starts [i * stride] bits after
   bank 0's. *)
type banked = { first : field; stride : int }

(* The fields of a descriptor's release. *)
type release = {
  enable : field;
  structure_size : field;
  payload64b : field;
  membar_type : field;
  address_lower : field;
  address_upper : field;
  payload_lower : field;
  payload_upper : field;
}

(* A descriptor version's layout, by NVIDIA's names of its fields. Where the
   versions' names differ by a suffix _SHIFTEDn, which says the field holds
   its value shifted right by n, the name drops it and a [_shift] holds n. A
   field the version lacks is [None]. [bytes] is the descriptor's size, the
   end of its last field. *)
type qmd = {
  version : int;
  bytes : int;
  qmd_major_version : field;
  qmd_type : field option;
  sm_global_caching_enable : field option;
  qmd_group_id : field;
  grid_width : field;
  grid_height : field;
  grid_depth : field;
  cta_thread_dimension0 : field;
  cta_thread_dimension1 : field;
  cta_thread_dimension2 : field;
  register_count : field;
  barrier_count : field;
  shared_memory_size : field;
  min_sm_config_shared_mem_size : field;
  target_sm_config_shared_mem_size : field;
  max_sm_config_shared_mem_size : field;
  shader_local_memory_high_size : field;
  program_address_lower : field;
  program_address_upper : field;
  program_prefetch_addr_lower_shifted : field;
  program_prefetch_addr_upper_shifted : field;
  program_prefetch_size : field;
  sass_version : field;
  api_visible_call_limit : field;
  sampler_index : field;
  cwd_membar_type : field;
  invalidate_texture_header_cache : field;
  invalidate_texture_sampler_cache : field;
  invalidate_texture_data_cache : field;
  invalidate_shader_data_cache : field;
  dependent_qmd0_pointer : field;
  dependent_qmd0_action : field;
  dependent_qmd0_prefetch : field;
  dependent_qmd0_enable : field;
  constant_buffer_addr_lower : banked;
  constant_buffer_addr_upper : banked;
  constant_buffer_size_shifted4 : banked;
  constant_buffer_valid : banked;
  constant_buffer_invalidate : banked;
  program_address_shift : int;
  constant_buffer_addr_shift : int;
  shader_local_memory_shift : int;
  shared_memory_shift : int;
  releases : release * release;
}

(* Classes *)

let ampere_compute_b = 0xc7c0
let ada_compute_a = 0xc9c0
let blackwell_compute_b = 0xcec0

(* Host methods (clc56f.h) *)

let nvc56f_set_object = 0
let nvc56f_sem_addr_lo = 0x5c
let nvc56f_non_stall_interrupt = 0x20
let nvc56f_sem_execute_operation_acq_circ_geq = 3
let nvc56f_sem_execute_operation_release = 1
let nvc56f_sem_execute_payload_size_64bit = 1
let nvc56f_sem_execute_release_wfi_en = 1
let nvc56f_sem_execute_release_timestamp_en = 1
let nvc56f_gp_entry1_level_subroutine = 1
let nvc56f_dma_sec_op_inc_method = 1
let nvc56f_sem_execute_operation = { lo = 0; bits = 3 }
let nvc56f_sem_execute_payload_size = { lo = 0x18; bits = 1 }
let nvc56f_sem_execute_release_wfi = { lo = 0x14; bits = 1 }
let nvc56f_sem_execute_release_timestamp = { lo = 0x19; bits = 1 }
let nvc56f_gp_entry0_get = { lo = 2; bits = 0x1e }
let nvc56f_gp_entry1_get_hi = { lo = 0; bits = 8 }
let nvc56f_gp_entry1_level = { lo = 9; bits = 1 }
let nvc56f_gp_entry1_length = { lo = 0xa; bits = 0x15 }
let nvc56f_dma_method_address = { lo = 0; bits = 0xc }
let nvc56f_dma_method_subchannel = { lo = 0xd; bits = 3 }
let nvc56f_dma_method_count = { lo = 0x10; bits = 0xd }
let nvc56f_dma_sec_op = { lo = 0x1d; bits = 3 }

(* Compute methods (clc7c0.h) *)

let nvc7c0_set_shader_shared_memory_window_a = 0x2a0
let nvc7c0_set_shader_local_memory_window_a = 0x7b0
let nvc7c0_set_shader_local_memory_a = 0x790
let nvc7c0_set_shader_local_memory_non_throttled_a = 0x2e4
let nvc7c0_invalidate_shader_caches_no_wfi = 0x1698
let nvc7c0_invalidate_shader_caches_no_wfi_instruction_true = 1
let nvc7c0_invalidate_shader_caches_no_wfi_global_data_true = 1
let nvc7c0_invalidate_shader_caches_no_wfi_constant_true = 1
let nvc7c0_send_pcas_a = 0x2b4
let nvc7c0_send_signaling_pcas2_b = 0x2c0
let nvc7c0_send_signaling_pcas2_b_pcas_action_prefetch_schedule = 9
let nvc7c0_invalidate_shader_caches_no_wfi_instruction = { lo = 0; bits = 1 }
let nvc7c0_invalidate_shader_caches_no_wfi_global_data = { lo = 4; bits = 1 }
let nvc7c0_invalidate_shader_caches_no_wfi_constant = { lo = 0xc; bits = 1 }
let nvc7c0_send_signaling_pcas2_b_pcas_action = { lo = 0; bits = 4 }

(* Copy methods (clc7b5.h) *)

let nvc7b5_set_semaphore_a = 0x240
let nvc7b5_launch_dma = 0x300
let nvc7b5_offset_in_upper = 0x400
let nvc7b5_line_length_in = 0x418
let nvc7b5_launch_dma_data_transfer_type_non_pipelined = 2
let nvc7b5_launch_dma_src_memory_layout_pitch = 1
let nvc7b5_launch_dma_dst_memory_layout_pitch = 1
let nvc7b5_launch_dma_flush_enable_true = 1
let nvc7b5_launch_dma_flush_type_sys = 0
let nvc7b5_launch_dma_semaphore_type_release_one_word_semaphore = 1
let nvc7b5_launch_dma_semaphore_type_release_four_word_semaphore = 2
let nvc7b5_launch_dma_semaphore_payload_size_two_word = 1
let nvc7b5_launch_dma_data_transfer_type = { lo = 0; bits = 2 }
let nvc7b5_launch_dma_flush_enable = { lo = 2; bits = 1 }
let nvc7b5_launch_dma_flush_type = { lo = 0x19; bits = 1 }
let nvc7b5_launch_dma_semaphore_type = { lo = 3; bits = 2 }
let nvc7b5_launch_dma_semaphore_payload_size = { lo = 0x1b; bits = 1 }
let nvc7b5_launch_dma_src_memory_layout = { lo = 7; bits = 1 }
let nvc7b5_launch_dma_dst_memory_layout = { lo = 8; bits = 1 }

(* Launch descriptors *)

let qmd_type_grid_cta = 2
let cwd_membar_type_l1_sysmembar = 1
let api_visible_call_limit_no_check = 1
let sampler_index_via_header_index = 1
let dependent_qmd0_action_qmd_schedule = 1
let release_structure_size_semaphore_four_words = 0
let release_membar_type_fe_none = 0
let release_structure_size_semaphore_two_words = 2

(* Version 3, NVC7C0_QMDV03_00 (clc7c0qmd.h). *)
let qmd_v3 =
  {
    version = 3;
    bytes = 0x100;
    qmd_major_version = { lo = 0x244; bits = 4 };
    qmd_type = None;
    sm_global_caching_enable = Some { lo = 0x86; bits = 1 };
    qmd_group_id = { lo = 0x80; bits = 6 };
    grid_width = { lo = 0x180; bits = 0x20 };
    grid_height = { lo = 0x1a0; bits = 0x10 };
    grid_depth = { lo = 0x1c0; bits = 0x10 };
    cta_thread_dimension0 = { lo = 0x250; bits = 0x10 };
    cta_thread_dimension1 = { lo = 0x260; bits = 0x10 };
    cta_thread_dimension2 = { lo = 0x270; bits = 0x10 };
    register_count = { lo = 0x288; bits = 9 };
    barrier_count = { lo = 0x2fb; bits = 5 };
    shared_memory_size = { lo = 0x220; bits = 0x12 };
    min_sm_config_shared_mem_size = { lo = 0x232; bits = 6 };
    target_sm_config_shared_mem_size = { lo = 0x291; bits = 6 };
    max_sm_config_shared_mem_size = { lo = 0x239; bits = 6 };
    shader_local_memory_high_size = { lo = 0x640; bits = 0x18 };
    program_address_lower = { lo = 0x600; bits = 0x20 };
    program_address_upper = { lo = 0x620; bits = 0x11 };
    program_prefetch_addr_lower_shifted = { lo = 0x100; bits = 0x20 };
    program_prefetch_addr_upper_shifted = { lo = 0x660; bits = 9 };
    program_prefetch_size = { lo = 0x669; bits = 9 };
    sass_version = { lo = 0x678; bits = 8 };
    api_visible_call_limit = { lo = 0x17a; bits = 1 };
    sampler_index = { lo = 0x17e; bits = 1 };
    cwd_membar_type = { lo = 0x170; bits = 2 };
    invalidate_texture_header_cache = { lo = 0xba; bits = 1 };
    invalidate_texture_sampler_cache = { lo = 0xbb; bits = 1 };
    invalidate_texture_data_cache = { lo = 0xbc; bits = 1 };
    invalidate_shader_data_cache = { lo = 0xbd; bits = 1 };
    dependent_qmd0_pointer = { lo = 0x1e0; bits = 0x20 };
    dependent_qmd0_action = { lo = 0x201; bits = 3 };
    dependent_qmd0_prefetch = { lo = 0x204; bits = 1 };
    dependent_qmd0_enable = { lo = 0x200; bits = 1 };
    constant_buffer_addr_lower = { first = { lo = 0x400; bits = 0x20 }; stride = 64 };
    constant_buffer_addr_upper = { first = { lo = 0x420; bits = 0x11 }; stride = 64 };
    constant_buffer_size_shifted4 = { first = { lo = 0x433; bits = 0xd }; stride = 64 };
    constant_buffer_valid = { first = { lo = 0x280; bits = 1 }; stride = 1 };
    constant_buffer_invalidate = { first = { lo = 0x432; bits = 1 }; stride = 64 };
    program_address_shift = 0;
    constant_buffer_addr_shift = 0;
    shader_local_memory_shift = 0;
    shared_memory_shift = 0;
    releases =
      ( {
          enable = { lo = 0x337; bits = 1 };
          structure_size = { lo = 0x33e; bits = 2 };
          payload64b = { lo = 0x33d; bits = 1 };
          membar_type = { lo = 0x333; bits = 1 };
          address_lower = { lo = 0x300; bits = 0x20 };
          address_upper = { lo = 0x320; bits = 8 };
          payload_lower = { lo = 0x340; bits = 0x20 };
          payload_upper = { lo = 0x360; bits = 0x20 };
        }
      , {
          enable = { lo = 0x3b7; bits = 1 };
          structure_size = { lo = 0x3be; bits = 2 };
          payload64b = { lo = 0x3bd; bits = 1 };
          membar_type = { lo = 0x3b3; bits = 1 };
          address_lower = { lo = 0x380; bits = 0x20 };
          address_upper = { lo = 0x3a0; bits = 8 };
          payload_lower = { lo = 0x3c0; bits = 0x20 };
          payload_upper = { lo = 0x3e0; bits = 0x20 };
        }
      );
  }

(* Version 5, NVCEC0_QMDV05_00 (clcec0qmd.h). *)
let qmd_v5 =
  {
    version = 5;
    bytes = 0x180;
    qmd_major_version = { lo = 0x1d4; bits = 4 };
    qmd_type = Some { lo = 0x97; bits = 3 };
    sm_global_caching_enable = None;
    qmd_group_id = { lo = 0x90; bits = 6 };
    grid_width = { lo = 0x4e0; bits = 0x20 };
    grid_height = { lo = 0x500; bits = 0x10 };
    grid_depth = { lo = 0x520; bits = 0x10 };
    cta_thread_dimension0 = { lo = 0x440; bits = 0x10 };
    cta_thread_dimension1 = { lo = 0x450; bits = 0x10 };
    cta_thread_dimension2 = { lo = 0x460; bits = 8 };
    register_count = { lo = 0x468; bits = 9 };
    barrier_count = { lo = 0x471; bits = 5 };
    shared_memory_size = { lo = 0x480; bits = 0xb };
    min_sm_config_shared_mem_size = { lo = 0x48b; bits = 6 };
    target_sm_config_shared_mem_size = { lo = 0x497; bits = 6 };
    max_sm_config_shared_mem_size = { lo = 0x491; bits = 6 };
    shader_local_memory_high_size = { lo = 0x4b0; bits = 0x10 };
    program_address_lower = { lo = 0x400; bits = 0x20 };
    program_address_upper = { lo = 0x420; bits = 0x15 };
    program_prefetch_addr_lower_shifted = { lo = 0x760; bits = 0x20 };
    program_prefetch_addr_upper_shifted = { lo = 0x780; bits = 0x11 };
    program_prefetch_size = { lo = 0x435; bits = 9 };
    sass_version = { lo = 0x1c0; bits = 8 };
    api_visible_call_limit = { lo = 0x1c8; bits = 1 };
    sampler_index = { lo = 0x1c9; bits = 1 };
    cwd_membar_type = { lo = 0x270; bits = 2 };
    invalidate_texture_header_cache = { lo = 0x1d8; bits = 1 };
    invalidate_texture_sampler_cache = { lo = 0x1d9; bits = 1 };
    invalidate_texture_data_cache = { lo = 0x1da; bits = 1 };
    invalidate_shader_data_cache = { lo = 0x1db; bits = 1 };
    dependent_qmd0_pointer = { lo = 0x180; bits = 0x20 };
    dependent_qmd0_action = { lo = 0x151; bits = 3 };
    dependent_qmd0_prefetch = { lo = 0x154; bits = 1 };
    dependent_qmd0_enable = { lo = 0x150; bits = 1 };
    constant_buffer_addr_lower = { first = { lo = 0x540; bits = 0x20 }; stride = 64 };
    constant_buffer_addr_upper = { first = { lo = 0x560; bits = 0x13 }; stride = 64 };
    constant_buffer_size_shifted4 = { first = { lo = 0x573; bits = 0xd }; stride = 64 };
    constant_buffer_valid = { first = { lo = 0x740; bits = 1 }; stride = 4 };
    constant_buffer_invalidate = { first = { lo = 0x743; bits = 1 }; stride = 4 };
    program_address_shift = 4;
    constant_buffer_addr_shift = 6;
    shader_local_memory_shift = 4;
    shared_memory_shift = 7;
    releases =
      ( {
          enable = { lo = 0x120; bits = 1 };
          structure_size = { lo = 0x121; bits = 2 };
          payload64b = { lo = 0x12c; bits = 1 };
          membar_type = { lo = 0x123; bits = 1 };
          address_lower = { lo = 0x1e0; bits = 0x20 };
          address_upper = { lo = 0x200; bits = 0x19 };
          payload_lower = { lo = 0x220; bits = 0x20 };
          payload_upper = { lo = 0x240; bits = 0x20 };
        }
      , {
          enable = { lo = 0x130; bits = 1 };
          structure_size = { lo = 0x131; bits = 2 };
          payload64b = { lo = 0x13c; bits = 1 };
          membar_type = { lo = 0x133; bits = 1 };
          address_lower = { lo = 0x300; bits = 0x20 };
          address_upper = { lo = 0x320; bits = 0x19 };
          payload_lower = { lo = 0x340; bits = 0x20 };
          payload_upper = { lo = 0x360; bits = 0x20 };
        }
      );
  }
