(library
 (name rig_examples_pool_sum)
 (modules)
 (libraries rig.pool)
 (foreign_stubs
  (language c)
  (names sum)))

(executable
 (name main)
 (modules main)
 (libraries rig_examples_pool_sum))

(rule
 (with-stdout-to
  main.output
  (run ./main.exe)))

(rule
 (alias runtest)
 (action
  (diff main.expected main.output)))
