(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** Joe and Kuo's (2008) Sobol direction numbers for the first 1111 dimensions,
    generated by test/gen/generate.py from the table scipy ships. *)

val poly : int array
(** [poly.(j)] is dimension [j]'s primitive polynomial, its leading and trailing
    coefficients included: its degree is its bit length minus one. *)

val vinit : int array array
(** [vinit.(j)] is dimension [j]'s initial direction numbers, one per degree. *)
