(library
 (name device_cuda_bench)
 (modules)
 (libraries device_cuda device_edge)
 (foreign_stubs
  (language c)
  (names device_cuda_bench_stubs)))

(executable
 (name bench_cuda)
 (modules bench_cuda)
 (libraries device_core device_cuda device_cuda_abi device_cuda_bench device_cuda_support thumper))

(rule
 (alias bench)
 (locks %{workspace_root}/bench)
 (deps
  (glob_files *.thumper)
  (source_tree ../test/fixtures))
 (action
  (run %{exe:bench_cuda.exe})))
