(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by ../gen/gen.py from the excerpts in ../gen/headers; do not
   edit. The command that regenerates this file is in ../gen/gen.py.

   The values are copied from rdma-core's and Linux's headers, which
   offer the GNU General Public License version 2 or the OpenIB.org BSD
   licence; raven takes the BSD licence:

   Copyright (c) 2018, Mellanox Technologies inc.  All rights reserved.
   Copyright (c) 2020, Intel Corporation. All rights reserved.
   Copyright (c) 2017-2018, Mellanox Technologies inc.  All rights reserved.
   Copyright (c) 2005 Topspin Communications.  All rights reserved.
   Copyright (c) 2005, 2006 Cisco Systems.  All rights reserved.
   Copyright (c) 2005 PathScale, Inc.  All rights reserved.
   Copyright (c) 2006 Mellanox Technologies.  All rights reserved.
   Copyright (c) 2004, 2005 Topspin Communications.  All rights reserved.
   Copyright (c) 2004, 2011-2012 Intel Corporation.  All rights reserved.
   Copyright (c) 2005, 2006, 2007 Cisco Systems, Inc.  All rights reserved.
   Copyright (c) 2020 Intel Corporation.  All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

    - Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    - Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE. *)

(* Constants *)

let rdma_ioctl_magic = 0x1b
let uverbs_attr_f_mandatory = 1
let uverbs_object_device = 0
let uverbs_object_mr = 7
let uverbs_method_invoke_write = 0
let uverbs_attr_core_in = 0
let uverbs_attr_core_out = 1
let uverbs_attr_write_cmd = 2
let uverbs_attr_uhw_in = 0x1000
let uverbs_attr_uhw_out = 0x1001
let uverbs_method_reg_dmabuf_mr = 4
let uverbs_attr_reg_dmabuf_mr_handle = 0
let uverbs_attr_reg_dmabuf_mr_pd_handle = 1
let uverbs_attr_reg_dmabuf_mr_offset = 2
let uverbs_attr_reg_dmabuf_mr_length = 3
let uverbs_attr_reg_dmabuf_mr_iova = 4
let uverbs_attr_reg_dmabuf_mr_fd = 5
let uverbs_attr_reg_dmabuf_mr_access_flags = 6
let uverbs_attr_reg_dmabuf_mr_resp_lkey = 7
let uverbs_attr_reg_dmabuf_mr_resp_rkey = 8
let rdma_driver_mlx5 = 1
let rdma_driver_rxe = 0xe
let ib_uverbs_access_local_write = 1
let ib_uverbs_access_remote_write = 2
let ib_uverbs_access_remote_read = 4
let ib_uverbs_access_relaxed_ordering = 0x100000
let ib_uverbs_qpt_rc = 2
let ib_user_verbs_cmd_get_context = 0
let ib_user_verbs_cmd_query_device = 1
let ib_user_verbs_cmd_query_port = 2
let ib_user_verbs_cmd_alloc_pd = 3
let ib_user_verbs_cmd_reg_mr = 9
let ib_user_verbs_cmd_dereg_mr = 0xd
let ib_user_verbs_cmd_create_comp_channel = 0x11
let ib_user_verbs_cmd_create_cq = 0x12
let ib_user_verbs_cmd_destroy_cq = 0x14
let ib_user_verbs_cmd_create_qp = 0x18
let ib_user_verbs_cmd_modify_qp = 0x1a
let ib_user_verbs_cmd_destroy_qp = 0x1b
let ibv_qps_init = 1
let ibv_qps_rtr = 2
let ibv_qps_rts = 3
let ibv_qp_state = 1
let ibv_qp_access_flags = 8
let ibv_qp_pkey_index = 0x10
let ibv_qp_port = 0x20
let ibv_qp_av = 0x80
let ibv_qp_path_mtu = 0x100
let ibv_qp_timeout = 0x200
let ibv_qp_retry_cnt = 0x400
let ibv_qp_rnr_retry = 0x800
let ibv_qp_rq_psn = 0x1000
let ibv_qp_max_qp_rd_atomic = 0x2000
let ibv_qp_min_rnr_timer = 0x8000
let ibv_qp_sq_psn = 0x10000
let ibv_qp_max_dest_rd_atomic = 0x20000
let ibv_qp_dest_qpn = 0x100000
let ibv_mtu_256 = 1
let ibv_port_active = 4
let ibv_link_layer_infiniband = 1
let ibv_link_layer_ethernet = 2
let ibv_event_cq_err = 0
let ibv_event_qp_fatal = 1
let ibv_event_qp_req_err = 2
let ibv_event_qp_access_err = 3
let ibv_event_device_fatal = 8
let ibv_event_port_active = 9
let ibv_event_port_err = 10

(* Structures: each field is (byte offset, bytes). *)

module Attr = struct
  let sizeof = 16
  let attr_id = (0, 2)
  let len = (2, 2)
  let flags = (4, 2)
  let attr_data = (6, 2)
  let attr_data__enum_data = (6, 2)
  let attr_data__enum_data__elem_id = (6, 1)
  let attr_data__enum_data__reserved = (7, 1)
  let attr_data__reserved = (6, 2)
  let data = (8, 8)
  let data_s64 = (8, 8)
end

module Ioctl_hdr = struct
  let sizeof = 24
  let length = (0, 2)
  let object_id = (2, 2)
  let method_id = (4, 2)
  let num_attrs = (6, 2)
  let reserved1 = (8, 8)
  let driver_id = (16, 4)
  let reserved2 = (20, 4)
  let attrs = (24, 0)
end

module Get_context = struct
  let sizeof = 8
  let response = (0, 8)
  let driver_data = (8, 0)
end

module Get_context_resp = struct
  let sizeof = 8
  let async_fd = (0, 4)
  let num_comp_vectors = (4, 4)
  let driver_data = (8, 0)
end

module Query_device = struct
  let sizeof = 8
  let response = (0, 8)
  let driver_data = (8, 0)
end

module Query_device_resp = struct
  let sizeof = 176
  let fw_ver = (0, 8)
  let node_guid = (8, 8)
  let sys_image_guid = (16, 8)
  let max_mr_size = (24, 8)
  let page_size_cap = (32, 8)
  let vendor_id = (40, 4)
  let vendor_part_id = (44, 4)
  let hw_ver = (48, 4)
  let max_qp = (52, 4)
  let max_qp_wr = (56, 4)
  let device_cap_flags = (60, 4)
  let max_sge = (64, 4)
  let max_sge_rd = (68, 4)
  let max_cq = (72, 4)
  let max_cqe = (76, 4)
  let max_mr = (80, 4)
  let max_pd = (84, 4)
  let max_qp_rd_atom = (88, 4)
  let max_ee_rd_atom = (92, 4)
  let max_res_rd_atom = (96, 4)
  let max_qp_init_rd_atom = (100, 4)
  let max_ee_init_rd_atom = (104, 4)
  let atomic_cap = (108, 4)
  let max_ee = (112, 4)
  let max_rdd = (116, 4)
  let max_mw = (120, 4)
  let max_raw_ipv6_qp = (124, 4)
  let max_raw_ethy_qp = (128, 4)
  let max_mcast_grp = (132, 4)
  let max_mcast_qp_attach = (136, 4)
  let max_total_mcast_qp_attach = (140, 4)
  let max_ah = (144, 4)
  let max_fmr = (148, 4)
  let max_map_per_fmr = (152, 4)
  let max_srq = (156, 4)
  let max_srq_wr = (160, 4)
  let max_srq_sge = (164, 4)
  let max_pkeys = (168, 2)
  let local_ca_ack_delay = (170, 1)
  let phys_port_cnt = (171, 1)
  let reserved = (172, 4)
end

module Query_port = struct
  let sizeof = 16
  let response = (0, 8)
  let port_num = (8, 1)
  let reserved = (9, 7)
  let driver_data = (16, 0)
end

module Query_port_resp = struct
  let sizeof = 40
  let port_cap_flags = (0, 4)
  let max_msg_sz = (4, 4)
  let bad_pkey_cntr = (8, 4)
  let qkey_viol_cntr = (12, 4)
  let gid_tbl_len = (16, 4)
  let pkey_tbl_len = (20, 2)
  let lid = (22, 2)
  let sm_lid = (24, 2)
  let state = (26, 1)
  let max_mtu = (27, 1)
  let active_mtu = (28, 1)
  let lmc = (29, 1)
  let max_vl_num = (30, 1)
  let sm_sl = (31, 1)
  let subnet_timeout = (32, 1)
  let init_type_reply = (33, 1)
  let active_width = (34, 1)
  let active_speed = (35, 1)
  let phys_state = (36, 1)
  let link_layer = (37, 1)
  let flags = (38, 1)
  let reserved = (39, 1)
end

module Alloc_pd = struct
  let sizeof = 8
  let response = (0, 8)
  let driver_data = (8, 0)
end

module Alloc_pd_resp = struct
  let sizeof = 4
  let pd_handle = (0, 4)
  let driver_data = (4, 0)
end

module Reg_mr = struct
  let sizeof = 40
  let response = (0, 8)
  let start = (8, 8)
  let length = (16, 8)
  let hca_va = (24, 8)
  let pd_handle = (32, 4)
  let access_flags = (36, 4)
  let driver_data = (40, 0)
end

module Reg_mr_resp = struct
  let sizeof = 12
  let mr_handle = (0, 4)
  let lkey = (4, 4)
  let rkey = (8, 4)
  let driver_data = (12, 0)
end

module Dereg_mr = struct
  let sizeof = 4
  let mr_handle = (0, 4)
end

module Create_comp_channel = struct
  let sizeof = 8
  let response = (0, 8)
end

module Create_comp_channel_resp = struct
  let sizeof = 4
  let fd = (0, 4)
end

module Create_cq = struct
  let sizeof = 32
  let response = (0, 8)
  let user_handle = (8, 8)
  let cqe = (16, 4)
  let comp_vector = (20, 4)
  let comp_channel = (24, 4)
  let reserved = (28, 4)
  let driver_data = (32, 0)
end

module Create_cq_resp = struct
  let sizeof = 8
  let cq_handle = (0, 4)
  let cqe = (4, 4)
  let driver_data = (8, 0)
end

module Destroy_cq = struct
  let sizeof = 16
  let response = (0, 8)
  let cq_handle = (8, 4)
  let reserved = (12, 4)
end

module Destroy_cq_resp = struct
  let sizeof = 8
  let comp_events_reported = (0, 4)
  let async_events_reported = (4, 4)
end

module Create_qp = struct
  let sizeof = 56
  let response = (0, 8)
  let user_handle = (8, 8)
  let pd_handle = (16, 4)
  let send_cq_handle = (20, 4)
  let recv_cq_handle = (24, 4)
  let srq_handle = (28, 4)
  let max_send_wr = (32, 4)
  let max_recv_wr = (36, 4)
  let max_send_sge = (40, 4)
  let max_recv_sge = (44, 4)
  let max_inline_data = (48, 4)
  let sq_sig_all = (52, 1)
  let qp_type = (53, 1)
  let is_srq = (54, 1)
  let reserved = (55, 1)
  let driver_data = (56, 0)
end

module Create_qp_resp = struct
  let sizeof = 32
  let qp_handle = (0, 4)
  let qpn = (4, 4)
  let max_send_wr = (8, 4)
  let max_recv_wr = (12, 4)
  let max_send_sge = (16, 4)
  let max_recv_sge = (20, 4)
  let max_inline_data = (24, 4)
  let reserved = (28, 4)
  let driver_data = (32, 0)
end

module Modify_qp = struct
  let sizeof = 112
  let dest = (0, 32)
  let dest__dgid = (0, 16)
  let dest__flow_label = (16, 4)
  let dest__dlid = (20, 2)
  let dest__reserved = (22, 2)
  let dest__sgid_index = (24, 1)
  let dest__hop_limit = (25, 1)
  let dest__traffic_class = (26, 1)
  let dest__sl = (27, 1)
  let dest__src_path_bits = (28, 1)
  let dest__static_rate = (29, 1)
  let dest__is_global = (30, 1)
  let dest__port_num = (31, 1)
  let alt_dest = (32, 32)
  let alt_dest__dgid = (32, 16)
  let alt_dest__flow_label = (48, 4)
  let alt_dest__dlid = (52, 2)
  let alt_dest__reserved = (54, 2)
  let alt_dest__sgid_index = (56, 1)
  let alt_dest__hop_limit = (57, 1)
  let alt_dest__traffic_class = (58, 1)
  let alt_dest__sl = (59, 1)
  let alt_dest__src_path_bits = (60, 1)
  let alt_dest__static_rate = (61, 1)
  let alt_dest__is_global = (62, 1)
  let alt_dest__port_num = (63, 1)
  let qp_handle = (64, 4)
  let attr_mask = (68, 4)
  let qkey = (72, 4)
  let rq_psn = (76, 4)
  let sq_psn = (80, 4)
  let dest_qp_num = (84, 4)
  let qp_access_flags = (88, 4)
  let pkey_index = (92, 2)
  let alt_pkey_index = (94, 2)
  let qp_state = (96, 1)
  let cur_qp_state = (97, 1)
  let path_mtu = (98, 1)
  let path_mig_state = (99, 1)
  let en_sqd_async_notify = (100, 1)
  let max_rd_atomic = (101, 1)
  let max_dest_rd_atomic = (102, 1)
  let min_rnr_timer = (103, 1)
  let port_num = (104, 1)
  let timeout = (105, 1)
  let retry_cnt = (106, 1)
  let rnr_retry = (107, 1)
  let alt_port_num = (108, 1)
  let alt_timeout = (109, 1)
  let reserved = (110, 2)
  let driver_data = (112, 0)
end

module Destroy_qp = struct
  let sizeof = 16
  let response = (0, 8)
  let qp_handle = (8, 4)
  let reserved = (12, 4)
end

module Destroy_qp_resp = struct
  let sizeof = 4
  let events_reported = (0, 4)
end

module Async_event_desc = struct
  let sizeof = 16
  let element = (0, 8)
  let event_type = (8, 4)
  let reserved = (12, 4)
end

module Comp_event_desc = struct
  let sizeof = 8
  let cq_handle = (0, 8)
end
