(lang dune 3.21)

(name norn)

(source
 (github raven-ml/raven))

(authors "Thibaut Mattio <thibaut.mattio@gmail.com>")

(maintainers "Thibaut Mattio <thibaut.mattio@gmail.com>")

(license ISC)

(documentation
 "https://github.com/raven-ml/raven/tree/main/contrib/norn")

(bug_reports "https://github.com/raven-ml/raven/issues")

(using mdx 0.4)

(version 1.0.0~alpha3)

(implicit_transitive_deps false)

(generate_opam_files true)

(package
 (name norn)
 (synopsis "MCMC sampling for OCaml")
 (description
  "Markov chain Monte Carlo samplers with automatic gradients via Rune. Hamiltonian Monte Carlo with dual-averaging step-size adaptation.")
 (depends
  (ocaml
   (>= 5.2.0))
  dune
  (nx
   (>= 1.0.0~alpha3))
  (rune
   (>= 1.0.0~alpha3))
  (windtrap :with-test)
  (mdx :with-test)
  (thumper :with-test))
 (tags
  (mcmc sampling bayesian machine-learning)))
