(* Generated by gen.py; do not edit. The inputs and the command that
   regenerates this file are in gen.py; their digests are in pins.json. *)

(* Constants *)

let hwrm_ver_get = 0
let hwrm_func_reset = 0x11
let hwrm_func_qcaps = 0x15
let hwrm_func_drv_rgtr = 0x1d
let hwrm_func_drv_unrgtr = 0x1a
let hwrm_func_qcfg = 0x16
let hwrm_func_backing_store_qcaps_v2 = 0x1a8
let hwrm_func_backing_store_cfg_v2 = 0x1a3
let hwrm_ring_alloc = 0x50
let hwrm_stat_ctx_alloc = 0xb0
let hwrm_vnic_alloc = 0x40
let hwrm_vnic_cfg = 0x42
let hwrm_cfa_l2_filter_alloc = 0x90
let cmdq_base_opcode_initialize_fw = 0x80
let cmdq_base_opcode_add_gid = 0x11
let cmdq_base_opcode_create_cq = 9
let cmdq_base_opcode_create_qp = 1
let cmdq_base_opcode_modify_qp = 3
let cmdq_base_opcode_register_mr = 0xf
let cmdq_base_opcode_deregister_mr = 0x10
let hwrm_max_req_len = 0x80
let bnxt_hwrm_target = 0xffff
let bnxt_hwrm_no_cmpl_ring = (-1)
let func_backing_store_cfg_v2_req_flags_bs_cfg_all_done = 2
let ring_alloc_req_ring_type_nq = 5
let ring_alloc_req_ring_type_l2_cmpl = 0
let ring_alloc_req_ring_type_rx = 2
let ring_alloc_req_int_mode_msix = 2
let ring_alloc_req_enables_nq_ring_id_valid = 0x80
let ring_alloc_req_enables_rx_buf_size_valid = 0x100
let vnic_cfg_req_enables_mru = 0x10
let vnic_cfg_req_enables_default_rx_ring_id = 0x20
let vnic_cfg_req_enables_default_cmpl_ring_id = 0x40
let cfa_l2_filter_alloc_req_flags_path_rx = 1
let cfa_l2_filter_alloc_req_enables_l2_addr = 1
let cfa_l2_filter_alloc_req_enables_l2_addr_mask = 2
let cfa_l2_filter_alloc_req_enables_dst_id = 0x8000
let dbc_dbc_index_mask = 0xffffff
let dbc_dbc_xid_mask = 0xfffff
let dbc_dbc_path_roce = 0
let dbc_dbc_type_sq = 0
let dbc_dbc_type_rq = 0x10000000
let dbc_dbc_type_cq = 0x40000000
let dbc_dbc_type_nq_arm = 0xb0000000
let bnxt_qplib_dbr_valid = 0x4000000
let bnxt_qplib_dbr_epoch_shift = 0x18
let rcfw_comm_base_offset = 0x600
let rcfw_pf_vf_comm_prod_offset = 0xc
let rcfw_comm_trig_offset = 0x100
let rcfw_cmdq_trig_val = 1
let firmware_first_flag = 0x1f
let cmdq_init_cmdq_size_sft = 2
let cmdq_initialize_fw_flags_hw_requester_retx_supported = 2
let creq_base_v = 1
let creq_base_type_qp_event = 0x38
let creq_qp_event_event_qp_error_notification = 0xc0
let ptu_pte_valid = 1
let ptu_pte_last = 2
let ptu_pte_next_to_last = 4
let cmdq_create_qp_type_rc = 2
let cmdq_modify_qp_qp_type_rc = 2
let cmdq_modify_qp_network_type_rocev2_ipv4 = 0x80
let cmdq_modify_qp_path_mtu_mtu_4096 = 0x40
let cmdq_modify_qp_new_state_init = 1
let cmdq_modify_qp_new_state_rtr = 2
let cmdq_modify_qp_new_state_rts = 3
let cmdq_modify_qp_access_local_write = 1
let cmdq_modify_qp_access_remote_write = 2
let cmdq_modify_qp_modify_mask_state = 1
let cmdq_modify_qp_modify_mask_access = 4
let cmdq_modify_qp_modify_mask_pkey = 8
let cmdq_modify_qp_modify_mask_dgid = 0x20
let cmdq_modify_qp_modify_mask_sgid_index = 0x80
let cmdq_modify_qp_modify_mask_hop_limit = 0x100
let cmdq_modify_qp_modify_mask_dest_mac = 0x400
let cmdq_modify_qp_modify_mask_path_mtu = 0x1000
let cmdq_modify_qp_modify_mask_rq_psn = 0x10000
let cmdq_modify_qp_modify_mask_min_rnr_timer = 0x40000
let cmdq_modify_qp_modify_mask_max_dest_rd_atomic = 0x100000
let cmdq_modify_qp_modify_mask_dest_qp_id = 0x4000000
let cmdq_modify_qp_modify_mask_timeout = 0x2000
let cmdq_modify_qp_modify_mask_retry_cnt = 0x4000
let cmdq_modify_qp_modify_mask_rnr_retry = 0x8000
let cmdq_modify_qp_modify_mask_max_rd_atomic = 0x20000
let cmdq_modify_qp_modify_mask_sq_psn = 0x80000
let cmdq_register_mr_flags_alloc_mr = 1
let cmdq_register_mr_lvl_sft = 0
let cmdq_register_mr_log2_pg_size_sft = 2
let cmdq_register_mr_access_local_write = 1
let cmdq_register_mr_access_remote_write = 4
let sq_base_wqe_type_send = 0
let sq_send_flags_signal_comp = 1
let rq_wqe_wqe_type_rcv = 0x80
let sq_msn_search_start_idx_sft = 0x30
let sq_msn_search_next_psn_sft = 0x18
let cq_base_toggle = 1

(* Structs: each field is (byte offset, bytes), an array's (offset, bytes
   of an element, elements). *)

module Hwrm_cmd_hdr = struct
  let sizeof = 16
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
end

module Hwrm_resp_hdr = struct
  let sizeof = 8
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
end

module Hwrm_ver_get_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let hwrm_intf_maj = (0x10, 1)
  let hwrm_intf_min = (0x11, 1)
  let hwrm_intf_upd = (0x12, 1)
  let unused_0 = (0x13, 1, 5)
end

module Hwrm_ver_get_output = struct
  let sizeof = 176
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let hwrm_intf_maj_8b = (8, 1)
  let hwrm_intf_min_8b = (9, 1)
  let hwrm_intf_upd_8b = (0xa, 1)
  let hwrm_intf_rsvd_8b = (0xb, 1)
  let hwrm_fw_maj_8b = (0xc, 1)
  let hwrm_fw_min_8b = (0xd, 1)
  let hwrm_fw_bld_8b = (0xe, 1)
  let hwrm_fw_rsvd_8b = (0xf, 1)
  let mgmt_fw_maj_8b = (0x10, 1)
  let mgmt_fw_min_8b = (0x11, 1)
  let mgmt_fw_bld_8b = (0x12, 1)
  let mgmt_fw_rsvd_8b = (0x13, 1)
  let netctrl_fw_maj_8b = (0x14, 1)
  let netctrl_fw_min_8b = (0x15, 1)
  let netctrl_fw_bld_8b = (0x16, 1)
  let netctrl_fw_rsvd_8b = (0x17, 1)
  let dev_caps_cfg = (0x18, 4)
  let roce_fw_maj_8b = (0x1c, 1)
  let roce_fw_min_8b = (0x1d, 1)
  let roce_fw_bld_8b = (0x1e, 1)
  let roce_fw_rsvd_8b = (0x1f, 1)
  let hwrm_fw_name = (0x20, 1, 0x10)
  let mgmt_fw_name = (0x30, 1, 0x10)
  let netctrl_fw_name = (0x40, 1, 0x10)
  let active_pkg_name = (0x50, 1, 0x10)
  let roce_fw_name = (0x60, 1, 0x10)
  let chip_num = (0x70, 2)
  let chip_rev = (0x72, 1)
  let chip_metal = (0x73, 1)
  let chip_bond_id = (0x74, 1)
  let chip_platform_type = (0x75, 1)
  let max_req_win_len = (0x76, 2)
  let max_resp_len = (0x78, 2)
  let def_req_timeout = (0x7a, 2)
  let flags = (0x7c, 1)
  let unused_0 = (0x7d, 1, 2)
  let always_1 = (0x7f, 1)
  let hwrm_intf_major = (0x80, 2)
  let hwrm_intf_minor = (0x82, 2)
  let hwrm_intf_build = (0x84, 2)
  let hwrm_intf_patch = (0x86, 2)
  let hwrm_fw_major = (0x88, 2)
  let hwrm_fw_minor = (0x8a, 2)
  let hwrm_fw_build = (0x8c, 2)
  let hwrm_fw_patch = (0x8e, 2)
  let mgmt_fw_major = (0x90, 2)
  let mgmt_fw_minor = (0x92, 2)
  let mgmt_fw_build = (0x94, 2)
  let mgmt_fw_patch = (0x96, 2)
  let netctrl_fw_major = (0x98, 2)
  let netctrl_fw_minor = (0x9a, 2)
  let netctrl_fw_build = (0x9c, 2)
  let netctrl_fw_patch = (0x9e, 2)
  let roce_fw_major = (0xa0, 2)
  let roce_fw_minor = (0xa2, 2)
  let roce_fw_build = (0xa4, 2)
  let roce_fw_patch = (0xa6, 2)
  let max_ext_req_len = (0xa8, 2)
  let max_req_timeout = (0xaa, 2)
  let unused_1 = (0xac, 1, 3)
  let valid = (0xaf, 1)
end

module Hwrm_func_reset_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let enables = (0x10, 4)
  let vf_id = (0x14, 2)
  let func_reset_level = (0x16, 1)
  let unused_0 = (0x17, 1)
end

module Hwrm_func_reset_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let unused_0 = (8, 1, 7)
  let valid = (0xf, 1)
end

module Hwrm_func_qcaps_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let fid = (0x10, 2)
  let unused_0 = (0x12, 1, 6)
end

module Hwrm_func_qcaps_output = struct
  let sizeof = 144
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let fid = (8, 2)
  let port_id = (0xa, 2)
  let flags = (0xc, 4)
  let mac_address = (0x10, 1, 6)
  let max_rsscos_ctx = (0x16, 2)
  let max_cmpl_rings = (0x18, 2)
  let max_tx_rings = (0x1a, 2)
  let max_rx_rings = (0x1c, 2)
  let max_l2_ctxs = (0x1e, 2)
  let max_vnics = (0x20, 2)
  let first_vf_id = (0x22, 2)
  let max_vfs = (0x24, 2)
  let max_stat_ctx = (0x26, 2)
  let max_encap_records = (0x28, 4)
  let max_decap_records = (0x2c, 4)
  let max_tx_em_flows = (0x30, 4)
  let max_tx_wm_flows = (0x34, 4)
  let max_rx_em_flows = (0x38, 4)
  let max_rx_wm_flows = (0x3c, 4)
  let max_mcast_filters = (0x40, 4)
  let max_flow_id = (0x44, 4)
  let max_hw_ring_grps = (0x48, 4)
  let max_sp_tx_rings = (0x4c, 2)
  let max_msix_vfs = (0x4e, 2)
  let flags_ext = (0x50, 4)
  let max_schqs = (0x54, 1)
  let mpc_chnls_cap = (0x55, 1)
  let max_key_ctxs_alloc = (0x56, 2)
  let flags_ext2 = (0x58, 4)
  let tunnel_disable_flag = (0x5c, 2)
  let xid_partition_cap = (0x5e, 2)
  let device_serial_number = (0x60, 1, 8)
  let ctxs_per_partition = (0x68, 2)
  let max_tso_segs = (0x6a, 2)
  let roce_vf_max_av = (0x6c, 4)
  let roce_vf_max_cq = (0x70, 4)
  let roce_vf_max_mrw = (0x74, 4)
  let roce_vf_max_qp = (0x78, 4)
  let roce_vf_max_srq = (0x7c, 4)
  let roce_vf_max_gid = (0x80, 4)
  let flags_ext3 = (0x84, 4)
  let max_roce_vfs = (0x88, 2)
  let max_crypto_rx_flow_filters = (0x8a, 2)
  let unused_3 = (0x8c, 1, 3)
  let valid = (0x8f, 1)
end

module Hwrm_func_drv_rgtr_input = struct
  let sizeof = 112
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let flags = (0x10, 4)
  let enables = (0x14, 4)
  let os_type = (0x18, 2)
  let ver_maj_8b = (0x1a, 1)
  let ver_min_8b = (0x1b, 1)
  let ver_upd_8b = (0x1c, 1)
  let unused_0 = (0x1d, 1, 3)
  let timestamp = (0x20, 4)
  let unused_1 = (0x24, 1, 4)
  let vf_req_fwd = (0x28, 4, 8)
  let async_event_fwd = (0x48, 4, 8)
  let ver_maj = (0x68, 2)
  let ver_min = (0x6a, 2)
  let ver_upd = (0x6c, 2)
  let ver_patch = (0x6e, 2)
end

module Hwrm_func_drv_rgtr_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let flags = (8, 4)
  let unused_0 = (0xc, 1, 3)
  let valid = (0xf, 1)
end

module Hwrm_func_drv_unrgtr_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let flags = (0x10, 4)
  let unused_0 = (0x14, 1, 4)
end

module Hwrm_func_drv_unrgtr_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let unused_0 = (8, 1, 7)
  let valid = (0xf, 1)
end

module Hwrm_func_qcfg_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let fid = (0x10, 2)
  let unused_0 = (0x12, 1, 6)
end

module Hwrm_func_qcfg_output = struct
  let sizeof = 176
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let fid = (8, 2)
  let port_id = (0xa, 2)
  let vlan = (0xc, 2)
  let flags = (0xe, 2)
  let mac_address = (0x10, 1, 6)
  let pci_id = (0x16, 2)
  let alloc_rsscos_ctx = (0x18, 2)
  let alloc_cmpl_rings = (0x1a, 2)
  let alloc_tx_rings = (0x1c, 2)
  let alloc_rx_rings = (0x1e, 2)
  let alloc_l2_ctx = (0x20, 2)
  let alloc_vnics = (0x22, 2)
  let admin_mtu = (0x24, 2)
  let mru = (0x26, 2)
  let stat_ctx_id = (0x28, 2)
  let port_partition_type = (0x2a, 1)
  let port_pf_cnt = (0x2b, 1)
  let dflt_vnic_id = (0x2c, 2)
  let max_mtu_configured = (0x2e, 2)
  let min_bw = (0x30, 4)
  let max_bw = (0x34, 4)
  let evb_mode = (0x38, 1)
  let options = (0x39, 1)
  let alloc_vfs = (0x3a, 2)
  let alloc_mcast_filters = (0x3c, 4)
  let alloc_hw_ring_grps = (0x40, 4)
  let alloc_sp_tx_rings = (0x44, 2)
  let alloc_stat_ctx = (0x46, 2)
  let alloc_msix = (0x48, 2)
  let registered_vfs = (0x4a, 2)
  let l2_doorbell_bar_size_kb = (0x4c, 2)
  let active_endpoints = (0x4e, 1)
  let always_1 = (0x4f, 1)
  let reset_addr_poll = (0x50, 4)
  let legacy_l2_db_size_kb = (0x54, 2)
  let svif_info = (0x56, 2)
  let mpc_chnls = (0x58, 1)
  let db_page_size = (0x59, 1)
  let roce_vnic_id = (0x5a, 2)
  let partition_min_bw = (0x5c, 4)
  let partition_max_bw = (0x60, 4)
  let host_mtu = (0x64, 2)
  let flags2 = (0x66, 2)
  let stag_vid = (0x68, 2)
  let port_kdnet_mode = (0x6a, 1)
  let kdnet_pcie_function = (0x6b, 1)
  let port_kdnet_fid = (0x6c, 2)
  let unused_5 = (0x6e, 1)
  let roce_bidi_opt_mode = (0x6f, 1)
  let num_ktls_tx_key_ctxs = (0x70, 4)
  let num_ktls_rx_key_ctxs = (0x74, 4)
  let lag_id = (0x78, 1)
  let parif = (0x79, 1)
  let fw_lag_id = (0x7a, 1)
  let unused_6 = (0x7b, 1)
  let num_quic_tx_key_ctxs = (0x7c, 4)
  let num_quic_rx_key_ctxs = (0x80, 4)
  let roce_max_av_per_vf = (0x84, 4)
  let roce_max_cq_per_vf = (0x88, 4)
  let roce_max_mrw_per_vf = (0x8c, 4)
  let roce_max_qp_per_vf = (0x90, 4)
  let roce_max_srq_per_vf = (0x94, 4)
  let roce_max_gid_per_vf = (0x98, 4)
  let xid_partition_cfg = (0x9c, 2)
  let mirror_vnic_id = (0x9e, 2)
  let max_link_width = (0xa0, 1)
  let max_link_speed = (0xa1, 1)
  let negotiated_link_width = (0xa2, 1)
  let negotiated_link_speed = (0xa3, 1)
  let unused_7 = (0xa4, 1, 2)
  let pcie_compliance = (0xa6, 1)
  let unused_8 = (0xa7, 1)
  let l2_db_multi_page_size_kb = (0xa8, 2)
  let unused_9 = (0xaa, 1, 5)
  let valid = (0xaf, 1)
end

module Hwrm_func_backing_store_qcaps_v2_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let type_ = (0x10, 2)
  let rsvd = (0x12, 1, 6)
end

module Hwrm_func_backing_store_qcaps_v2_output = struct
  let sizeof = 56
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let type_ = (8, 2)
  let entry_size = (0xa, 2)
  let flags = (0xc, 4)
  let instance_bit_map = (0x10, 4)
  let ctx_init_value = (0x14, 1)
  let ctx_init_offset = (0x15, 1)
  let entry_multiple = (0x16, 1)
  let rsvd = (0x17, 1)
  let max_num_entries = (0x18, 4)
  let min_num_entries = (0x1c, 4)
  let next_valid_type = (0x20, 2)
  let subtype_valid_cnt = (0x22, 1)
  let exact_cnt_bit_map = (0x23, 1)
  let split_entry_0 = (0x24, 4)
  let split_entry_1 = (0x28, 4)
  let split_entry_2 = (0x2c, 4)
  let split_entry_3 = (0x30, 4)
  let max_instance_count = (0x34, 2)
  let rsvd3 = (0x36, 1)
  let valid = (0x37, 1)
end

module Hwrm_func_backing_store_cfg_v2_input = struct
  let sizeof = 64
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let type_ = (0x10, 2)
  let instance = (0x12, 2)
  let flags = (0x14, 4)
  let page_dir = (0x18, 8)
  let num_entries = (0x20, 4)
  let entry_size = (0x24, 2)
  let page_size_pbl_level = (0x26, 1)
  let subtype_valid_cnt = (0x27, 1)
  let split_entry_0 = (0x28, 4)
  let split_entry_1 = (0x2c, 4)
  let split_entry_2 = (0x30, 4)
  let split_entry_3 = (0x34, 4)
  let enables = (0x38, 4)
  let next_bs_offset = (0x3c, 4)
end

module Hwrm_func_backing_store_cfg_v2_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let rsvd0 = (8, 1, 7)
  let valid = (0xf, 1)
end

module Hwrm_ring_alloc_input = struct
  let sizeof = 96
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let enables = (0x10, 4)
  let ring_type = (0x14, 1)
  let cmpl_coal_cnt = (0x15, 1)
  let flags = (0x16, 2)
  let page_tbl_addr = (0x18, 8)
  let fbo = (0x20, 4)
  let page_size = (0x24, 1)
  let page_tbl_depth = (0x25, 1)
  let schq_id = (0x26, 2)
  let length = (0x28, 4)
  let logical_id = (0x2c, 2)
  let cmpl_ring_id = (0x2e, 2)
  let queue_id = (0x30, 2)
  let rx_buf_size = (0x32, 2)
  let rx_ring_id = (0x34, 2)
  let nq_ring_id = (0x36, 2)
  let ring_arb_cfg = (0x38, 2)
  let steering_tag = (0x3a, 2)
  let reserved3 = (0x3c, 4)
  let stat_ctx_id = (0x40, 4)
  let reserved4 = (0x44, 4)
  let max_bw = (0x48, 4)
  let int_mode = (0x4c, 1)
  let mpc_chnls_type = (0x4d, 1)
  let rx_rate_profile_sel = (0x4e, 1)
  let unused_4 = (0x4f, 1)
  let cq_handle = (0x50, 8)
  let dpi = (0x58, 2)
  let unused_5 = (0x5a, 2, 3)
end

module Hwrm_ring_alloc_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let ring_id = (8, 2)
  let logical_ring_id = (0xa, 2)
  let push_buffer_index = (0xc, 1)
  let unused_0 = (0xd, 1, 2)
  let valid = (0xf, 1)
end

module Hwrm_stat_ctx_alloc_input = struct
  let sizeof = 48
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let stats_dma_addr = (0x10, 8)
  let update_period_ms = (0x18, 4)
  let stat_ctx_flags = (0x1c, 1)
  let unused_0 = (0x1d, 1)
  let stats_dma_length = (0x1e, 2)
  let flags = (0x20, 2)
  let steering_tag = (0x22, 2)
  let stat_ctx_id = (0x24, 4)
  let alloc_seq_id = (0x28, 2)
  let unused_1 = (0x2a, 1, 6)
end

module Hwrm_stat_ctx_alloc_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let stat_ctx_id = (8, 4)
  let unused_0 = (0xc, 1, 3)
  let valid = (0xf, 1)
end

module Hwrm_vnic_alloc_input = struct
  let sizeof = 24
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let flags = (0x10, 4)
  let virtio_net_fid = (0x14, 2)
  let vnic_id = (0x16, 2)
end

module Hwrm_vnic_alloc_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let vnic_id = (8, 4)
  let unused_0 = (0xc, 1, 3)
  let valid = (0xf, 1)
end

module Hwrm_vnic_cfg_input = struct
  let sizeof = 48
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let flags = (0x10, 4)
  let enables = (0x14, 4)
  let vnic_id = (0x18, 2)
  let dflt_ring_grp = (0x1a, 2)
  let rss_rule = (0x1c, 2)
  let cos_rule = (0x1e, 2)
  let lb_rule = (0x20, 2)
  let mru = (0x22, 2)
  let default_rx_ring_id = (0x24, 2)
  let default_cmpl_ring_id = (0x26, 2)
  let queue_id = (0x28, 2)
  let rx_csum_v2_mode = (0x2a, 1)
  let l2_cqe_mode = (0x2b, 1)
  let raw_qp_id = (0x2c, 4)
end

module Hwrm_vnic_cfg_output = struct
  let sizeof = 16
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let unused_0 = (8, 1, 7)
  let valid = (0xf, 1)
end

module Hwrm_cfa_l2_filter_alloc_input = struct
  let sizeof = 96
  let req_type = (0, 2)
  let cmpl_ring = (2, 2)
  let seq_id = (4, 2)
  let target_id = (6, 2)
  let resp_addr = (8, 8)
  let flags = (0x10, 4)
  let enables = (0x14, 4)
  let l2_addr = (0x18, 1, 6)
  let num_vlans = (0x1e, 1)
  let t_num_vlans = (0x1f, 1)
  let l2_addr_mask = (0x20, 1, 6)
  let l2_ovlan = (0x26, 2)
  let l2_ovlan_mask = (0x28, 2)
  let l2_ivlan = (0x2a, 2)
  let l2_ivlan_mask = (0x2c, 2)
  let unused_1 = (0x2e, 1, 2)
  let t_l2_addr = (0x30, 1, 6)
  let unused_2 = (0x36, 1, 2)
  let t_l2_addr_mask = (0x38, 1, 6)
  let t_l2_ovlan = (0x3e, 2)
  let t_l2_ovlan_mask = (0x40, 2)
  let t_l2_ivlan = (0x42, 2)
  let t_l2_ivlan_mask = (0x44, 2)
  let src_type = (0x46, 1)
  let unused_3 = (0x47, 1)
  let src_id = (0x48, 4)
  let tunnel_type = (0x4c, 1)
  let unused_4 = (0x4d, 1)
  let dst_id = (0x4e, 2)
  let mirror_vnic_id = (0x50, 2)
  let pri_hint = (0x52, 1)
  let unused_5 = (0x53, 1)
  let unused_6 = (0x54, 4)
  let l2_filter_id_hint = (0x58, 8)
end

module Hwrm_cfa_l2_filter_alloc_output = struct
  let sizeof = 24
  let error_code = (0, 2)
  let req_type = (2, 2)
  let seq_id = (4, 2)
  let resp_len = (6, 2)
  let l2_filter_id = (8, 8)
  let flow_id = (0x10, 4)
  let unused_0 = (0x14, 1, 3)
  let valid = (0x17, 1)
end

module Cmdq_init = struct
  let sizeof = 16
  let cmdq_pbl = (0, 8)
  let cmdq_size_cmdq_lvl = (8, 2)
  let creq_ring_id = (0xa, 2)
  let prod_idx = (0xc, 4)
end

module Cmdq_base = struct
  let sizeof = 16
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
end

module Creq_base = struct
  let sizeof = 16
  let type_ = (0, 1)
  let reserved56 = (1, 1, 7)
  let v = (8, 1)
  let event = (9, 1)
  let reserved48 = (0xa, 1, 6)
end

module Cmdq_initialize_fw = struct
  let sizeof = 112
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let qpc_pg_size_qpc_lvl = (0x10, 1)
  let mrw_pg_size_mrw_lvl = (0x11, 1)
  let srq_pg_size_srq_lvl = (0x12, 1)
  let cq_pg_size_cq_lvl = (0x13, 1)
  let tqm_pg_size_tqm_lvl = (0x14, 1)
  let tim_pg_size_tim_lvl = (0x15, 1)
  let log2_dbr_pg_size = (0x16, 2)
  let qpc_page_dir = (0x18, 8)
  let mrw_page_dir = (0x20, 8)
  let srq_page_dir = (0x28, 8)
  let cq_page_dir = (0x30, 8)
  let tqm_page_dir = (0x38, 8)
  let tim_page_dir = (0x40, 8)
  let number_of_qp = (0x48, 4)
  let number_of_mrw = (0x4c, 4)
  let number_of_srq = (0x50, 4)
  let number_of_cq = (0x54, 4)
  let max_qp_per_vf = (0x58, 4)
  let max_mrw_per_vf = (0x5c, 4)
  let max_srq_per_vf = (0x60, 4)
  let max_cq_per_vf = (0x64, 4)
  let max_gid_per_vf = (0x68, 4)
  let stat_ctx_id = (0x6c, 4)
end

module Cmdq_add_gid = struct
  let sizeof = 48
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let gid = (0x10, 4, 4)
  let src_mac = (0x20, 2, 3)
  let vlan = (0x26, 2)
  let ipid = (0x28, 2)
  let stats_ctx = (0x2a, 2)
  let unused_0 = (0x2c, 4)
end

module Cmdq_create_cq = struct
  let sizeof = 64
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let cq_handle = (0x10, 8)
  let pg_size_lvl = (0x18, 4)
  let cq_fco_cnq_id = (0x1c, 4)
  let dpi = (0x20, 4)
  let cq_size = (0x24, 4)
  let pbl = (0x28, 8)
  let steering_tag = (0x30, 2)
  let reserved48 = (0x32, 1, 2)
  let coalescing = (0x34, 4)
  let reserved64 = (0x38, 8)
end

module Cmdq_create_qp = struct
  let sizeof = 104
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let qp_handle = (0x10, 8)
  let qp_flags = (0x18, 4)
  let type_ = (0x1c, 1)
  let sq_pg_size_sq_lvl = (0x1d, 1)
  let rq_pg_size_rq_lvl = (0x1e, 1)
  let unused_0 = (0x1f, 1)
  let dpi = (0x20, 4)
  let sq_size = (0x24, 4)
  let rq_size = (0x28, 4)
  let sq_fwo_sq_sge = (0x2c, 2)
  let rq_fwo_rq_sge = (0x2e, 2)
  let scq_cid = (0x30, 4)
  let rcq_cid = (0x34, 4)
  let srq_cid = (0x38, 4)
  let pd_id = (0x3c, 4)
  let sq_pbl = (0x40, 8)
  let rq_pbl = (0x48, 8)
  let irrq_addr = (0x50, 8)
  let orrq_addr = (0x58, 8)
  let request_xid = (0x60, 4)
  let steering_tag = (0x64, 2)
  let reserved16 = (0x66, 2)
end

module Cmdq_modify_qp = struct
  let sizeof = 144
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let qp_type = (7, 1)
  let resp_addr = (8, 8)
  let modify_mask = (0x10, 4)
  let qp_cid = (0x14, 4)
  let network_type_en_sqd_async_notify_new_state = (0x18, 1)
  let access = (0x19, 1)
  let pkey = (0x1a, 2)
  let qkey = (0x1c, 4)
  let dgid = (0x20, 4, 4)
  let flow_label = (0x30, 4)
  let sgid_index = (0x34, 2)
  let hop_limit = (0x36, 1)
  let traffic_class = (0x37, 1)
  let dest_mac = (0x38, 2, 3)
  let tos_dscp_tos_ecn = (0x3e, 1)
  let path_mtu_pingpong_push_enable = (0x3f, 1)
  let timeout = (0x40, 1)
  let retry_cnt = (0x41, 1)
  let rnr_retry = (0x42, 1)
  let min_rnr_timer = (0x43, 1)
  let rq_psn = (0x44, 4)
  let sq_psn = (0x48, 4)
  let max_rd_atomic = (0x4c, 1)
  let max_dest_rd_atomic = (0x4d, 1)
  let enable_cc = (0x4e, 2)
  let sq_size = (0x50, 4)
  let rq_size = (0x54, 4)
  let sq_sge = (0x58, 2)
  let rq_sge = (0x5a, 2)
  let max_inline_data = (0x5c, 4)
  let dest_qp_id = (0x60, 4)
  let pingpong_push_dpi = (0x64, 4)
  let src_mac = (0x68, 2, 3)
  let vlan_pcp_vlan_dei_vlan_id = (0x6e, 2)
  let irrq_addr = (0x70, 8)
  let orrq_addr = (0x78, 8)
  let ext_modify_mask = (0x80, 4)
  let ext_stats_ctx_id = (0x84, 4)
  let schq_id = (0x88, 2)
  let unused_0 = (0x8a, 2)
  let reserved32 = (0x8c, 4)
end

module Cmdq_register_mr = struct
  let sizeof = 56
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let log2_pg_size_lvl = (0x10, 1)
  let access = (0x11, 1)
  let log2_pbl_pg_size = (0x12, 2)
  let key = (0x14, 4)
  let pbl = (0x18, 8)
  let va = (0x20, 8)
  let mr_size = (0x28, 8)
  let steering_tag = (0x30, 2)
  let reserved48 = (0x32, 1, 6)
end

module Cmdq_deregister_mr = struct
  let sizeof = 24
  let opcode = (0, 1)
  let cmd_size = (1, 1)
  let flags = (2, 2)
  let cookie = (4, 2)
  let resp_size = (6, 1)
  let reserved8 = (7, 1)
  let resp_addr = (8, 8)
  let lkey = (0x10, 4)
  let unused_0 = (0x14, 4)
end

module Creq_initialize_fw_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let reserved32 = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let reserved48 = (0xa, 1, 6)
end

module Creq_add_gid_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let reserved48 = (0xa, 1, 6)
end

module Creq_create_cq_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let reserved48 = (0xa, 1, 6)
end

module Creq_create_qp_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let optimized_transmit_enabled = (0xa, 1)
  let reserved48 = (0xb, 1, 5)
end

module Creq_modify_qp_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let pingpong_push_state_index_enabled = (0xa, 1)
  let reserved8 = (0xb, 1)
  let lag_src_mac = (0xc, 4)
end

module Creq_register_mr_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let reserved48 = (0xa, 1, 6)
end

module Creq_deregister_mr_resp = struct
  let sizeof = 16
  let type_ = (0, 1)
  let status = (1, 1)
  let cookie = (2, 2)
  let xid = (4, 4)
  let v = (8, 1)
  let event = (9, 1)
  let reserved16 = (0xa, 2)
  let bound_windows = (0xc, 4)
end

module Sq_send_hdr = struct
  let sizeof = 32
  let wqe_type = (0, 1)
  let flags = (1, 1)
  let wqe_size = (2, 1)
  let reserved8_1 = (3, 1)
  let inv_key_or_imm_data = (4, 4)
  let length = (8, 4)
  let q_key = (0xc, 4)
  let dst_qp = (0x10, 4)
  let avid = (0x14, 4)
  let reserved32 = (0x18, 4)
  let timestamp = (0x1c, 4)
end

module Sq_sge = struct
  let sizeof = 16
  let va_or_pa = (0, 8)
  let l_key = (8, 4)
  let size = (0xc, 4)
end

module Rq_wqe_hdr = struct
  let sizeof = 32
  let wqe_type = (0, 1)
  let flags = (1, 1)
  let wqe_size = (2, 1)
  let reserved8 = (3, 1)
  let reserved32 = (4, 4)
  let wr_id = (8, 4, 2)
  let reserved128 = (0x10, 1, 0x10)
end

module Cq_base = struct
  let sizeof = 32
  let reserved64_1 = (0, 8)
  let reserved64_2 = (8, 8)
  let reserved64_3 = (0x10, 8)
  let cqe_type_toggle = (0x18, 1)
  let status = (0x19, 1)
  let reserved16 = (0x1a, 2)
  let opaque = (0x1c, 4)
end

module Sq_msn_search = struct
  let sizeof = 8
  let start_idx_next_psn_start_psn = (0, 8)
end
