(* Generated by generate_tables.py; do not edit by hand.
   Regenerate with: uv run packages/tolk/lib/runtime/amd/generate_tables.py *)

module V4_0_0 = struct
  let sdma_op_copy = 1
  let sdma_op_write = 2
  let sdma_op_indirect = 4
  let sdma_op_fence = 5
  let sdma_op_trap = 6
  let sdma_op_poll_regmem = 8
  let sdma_op_timestamp = 0xd
  let sdma_subop_copy_linear = 0
  let sdma_subop_timestamp_get_global = 2
  let sdma_pkt_copy_linear_header_sub_op x = (x land 0xff) lsl 8
  let sdma_pkt_copy_linear_count_count x = (x land 0x3fffff) lsl 0
  let sdma_pkt_indirect_header_vmid x = (x land 0xf) lsl 16
  let sdma_pkt_poll_regmem_header_func x = (x land 0x7) lsl 28
  let sdma_pkt_poll_regmem_header_mem_poll x = (x land 0x1) lsl 31
  let sdma_pkt_poll_regmem_dw5_interval x = (x land 0xffff) lsl 0
  let sdma_pkt_poll_regmem_dw5_retry_count x = (x land 0xfff) lsl 16
  let sdma_pkt_timestamp_get_header_sub_op x = (x land 0xff) lsl 8
  let sdma_pkt_trap_int_context_int_context x = (x land 0xfffffff) lsl 0
end

module V6_0_0 = struct
  let sdma_op_copy = 1
  let sdma_op_write = 2
  let sdma_op_indirect = 4
  let sdma_op_fence = 5
  let sdma_op_trap = 6
  let sdma_op_poll_regmem = 8
  let sdma_op_timestamp = 0xd
  let sdma_subop_copy_linear = 0
  let sdma_subop_timestamp_get_global = 2
  let sdma_pkt_copy_linear_header_sub_op x = (x land 0xff) lsl 8
  let sdma_pkt_copy_linear_count_count x = (x land 0x3fffffff) lsl 0
  let sdma_pkt_indirect_header_vmid x = (x land 0xf) lsl 16
  let sdma_pkt_poll_regmem_header_func x = (x land 0x7) lsl 28
  let sdma_pkt_poll_regmem_header_mem_poll x = (x land 0x1) lsl 31
  let sdma_pkt_poll_regmem_dw5_interval x = (x land 0xffff) lsl 0
  let sdma_pkt_poll_regmem_dw5_retry_count x = (x land 0xfff) lsl 16
  let sdma_pkt_timestamp_get_header_sub_op x = (x land 0xff) lsl 8
  let sdma_pkt_trap_int_context_int_context x = (x land 0xfffffff) lsl 0
  let sdma_pkt_fence_header_mtype x = (x land 0x7) lsl 16
end
