(* Generated by generate_tables.py; do not edit by hand.
   Regenerate with: uv run packages/tolk/lib/runtime/amd/generate_tables.py *)

(* Per-family register maps: name -> (offset, segment, fields as (lo, hi)). *)
let gc_9_4_3 = [
  ("regCOMPUTE_PGM_LO", (0xe0c, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_PGM_RSRC1", (0xe12, 0, [ ("vgprs", (0, 5)); ("sgprs", (6, 9)); ("priority", (10, 11)); ("float_mode", (12, 19)); ("priv", (20, 20)); ("dx10_clamp", (21, 21)); ("debug_mode", (22, 22)); ("ieee_mode", (23, 23)); ("bulky", (24, 24)); ("cdbg_user", (25, 25)); ("fp16_ovfl", (26, 26)) ]));
  ("regCOMPUTE_PGM_RSRC3", (0xe2d, 0, [ ("accum_offset", (0, 5)); ("trap_on_start", (10, 10)); ("trap_on_end", (11, 11)); ("tg_split", (16, 16)) ]));
  ("regCOMPUTE_TMPRING_SIZE", (0xe18, 0, [ ("waves", (0, 11)); ("wavesize", (12, 24)) ]));
  ("regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", (0xe10, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESTART_X", (0xe1b, 0, [ ("restart", (0, 31)) ]));
  ("regCOMPUTE_USER_DATA_0", (0xe40, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESOURCE_LIMITS", (0xe15, 0, [ ("waves_per_sh", (0, 9)); ("tg_per_cu", (12, 15)); ("lock_threshold", (16, 21)); ("simd_dest_cntl", (22, 22)); ("force_simd_dist", (23, 23)); ("cu_group_count", (24, 26)); ("simd_disable", (27, 30)) ]));
  ("regCOMPUTE_START_X", (0xe04, 0, [ ("start", (0, 31)) ]));
  ("regCOMPUTE_DISPATCH_INITIATOR", (0xe00, 0, [ ("compute_shader_en", (0, 0)); ("partial_tg_en", (1, 1)); ("force_start_at_000", (2, 2)); ("ordered_append_enbl", (3, 3)); ("ordered_append_mode", (4, 4)); ("use_thread_dimensions", (5, 5)); ("order_mode", (6, 6)); ("scalar_l1_inv_vol", (10, 10)); ("vector_l1_inv_vol", (11, 11)); ("reserved", (12, 12)); ("restore", (14, 14)) ]));
]

let gc_11_0_0 = [
  ("regCOMPUTE_PGM_LO", (0x1bac, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_PGM_RSRC1", (0x1bb2, 0, [ ("vgprs", (0, 5)); ("sgprs", (6, 9)); ("priority", (10, 11)); ("float_mode", (12, 19)); ("priv", (20, 20)); ("dx10_clamp", (21, 21)); ("ieee_mode", (23, 23)); ("bulky", (24, 24)); ("fp16_ovfl", (26, 26)); ("wgp_mode", (29, 29)); ("mem_ordered", (30, 30)); ("fwd_progress", (31, 31)) ]));
  ("regCOMPUTE_PGM_RSRC3", (0x1bc8, 0, [ ("shared_vgpr_cnt", (0, 3)); ("inst_pref_size", (4, 9)); ("trap_on_start", (10, 10)); ("trap_on_end", (11, 11)); ("image_op", (31, 31)) ]));
  ("regCOMPUTE_TMPRING_SIZE", (0x1bb8, 0, [ ("waves", (0, 11)); ("wavesize", (12, 26)) ]));
  ("regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", (0x1bb0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESTART_X", (0x1bbb, 0, [ ("restart", (0, 31)) ]));
  ("regCOMPUTE_USER_DATA_0", (0x1be0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESOURCE_LIMITS", (0x1bb5, 0, [ ("waves_per_sh", (0, 9)); ("tg_per_cu", (12, 15)); ("lock_threshold", (16, 21)); ("simd_dest_cntl", (22, 22)); ("force_simd_dist", (23, 23)); ("cu_group_count", (24, 26)) ]));
  ("regCOMPUTE_START_X", (0x1ba4, 0, [ ("start", (0, 31)) ]));
  ("regCOMPUTE_DISPATCH_INITIATOR", (0x1ba0, 0, [ ("compute_shader_en", (0, 0)); ("partial_tg_en", (1, 1)); ("force_start_at_000", (2, 2)); ("ordered_append_enbl", (3, 3)); ("ordered_append_mode", (4, 4)); ("use_thread_dimensions", (5, 5)); ("order_mode", (6, 6)); ("scalar_l1_inv_vol", (10, 10)); ("vector_l1_inv_vol", (11, 11)); ("reserved", (12, 12)); ("tunnel_enable", (13, 13)); ("restore", (14, 14)); ("cs_w32_en", (15, 15)); ("amp_shader_en", (16, 16)); ("disable_disp_prempt_en", (17, 17)) ]));
]

let gc_11_0_3 = [
  ("regCOMPUTE_PGM_LO", (0x1bac, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_PGM_RSRC1", (0x1bb2, 0, [ ("vgprs", (0, 5)); ("sgprs", (6, 9)); ("priority", (10, 11)); ("float_mode", (12, 19)); ("priv", (20, 20)); ("dx10_clamp", (21, 21)); ("debug_mode", (22, 22)); ("ieee_mode", (23, 23)); ("bulky", (24, 24)); ("cdbg_user", (25, 25)); ("fp16_ovfl", (26, 26)); ("wgp_mode", (29, 29)); ("mem_ordered", (30, 30)); ("fwd_progress", (31, 31)) ]));
  ("regCOMPUTE_PGM_RSRC3", (0x1bc8, 0, [ ("shared_vgpr_cnt", (0, 3)); ("inst_pref_size", (4, 9)); ("trap_on_start", (10, 10)); ("trap_on_end", (11, 11)); ("image_op", (31, 31)) ]));
  ("regCOMPUTE_TMPRING_SIZE", (0x1bb8, 0, [ ("waves", (0, 11)); ("wavesize", (12, 26)) ]));
  ("regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", (0x1bb0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESTART_X", (0x1bbb, 0, [ ("restart", (0, 31)) ]));
  ("regCOMPUTE_USER_DATA_0", (0x1be0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESOURCE_LIMITS", (0x1bb5, 0, [ ("waves_per_sh", (0, 9)); ("tg_per_cu", (12, 15)); ("lock_threshold", (16, 21)); ("simd_dest_cntl", (22, 22)); ("force_simd_dist", (23, 23)); ("cu_group_count", (24, 26)) ]));
  ("regCOMPUTE_START_X", (0x1ba4, 0, [ ("start", (0, 31)) ]));
  ("regCOMPUTE_DISPATCH_INITIATOR", (0x1ba0, 0, [ ("compute_shader_en", (0, 0)); ("partial_tg_en", (1, 1)); ("force_start_at_000", (2, 2)); ("ordered_append_enbl", (3, 3)); ("ordered_append_mode", (4, 4)); ("use_thread_dimensions", (5, 5)); ("order_mode", (6, 6)); ("scalar_l1_inv_vol", (10, 10)); ("vector_l1_inv_vol", (11, 11)); ("reserved", (12, 12)); ("tunnel_enable", (13, 13)); ("restore", (14, 14)); ("cs_w32_en", (15, 15)); ("amp_shader_en", (16, 16)); ("disable_disp_prempt_en", (17, 17)) ]));
]

let gc_11_5_0 = [
  ("regCOMPUTE_PGM_LO", (0x1bac, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_PGM_RSRC1", (0x1bb2, 0, [ ("vgprs", (0, 5)); ("sgprs", (6, 9)); ("priority", (10, 11)); ("float_mode", (12, 19)); ("priv", (20, 20)); ("dx10_clamp", (21, 21)); ("ieee_mode", (23, 23)); ("bulky", (24, 24)); ("fp16_ovfl", (26, 26)); ("wgp_mode", (29, 29)); ("mem_ordered", (30, 30)); ("fwd_progress", (31, 31)) ]));
  ("regCOMPUTE_PGM_RSRC3", (0x1bc8, 0, [ ("shared_vgpr_cnt", (0, 3)); ("inst_pref_size", (4, 9)); ("trap_on_start", (10, 10)); ("trap_on_end", (11, 11)); ("image_op", (31, 31)) ]));
  ("regCOMPUTE_TMPRING_SIZE", (0x1bb8, 0, [ ("waves", (0, 11)); ("wavesize", (12, 26)) ]));
  ("regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", (0x1bb0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESTART_X", (0x1bbb, 0, [ ("restart", (0, 31)) ]));
  ("regCOMPUTE_USER_DATA_0", (0x1be0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESOURCE_LIMITS", (0x1bb5, 0, [ ("waves_per_sh", (0, 9)); ("tg_per_cu", (12, 15)); ("lock_threshold", (16, 21)); ("simd_dest_cntl", (22, 22)); ("force_simd_dist", (23, 23)); ("cu_group_count", (24, 26)) ]));
  ("regCOMPUTE_START_X", (0x1ba4, 0, [ ("start", (0, 31)) ]));
  ("regCOMPUTE_DISPATCH_INITIATOR", (0x1ba0, 0, [ ("compute_shader_en", (0, 0)); ("partial_tg_en", (1, 1)); ("force_start_at_000", (2, 2)); ("ordered_append_enbl", (3, 3)); ("ordered_append_mode", (4, 4)); ("use_thread_dimensions", (5, 5)); ("order_mode", (6, 6)); ("scalar_l1_inv_vol", (10, 10)); ("vector_l1_inv_vol", (11, 11)); ("reserved", (12, 12)); ("tunnel_enable", (13, 13)); ("restore", (14, 14)); ("cs_w32_en", (15, 15)); ("amp_shader_en", (16, 16)); ("disable_disp_prempt_en", (17, 17)) ]));
]

let gc_12_0_0 = [
  ("regCOMPUTE_PGM_LO", (0x1bac, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_PGM_RSRC1", (0x1bb2, 0, [ ("vgprs", (0, 5)); ("sgprs", (6, 9)); ("priority", (10, 11)); ("float_mode", (12, 19)); ("priv", (20, 20)); ("wg_rr_en", (21, 21)); ("debug_mode", (22, 22)); ("disable_perf", (23, 23)); ("bulky", (24, 24)); ("cdbg_user", (25, 25)); ("fp16_ovfl", (26, 26)); ("wgp_mode", (29, 29)); ("mem_ordered", (30, 30)); ("fwd_progress", (31, 31)) ]));
  ("regCOMPUTE_PGM_RSRC3", (0x1bc8, 0, [ ("shared_vgpr_cnt", (0, 3)); ("inst_pref_size", (4, 11)); ("glg_en", (13, 13)); ("image_op", (31, 31)) ]));
  ("regCOMPUTE_TMPRING_SIZE", (0x1bb8, 0, [ ("waves", (0, 11)); ("wavesize", (12, 29)) ]));
  ("regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", (0x1bb0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESTART_X", (0x1bbb, 0, [ ("restart", (0, 31)) ]));
  ("regCOMPUTE_USER_DATA_0", (0x1be0, 0, [ ("data", (0, 31)) ]));
  ("regCOMPUTE_RESOURCE_LIMITS", (0x1bb5, 0, [ ("waves_per_sh", (0, 9)); ("tg_per_cu", (12, 15)); ("lock_threshold", (16, 21)); ("simd_dest_cntl", (22, 22)); ("force_simd_dist", (23, 23)); ("cu_group_count", (24, 26)) ]));
  ("regCOMPUTE_START_X", (0x1ba4, 0, [ ("start", (0, 31)) ]));
  ("regCOMPUTE_DISPATCH_INITIATOR", (0x1ba0, 0, [ ("compute_shader_en", (0, 0)); ("partial_tg_en", (1, 1)); ("force_start_at_000", (2, 2)); ("ordered_append_enbl", (3, 3)); ("ordered_append_mode", (4, 4)); ("use_thread_dimensions", (5, 5)); ("order_mode", (6, 6)); ("scalar_l1_inv_vol", (10, 10)); ("vector_l1_inv_vol", (11, 11)); ("ping_pong_en", (12, 12)); ("tunnel_enable", (13, 13)); ("restore", (14, 14)); ("cs_w32_en", (15, 15)); ("amp_shader_en", (16, 16)); ("disable_disp_prempt_en", (17, 17)); ("interleave_2d_en", (18, 18)); ("ttrace_queue_id", (29, 31)) ]));
]

let nbio_4_3_0 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x8e26, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x8e27, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let nbio_7_2_0 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x8e26, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x8e27, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let nbio_7_7_0 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x8e26, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x8e27, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let nbio_7_9_0 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x8e26, 8, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x8e27, 8, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let nbio_7_11_0 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x8e26, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x8e27, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let nbif_6_3_1 = [
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", (0x106, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF0_GPU_HDP_FLUSH_DONE", (0x107, 2, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_REQ", (0x8e26, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
  ("regBIF_BX_PF1_GPU_HDP_FLUSH_DONE", (0x8e27, 5, [ ("cp0", (0, 0)); ("cp1", (1, 1)); ("cp2", (2, 2)); ("cp3", (3, 3)); ("cp4", (4, 4)); ("cp5", (5, 5)); ("cp6", (6, 6)); ("cp7", (7, 7)); ("cp8", (8, 8)); ("cp9", (9, 9)); ("sdma0", (10, 10)); ("sdma1", (11, 11)); ("rsvd_eng0", (12, 12)); ("rsvd_eng1", (13, 13)); ("rsvd_eng2", (14, 14)); ("rsvd_eng3", (15, 15)); ("rsvd_eng4", (16, 16)); ("rsvd_eng5", (17, 17)); ("rsvd_eng6", (18, 18)); ("rsvd_eng7", (19, 19)); ("rsvd_eng8", (20, 20)); ("rsvd_eng9", (21, 21)); ("rsvd_eng10", (22, 22)); ("rsvd_eng11", (23, 23)); ("rsvd_eng12", (24, 24)); ("rsvd_eng13", (25, 25)); ("rsvd_eng14", (26, 26)); ("rsvd_eng15", (27, 27)); ("rsvd_eng16", (28, 28)); ("rsvd_eng17", (29, 29)); ("rsvd_eng18", (30, 30)); ("rsvd_eng19", (31, 31)) ]));
]

let families = [
  ("gc", (9, 4, 3), gc_9_4_3);
  ("gc", (11, 0, 0), gc_11_0_0);
  ("gc", (11, 0, 3), gc_11_0_3);
  ("gc", (11, 5, 0), gc_11_5_0);
  ("gc", (12, 0, 0), gc_12_0_0);
  ("nbio", (4, 3, 0), nbio_4_3_0);
  ("nbio", (7, 2, 0), nbio_7_2_0);
  ("nbio", (7, 7, 0), nbio_7_7_0);
  ("nbio", (7, 9, 0), nbio_7_9_0);
  ("nbio", (7, 11, 0), nbio_7_11_0);
  ("nbif", (6, 3, 1), nbif_6_3_1);
]

(* Address-space segment bases, per die instance. *)
module Navi = struct
  let gc_bases = [|
    [| 0x1260; 0xa000; 0x1c000; 0x2402c00; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
  |]

  let nbio_bases = [|
    [| 0; 0x14; 0xd20; 0x10400; 0x241b000; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
  |]
end

module Vega = struct
  let gc_bases = [|
    [| 0x2000; 0xa000; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0 |];
  |]

  let nbio_bases = [|
    [| 0; 0x14; 0xd20; 0x10400; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
    [| 0; 0; 0; 0; 0; 0; 0; 0; 0 |];
  |]
end

(* Hardware IP discovery ids. *)
let gc_hwid = 0xb
let sdma0_hwid = 0x2a
let nbif_hwid = 0x6c
let gc_hwip = 1
let sdma0_hwip = 3
let nbif_hwip = 0x1a
