(* Generated by generate_tables.py; do not edit by hand.
   Regenerate with: uv run packages/tolk/lib/runtime/amd/generate_tables.py *)

(* llvm_amdhsa_kernel_descriptor_t: byte offsets and total size. *)
let size = 0x40
let group_segment_fixed_size = 0
let private_segment_fixed_size = 4
let kernarg_size = 8
let kernel_code_entry_byte_offset = 0x10
let compute_pgm_rsrc3 = 0x2c
let compute_pgm_rsrc1 = 0x30
let compute_pgm_rsrc2 = 0x34
let kernel_code_properties = 0x38
