(* Generated by generate_tables.py; do not edit by hand.
   Regenerate with: uv run packages/tolk/lib/runtime/amd/generate_tables.py *)

(* hsa_kernel_dispatch_packet_t: byte offsets and total size. *)
module Kernel_dispatch_packet = struct
  let size = 0x40
  let header = 0
  let setup = 2
  let workgroup_size_x = 4
  let workgroup_size_y = 6
  let workgroup_size_z = 8
  let grid_size_x = 0xc
  let grid_size_y = 0x10
  let grid_size_z = 0x14
  let private_segment_size = 0x18
  let group_segment_size = 0x1c
  let kernel_object = 0x20
  let kernarg_address = 0x28
  let completion_signal = 0x38
end

(* amd_queue_t: byte offsets. *)
module Amd_queue = struct
  let size = 0x100
  let read_dispatch_id = 0x80
  let write_dispatch_id = 0x38
  let queue_properties = 0xb4
  let read_dispatch_id_field_base_byte_offset = 0x88
  let max_cu_id = 0x48
  let max_wave_id = 0x4c
  let scratch_resource_descriptor = 0x90
  let scratch_backing_memory_location = 0xa0
  let scratch_wave64_lane_byte_size = 0xb0
  let compute_tmpring_size = 0x8c
end

(* Scratch resource descriptors: fixed format and address swizzle bits. *)
module Scratch_resource = struct
  let gfx9_swizzle = 0x80000000
  let gfx9_format = 0xea4fac
  let gfx11_swizzle = 0x40000000
  let gfx11_format = 0x20814fac
  let gfx12_swizzle = 0x40000000
  let gfx12_format = 0x20814fac
end

(* COMPUTE_TMPRING_SIZE bitfields as (shift, width), per target generation. *)
module Compute_tmpring_size = struct
  let gfx9_waves = (0, 12)
  let gfx9_wavesize = (12, 13)
  let gfx11_waves = (0, 12)
  let gfx11_wavesize = (12, 15)
  let gfx12_waves = (0, 12)
  let gfx12_wavesize = (12, 18)
end

let amd_queue_properties_is_ptr64 = 2
let amd_queue_properties_enable_profiling = 8
let amd_kernel_code_properties_enable_sgpr_private_segment_buffer = 1
let amd_kernel_code_properties_enable_sgpr_dispatch_ptr = 2
let hsa_packet_header_type = 0
let hsa_packet_header_barrier = 8
let hsa_packet_header_scacquire_fence_scope = 9
let hsa_packet_header_screlease_fence_scope = 0xb
let hsa_fence_scope_system = 2
let hsa_packet_type_vendor_specific = 0
let hsa_packet_type_kernel_dispatch = 2
let hsa_kernel_dispatch_packet_setup_dimensions = 0
