#!/usr/bin/env python3
"""Generate the nx.io test fixtures: files other tools write.

numpy writes the NPY, NPZ and text files, torch the bfloat16 SafeTensors file,
Python's gzip and zlib the compressed streams, and Pillow the JPEG files. The
PNG files come from the minimal writer below, which chooses the row filters,
sample depths and interlacing that an encoder picks on its own. Each image has
a sibling .npy of the pixels Pillow decodes from it.

Usage:
    cd packages/nx/test/fixtures
    uv run --with numpy --with pillow --with safetensors --with torch \\
      python generate.py
"""

import gzip
import struct
import zlib

import numpy as np
import torch
from PIL import Image
from safetensors.numpy import save_file
from safetensors.torch import save_file as save_torch


def safetensors_fixtures():
    # [+0, smallest subnormal, 1.0, +inf, NaN] at float16 and bfloat16
    f16_bits = [0x0000, 0x0001, 0x3C00, 0x7C00, 0x7E01]
    f16 = np.frombuffer(struct.pack("<5H", *f16_bits), dtype=np.float16)
    save_file({"f16_tensor": f16}, "f16_bit_exact.safetensors")
    bf16_bits = [0x0000, 0x0001, 0x3F80, 0x7F80, 0x7FC1]
    bf16 = torch.tensor(bf16_bits, dtype=torch.int16).view(torch.bfloat16)
    save_torch({"bf16_tensor": bf16}, "bf16_bit_exact.safetensors")


def numpy_fixtures():
    np.save("fortran.npy", np.asfortranarray(np.arange(1, 7, dtype="<f4").reshape(2, 3)))
    np.save("big_endian.npy", np.array([1, 256, -2], dtype=">i2"))
    for version, array in [((2, 0), np.array([7, 8, 9], dtype="<i4")),
                           ((3, 0), np.array([True, False, True]))]:
        with open("version%d.npy" % version[0], "wb") as f:
            np.lib.format.write_array(f, array, version=version)
    np.save("unicode.npy", np.array(["abc"]))
    np.savez_compressed("archive.npz", a=np.array([[1.5, -2.0]], dtype="<f4"),
                        b=np.array([3, 4, 5], dtype="<i8"))
    np.savetxt("savetxt.txt",
               np.array([[0.1, 1e23, 5e-324, 2.2250738585072014e-308, 1.23456789],
                         [-0.0, np.nan, np.inf, -np.inf, 1.7976931348623157e308]]),
               delimiter=",", newline="\r\n", header="alpha beta gamma",
               footer="generated by numpy", comments="##")


def compressed_fixtures():
    with open("hello.gz", "wb") as f:
        f.write(gzip.compress(b"hello, nx gzip!\n", mtime=0))
    lines = "".join("line %d\n" % i for i in range(200)).encode()
    for name, data, level in [("empty", b"", 9),
                              ("fixed", b"hello, nx zlib!\n", 1),
                              ("stored", b"stored block\n", 0),
                              ("dynamic", lines, 9)]:
        with open("zlib_%s.z" % name, "wb") as f:
            f.write(zlib.compress(data, level))


def paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    return a if pa <= pb and pa <= pc else b if pb <= pc else c


def filtered(kind, line, prev, bpp):
    out = bytearray([kind])
    for i, x in enumerate(line):
        a = line[i - bpp] if i >= bpp else 0
        b = prev[i]
        c = prev[i - bpp] if i >= bpp else 0
        out.append((x - [0, a, b, (a + b) // 2, paeth(a, b, c)][kind]) & 255)
    return bytes(out)


def packed(samples, depth):
    if depth == 16:
        return b"".join(struct.pack(">H", s) for s in samples)
    if depth == 8:
        return bytes(samples)
    per = 8 // depth
    samples = samples + [0] * (-len(samples) % per)
    return bytes(sum(s << (8 - depth * (k + 1)) for k, s in enumerate(samples[i:i + per]))
                 for i in range(0, len(samples), per))


def chunk(kind, data):
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", zlib.crc32(kind + data)))


def write_png(path, pixels, depth, color, filters=(0,), palette=None,
              trns=None, interlace=False):
    """pixels: rows of pixels, each a tuple of samples."""
    height, width, channels = len(pixels), len(pixels[0]), len(pixels[0][0])
    passes = ([(0, 0, 8, 8), (4, 0, 8, 8), (0, 4, 4, 8), (2, 0, 4, 4),
               (0, 2, 2, 4), (1, 0, 2, 2), (0, 1, 1, 2)]
              if interlace else [(0, 0, 1, 1)])
    bpp = max(1, depth * channels // 8)
    data = b""
    for x0, y0, dx, dy in passes:
        xs, ys = range(x0, width, dx), range(y0, height, dy)
        prev = None
        for k, y in enumerate(ys):
            if not xs:
                break
            line = packed([s for x in xs for s in pixels[y][x]], depth)
            prev = prev or bytes(len(line))
            data += filtered(filters[k % len(filters)], line, prev, bpp)
            prev = line
    header = struct.pack(">IIBBBBB", width, height, depth, color, 0, 0, int(interlace))
    body = chunk(b"IHDR", header)
    if palette:
        body += chunk(b"PLTE", bytes(v for rgb in palette for v in rgb))
    if trns:
        body += chunk(b"tRNS", bytes(trns))
    body += chunk(b"IDAT", zlib.compress(data, 9)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" + body)


def reference(path, mode):
    np.save(path.rsplit(".", 1)[0] + ".npy", np.asarray(Image.open(path).convert(mode)))


def image_fixtures():
    rgb = [[((31 * y + 73 * x) % 256, (73 * y + 11 * x) % 256, (47 * x * y + 5) % 256)
            for x in range(3)] for y in range(5)]
    write_png("png_filters.png", rgb, 8, 2, filters=(0, 1, 2, 3, 4))
    reference("png_filters.png", "RGB")
    bits = [[((x + y) % 3 == 0,) for x in range(8)] for y in range(2)]
    write_png("png_gray1.png", [[(int(b),) for (b,) in row] for row in bits], 1, 0,
              filters=(1, 2))
    reference("png_gray1.png", "L")
    write_png("png_rgb16.png", [[(0x0000, 0xFFFF, 0x8000), (0x1234, 0xABCD, 0x01FF)]],
              16, 2, filters=(4,))
    reference("png_rgb16.png", "RGB")
    indices = [[((x + 2 * y) % 4,) for x in range(5)] for y in range(5)]
    write_png("png_palette_adam7.png", indices, 2, 3, filters=(0, 1, 2, 3, 4),
              palette=[(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0)],
              trns=[255, 128, 255, 0], interlace=True)
    reference("png_palette_adam7.png", "RGB")

    def gradient(h, w, mode):
        a = np.fromfunction(lambda y, x, c: 10 + 12 * y + 8 * x + 30 * c,
                            (h, w, len(mode)))
        return Image.fromarray(a.astype(np.uint8).squeeze(), mode)

    gradient(8, 8, "RGB").save("jpeg_baseline.jpg", quality=90)
    gradient(7, 9, "RGB").save("jpeg_progressive.jpg", quality=90, progressive=True)
    gradient(6, 5, "L").save("jpeg_gray.jpg", quality=90)
    gradient(5, 6, "CMYK").save("jpeg_cmyk.jpg", quality=90)
    gradient(9, 11, "RGB").save("jpeg_restart.jpg", quality=90, restart_marker_blocks=1)
    for name in ["baseline", "progressive", "gray", "cmyk", "restart"]:
        reference("jpeg_%s.jpg" % name, "RGB")


if __name__ == "__main__":
    safetensors_fixtures()
    numpy_fixtures()
    compressed_fixtures()
    image_fixtures()
