(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by gen/gen.py from the excerpts in gen/headers; do not edit.
   The command that regenerates this file is in gen/gen.py.

   The values are NVIDIA's, copied under the MIT licence from its headers and
   from the headers of Linux's nouveau driver (SPDX-License-Identifier: MIT):

   Copyright (c) 1993-2021 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1993-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 1993-2024, NVIDIA CORPORATION
   Copyright (c) 2003-2016 NVIDIA Corporation
   Copyright (c) 2003-2021 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2003-2022 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2003-2023 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2003-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2008-2025 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2017-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2018-2019 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2019-2022 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2021-2024 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES
   Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES

   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE. *)

(* Constants. *)
let nv_vgpu_msg_signature_valid = 0x43505256
let nv_vgpu_msg_result_rpc_pending = 0xffffffff
let nv_vgpu_msg_header_version_major_tot = 3
let nv_vgpu_msg_header_version_minor_tot = 0
let gsp_fw_wpr_meta_revision = 1
let gsp_fw_wpr_meta_magic = 0xdc3aae21371a60b3L
let bit_header_signature = 0x544942
let bit_token_falcon_data = 0x70
let bit_token_v1_00_size_6 = 6
let bit_token_v1_00_size_8 = 8
let bit_data_falcon_data_v2_size_4 = 4
let falcon_ucode_entry_appid_fwsec_prod = 0x85
let falcon_ucode_desc_v3_size_44 = 0x2c
let bcrt30_rsa3k_sig_size = 0x180
let nv_bit_falcon_ucode_desc_header_vdesc_version_v3 = 3
let falcon_application_interface_entry_id_dmemmapper = 4
let falcon_application_interface_dmem_mapper_v3_cmd_frts = 0x15
let fwseclic_read_vbios_struct_flags = 2
let fwseclic_frts_region_media_fb = 2
let fwseclic_frts_region_size_1mb_in_4k = 0x100
let nv_bcrt_hash_info_base_code_type_vbios_base = 0
let nv_bcrt_hash_info_base_code_type_vbios_ext = 0xe0
let offsetof_pci_exp_rom_pci_data_struct_ptr = 0x18
let offsetof_pci_data_struct_image_len = 0x10
let offsetof_pci_data_struct_code_type = 0x14
let pci_rom_image_block_size = 0x200
let bit_header_id = 0xb8ff
let bit_header_size_offset = 8
let falcon_ucode_table_hdr_v1_version = 1
let falcon_ucode_table_hdr_v1_size_6 = 6
let falcon_ucode_table_entry_v1_size_6 = 6
let falcon_ucode_entry_appid_firmware_sec_lic = 5
let pci_data_struct_signature = 0x52494350
let pci_data_struct_signature_nv = 0x5344504e
let pci_data_struct_signature_nv2 = 0x53494752
let offsetof_pci_data_struct_len = 0xa
let offsetof_pci_data_struct_last_image = 0x15
let nv_pci_data_ext_sig = 0x4544504e
let nv_pci_data_ext_rev_10 = 0x100
let nv_pci_data_ext_rev_11 = 0x101
let offsetof_pci_data_ext_struct_sig = 0
let offsetof_pci_data_ext_struct_len = 6
let offsetof_pci_data_ext_struct_rev = 4
let offsetof_pci_data_ext_struct_subimage_len = 8
let offsetof_pci_data_ext_struct_last_image = 0xa

(* Bit fields of 32-bit words: (lowest bit, bits). *)
let nv_bit_falcon_ucode_desc_header_vdesc_version = (8, 8)
let nv_bit_falcon_ucode_desc_header_vdesc_size = (0x10, 0x10)
let nv_vgpu_msg_header_version_major = (0x18, 8)
let nv_vgpu_msg_header_version_minor = (0x10, 8)

(* The GSP's functions and events (rpc_global_enums.h). *)
let nv_vgpu_msg_function_continuation_record = 0x47
let nv_vgpu_msg_function_gsp_rm_alloc = 0x67
let nv_vgpu_msg_function_gsp_rm_control = 0x4c
let nv_vgpu_msg_function_set_page_directory = 0x36
let nv_vgpu_msg_function_gsp_set_system_info = 0x48
let nv_vgpu_msg_function_set_registry = 0x49
let nv_vgpu_msg_function_unloading_guest_driver = 0x2f
let nv_vgpu_msg_event_gsp_init_done = 0x1001
let nv_vgpu_msg_event_gsp_run_cpu_sequencer = 0x1002
let nv_vgpu_msg_event_rc_triggered = 0x1004
let nv_vgpu_msg_event_mmu_fault_queued = 0x1005
let nv_vgpu_msg_event_os_error_log = 0x1006
let nv_vgpu_msg_event_ucode_libos_print = 0x100c

(* Structs: each field is (byte offset, bytes), an array's (offset, bytes
   of an element, elements). *)
module Msgq_tx_header = struct
  let sizeof = 32
  let version = (0, 4)
  let size = (4, 4)
  let msg_size = (8, 4)
  let msg_count = (0xc, 4)
  let write_ptr = (0x10, 4)
  let flags = (0x14, 4)
  let rx_hdr_off = (0x18, 4)
  let entry_off = (0x1c, 4)
end

module Msgq_rx_header = struct
  let sizeof = 4
  let read_ptr = (0, 4)
end

module Queue_element = struct
  let sizeof = 80
  let auth_tag_buffer = (0, 1, 0x10)
  let aad_buffer = (0x10, 1, 0x10)
  let check_sum = (0x20, 4)
  let seq_num = (0x24, 4)
  let elem_count = (0x28, 4)
  let rpc = (0x30, 0x20)
end

module Rpc_header = struct
  let sizeof = 32
  let header_version = (0, 4)
  let signature = (4, 4)
  let length = (8, 4)
  let function_ = (0xc, 4)
  let rpc_result = (0x10, 4)
  let rpc_result_private = (0x14, 4)
  let sequence = (0x18, 4)
end

module Rpc_rc_triggered = struct
  let sizeof = 48
  let nv2080_engine_type = (0, 4)
  let chid = (4, 4)
  let except_type = (0x10, 4)
  let scope = (0x14, 4)
end

module Wpr_meta = struct
  let sizeof = 256
  let magic = (0, 8)
  let revision = (8, 8)
  let sysmem_addr_of_radix3_elf = (0x10, 8)
  let size_of_radix3_elf = (0x18, 8)
  let sysmem_addr_of_bootloader = (0x20, 8)
  let size_of_bootloader = (0x28, 8)
  let bootloader_code_offset = (0x30, 8)
  let bootloader_data_offset = (0x38, 8)
  let bootloader_manifest_offset = (0x40, 8)
  let sysmem_addr_of_signature = (0x48, 8)
  let size_of_signature = (0x50, 8)
  let gsp_fw_rsvd_start = (0x58, 8)
  let non_wpr_heap_offset = (0x60, 8)
  let non_wpr_heap_size = (0x68, 8)
  let gsp_fw_wpr_start = (0x70, 8)
  let gsp_fw_heap_offset = (0x78, 8)
  let gsp_fw_heap_size = (0x80, 8)
  let gsp_fw_offset = (0x88, 8)
  let boot_bin_offset = (0x90, 8)
  let frts_offset = (0x98, 8)
  let frts_size = (0xa0, 8)
  let gsp_fw_wpr_end = (0xa8, 8)
  let fb_size = (0xb0, 8)
  let vga_workspace_offset = (0xb8, 8)
  let vga_workspace_size = (0xc0, 8)
  let pmu_reserved_size = (0xf4, 4)
end

module Riscv_ucode_desc = struct
  let sizeof = 84
  let monitor_data_offset = (0x28, 4)
  let monitor_code_offset = (0x30, 4)
  let manifest_offset = (0x20, 4)
end

module App_interface_header = struct
  let sizeof = 4
  let header_size = (1, 1)
  let entry_size = (2, 1)
  let entry_count = (3, 1)
end

module App_interface_entry = struct
  let sizeof = 8
  let id = (0, 4)
  let dmem_offset = (4, 4)
end

module Dmem_mapper = struct
  let sizeof = 64
  let cmd_in_buffer_offset = (8, 4)
  let init_cmd = (0x2c, 4)
end

module Read_vbios_desc = struct
  let sizeof = 24
end

module Frts_region_desc = struct
  let sizeof = 20
end

module Frts_cmd = struct
  let sizeof = 48
  let read_vbios_desc_version = (0, 4)
  let read_vbios_desc_size = (4, 4)
  let read_vbios_desc_gfw_image_offset = (8, 8)
  let read_vbios_desc_gfw_image_size = (0x10, 4)
  let read_vbios_desc_flags = (0x14, 4)
  let frts_region_desc_version = (0x18, 4)
  let frts_region_desc_size = (0x1c, 4)
  let frts_region_desc_frts_region_offset4_k = (0x20, 4)
  let frts_region_desc_frts_region_size = (0x24, 4)
  let frts_region_desc_frts_region_media_type = (0x28, 4)
end

module Bin_header = struct
  let sizeof = 24
  let bin_magic = (0, 4)
  let header_offset = (0xc, 4)
  let data_offset = (0x10, 4)
  let data_size = (0x14, 4)
end

module Hs_header = struct
  let sizeof = 36
  let sig_prod_offset = (0, 4)
  let sig_prod_size = (4, 4)
  let patch_loc = (8, 4)
  let patch_sig = (0xc, 4)
  let num_sig = (0x18, 4)
  let header_offset = (0x1c, 4)
end

module Hs_load_header = struct
  let sizeof = 20
  let os_data_offset = (8, 4)
  let os_data_size = (0xc, 4)
  let num_apps = (0x10, 4)
  let app = (0x14, 8, 0)
end

(* The VBIOS's structures, packed: each field is (byte offset, bytes). *)
module Bit_header = struct
  let sizeof = 12
  let id = (0, 2)
  let signature = (2, 4)
  let bcd_version = (6, 2)
  let header_size = (8, 1)
  let token_size = (9, 1)
  let token_entries = (0xa, 1)
  let header_chksum = (0xb, 1)
end

module Bit_token_6 = struct
  let sizeof = 6
  let token_id = (0, 1)
  let data_version = (1, 1)
  let data_size = (2, 2)
  let data_ptr = (4, 2)
end

module Bit_token_8 = struct
  let sizeof = 8
  let token_id = (0, 1)
  let data_version = (1, 1)
  let data_size = (2, 2)
  let data_ptr = (4, 4)
end

module Falcon_data = struct
  let sizeof = 4
  let falcon_ucode_table_ptr = (0, 4)
end

module Ucode_table_header = struct
  let sizeof = 6
  let version = (0, 1)
  let header_size = (1, 1)
  let entry_size = (2, 1)
  let entry_count = (3, 1)
  let desc_version = (4, 1)
  let desc_size = (5, 1)
end

module Ucode_table_entry = struct
  let sizeof = 6
  let application_id = (0, 1)
  let target_id = (1, 1)
  let desc_ptr = (2, 4)
end

module Ucode_desc_header = struct
  let sizeof = 4
  let v_desc = (0, 4)
end

module Ucode_desc_v3 = struct
  let sizeof = 44
  let hdr = (0, 4)
  let stored_size = (4, 4)
  let pkc_data_offset = (8, 4)
  let interface_offset = (0xc, 4)
  let imem_phys_base = (0x10, 4)
  let imem_load_size = (0x14, 4)
  let imem_virt_base = (0x18, 4)
  let dmem_phys_base = (0x1c, 4)
  let dmem_load_size = (0x20, 4)
  let engine_id_mask = (0x24, 2)
  let ucode_id = (0x26, 1)
  let signature_count = (0x27, 1)
  let signature_versions = (0x28, 2)
  let reserved = (0x2a, 2)
end

(* nverror.h's robust channel errors, by value. *)
let robust_channel_errors = [
  (0xd, "GR_EXCEPTION");
  (0xe, "FAKE_ERROR");
  (0x10, "VBLANK_CALLBACK_TIMEOUT");
  (0x13, "DISP_MISSED_NOTIFIER");
  (0x14, "MPEG_ERROR_SW_METHOD");
  (0x15, "ME_ERROR_SW_METHOD");
  (0x16, "VP_ERROR_SW_METHOD");
  (0x17, "RC_LOGGING_ENABLED");
  (0x1b, "VP_ERROR");
  (0x1c, "VP2_ERROR");
  (0x1d, "BSP_ERROR");
  (0x1e, "UNUSED_ERROR_30");
  (0x1f, "FIFO_ERROR_MMU_ERR_FLT");
  (0x20, "PBDMA_ERROR");
  (0x21, "SEC_ERROR");
  (0x22, "MSVLD_ERROR");
  (0x23, "MSPDEC_ERROR");
  (0x24, "MSPPP_ERROR");
  (0x27, "CE0_ERROR");
  (0x28, "CE1_ERROR");
  (0x29, "CE2_ERROR");
  (0x2a, "VIC_ERROR");
  (0x2b, "RESETCHANNEL_VERIF_ERROR");
  (0x2c, "GR_FAULT_DURING_CTXSW");
  (0x2d, "PREEMPTIVE_REMOVAL");
  (0x2f, "NVENC0_ERROR");
  (0x30, "GPU_ECC_DBE");
  (0x3c, "SEC2_ERROR");
  (0x41, "NVENC1_ERROR");
  (0x44, "NVDEC0_ERROR");
  (0x45, "GR_CLASS_ERROR");
  (0x46, "CE3_ERROR");
  (0x47, "CE4_ERROR");
  (0x48, "CE5_ERROR");
  (0x49, "NVENC2_ERROR");
  (0x4b, "CE6_ERROR");
  (0x4c, "CE7_ERROR");
  (0x4d, "CE8_ERROR");
  (0x4f, "GPU_HAS_FALLEN_OFF_THE_BUS");
  (0x51, "VGA_SUBSYSTEM_ERROR");
  (0x52, "NVJPG0_ERROR");
  (0x53, "NVDEC1_ERROR");
  (0x54, "NVDEC2_ERROR");
  (0x55, "CE9_ERROR");
  (0x56, "OFA0_ERROR");
  (0x58, "NVDEC3_ERROR");
  (0x59, "NVDEC4_ERROR");
  (0x5e, "CONTAINED_ERROR");
  (0x5f, "UNCONTAINED_ERROR");
  (0x60, "NVDEC5_ERROR");
  (0x61, "NVDEC6_ERROR");
  (0x62, "NVDEC7_ERROR");
  (0x63, "NVJPG1_ERROR");
  (0x64, "NVJPG2_ERROR");
  (0x65, "NVJPG3_ERROR");
  (0x66, "NVJPG4_ERROR");
  (0x67, "NVJPG5_ERROR");
  (0x68, "NVJPG6_ERROR");
  (0x69, "NVJPG7_ERROR");
  (0x7e, "CE10_ERROR");
  (0x7f, "CE11_ERROR");
  (0x80, "CE12_ERROR");
  (0x81, "CE13_ERROR");
  (0x82, "CE14_ERROR");
  (0x83, "CE15_ERROR");
  (0x84, "CE16_ERROR");
  (0x85, "CE17_ERROR");
  (0x86, "CE18_ERROR");
  (0x87, "CE19_ERROR");
  (0x8a, "DLA_ERROR");
  (0x8b, "OFA1_ERROR");
  (0x8d, "FAST_PATH_ERROR");
  (0x8e, "NVENC3_ERROR");
  (0x97, "KEY_ROTATION_ERROR");
]

(* Page-table entries: fields as (lowest bit, bits) of the entry, which is
   16 bytes for a dual entry, and values. *)
let nv_mmu_pte_kind_generic_memory = 6
let nv_mmu_ver2_dual_pde_address_big_sys = (4, 0x32)
let nv_mmu_ver2_dual_pde_address_big_vid = (4, 0x1d)
let nv_mmu_ver2_dual_pde_address_big_vid_peer = (0x21, 3)
let nv_mmu_ver2_dual_pde_address_small_sys = (0x48, 0x2e)
let nv_mmu_ver2_dual_pde_address_small_vid = (0x48, 0x19)
let nv_mmu_ver2_dual_pde_address_small_vid_peer = (0x61, 3)
let nv_mmu_ver2_dual_pde_aperture_big = (1, 2)
let nv_mmu_ver2_dual_pde_aperture_small = (0x41, 2)
let nv_mmu_ver2_dual_pde_is_pde = (0, 1)
let nv_mmu_ver2_dual_pde_is_pte = (0, 1)
let nv_mmu_ver2_dual_pde_no_ats = (5, 1)
let nv_mmu_ver2_dual_pde_valid = (0, 1)
let nv_mmu_ver2_dual_pde_vol_big = (3, 1)
let nv_mmu_ver2_dual_pde_vol_small = (0x43, 1)
let nv_mmu_ver2_pde_address_sys = (8, 0x2e)
let nv_mmu_ver2_pde_address_vid = (8, 0x19)
let nv_mmu_ver2_pde_address_vid_peer = (0x21, 3)
let nv_mmu_ver2_pde_aperture = (1, 2)
let nv_mmu_ver2_pde_is_pde = (0, 1)
let nv_mmu_ver2_pde_is_pte = (0, 1)
let nv_mmu_ver2_pde_no_ats = (5, 1)
let nv_mmu_ver2_pde_valid = (0, 1)
let nv_mmu_ver2_pde_vol = (3, 1)
let nv_mmu_ver2_pte_address_sys = (8, 0x2e)
let nv_mmu_ver2_pte_address_vid = (8, 0x19)
let nv_mmu_ver2_pte_address_vid_peer = (0x21, 3)
let nv_mmu_ver2_pte_aperture = (1, 2)
let nv_mmu_ver2_pte_atomic_disable = (7, 1)
let nv_mmu_ver2_pte_comptagline = (0x24, 0x14)
let nv_mmu_ver2_pte_encrypted = (4, 1)
let nv_mmu_ver2_pte_kind = (0x38, 8)
let nv_mmu_ver2_pte_privilege = (5, 1)
let nv_mmu_ver2_pte_read_only = (6, 1)
let nv_mmu_ver2_pte_valid = (0, 1)
let nv_mmu_ver2_pte_vol = (3, 1)
let nv_mmu_ver2_pte_aperture_video_memory = 0
let nv_mmu_ver2_pte_aperture_peer_memory = 1
let nv_mmu_ver2_pte_aperture_system_coherent_memory = 2
let nv_mmu_ver2_pte_aperture_system_non_coherent_memory = 3
let nv_mmu_ver2_pde_aperture_invalid = 0
let nv_mmu_ver2_pde_aperture_video_memory = 1
let nv_mmu_ver2_pde_aperture_system_coherent_memory = 2
let nv_mmu_ver2_pde_aperture_system_non_coherent_memory = 3
let nv_mmu_ver2_dual_pde_aperture_small_video_memory = 1
let nv_mmu_ver3_dual_pde_address_big = (8, 0x2c)
let nv_mmu_ver3_dual_pde_address_small = (0x4c, 0x28)
let nv_mmu_ver3_dual_pde_aperture_big = (1, 2)
let nv_mmu_ver3_dual_pde_aperture_small = (0x41, 2)
let nv_mmu_ver3_dual_pde_is_pte = (0, 1)
let nv_mmu_ver3_dual_pde_pcf_big = (3, 3)
let nv_mmu_ver3_dual_pde_pcf_small = (0x43, 3)
let nv_mmu_ver3_dual_pde_valid = (0, 1)
let nv_mmu_ver3_pde_address = (0xc, 0x28)
let nv_mmu_ver3_pde_aperture = (1, 2)
let nv_mmu_ver3_pde_is_pte = (0, 1)
let nv_mmu_ver3_pde_pcf = (3, 3)
let nv_mmu_ver3_pde_valid = (0, 1)
let nv_mmu_ver3_pte_address = (0xc, 0x28)
let nv_mmu_ver3_pte_address_peer = (0xc, 0x28)
let nv_mmu_ver3_pte_address_sys = (0xc, 0x28)
let nv_mmu_ver3_pte_address_vid = (0xc, 0x1c)
let nv_mmu_ver3_pte_aperture = (1, 2)
let nv_mmu_ver3_pte_kind = (8, 4)
let nv_mmu_ver3_pte_pcf = (3, 5)
let nv_mmu_ver3_pte_peer_id = (0x3d, 3)
let nv_mmu_ver3_pte_valid = (0, 1)
let nv_mmu_ver3_pte_aperture_video_memory = 0
let nv_mmu_ver3_pte_aperture_peer_memory = 1
let nv_mmu_ver3_pte_aperture_system_coherent_memory = 2
let nv_mmu_ver3_pte_aperture_system_non_coherent_memory = 3
let nv_mmu_ver3_pde_aperture_invalid = 0
let nv_mmu_ver3_pde_aperture_video_memory = 1
let nv_mmu_ver3_pde_aperture_system_coherent_memory = 2
let nv_mmu_ver3_pde_aperture_system_non_coherent_memory = 3
let nv_mmu_ver3_dual_pde_aperture_small_video_memory = 1
let nv_mmu_ver3_pte_pcf_regular_rw_atomic_cached_ace = 0
let nv_mmu_ver3_pte_pcf_regular_rw_atomic_uncached_ace = 1
let nv_mmu_ver3_pde_pcf_valid_cached_ats_not_allowed = 2
let nv_mmu_ver3_dual_pde_pcf_small_valid_cached_ats_not_allowed = 2

(* Registers: each is its address in BAR 0, or a function of its index, and
   each of its fields (lowest bit, bits). Those of both families, then what
   differs: Ampere and Ada's, and Blackwell's. *)
let nv_pmc_boot_0 = 0
let nv_pmc_boot_0_architecture_0 = (0x18, 5)
let nv_pmc_boot_0_architecture_1 = (8, 1)
let nv_pmc_boot_0_implementation = (0x14, 4)
let nv_pmc_boot_0_major_revision = (4, 4)
let nv_pmc_boot_0_minor_revision = (0, 4)
let nv_pmc_boot_42 = 0xa00
let nv_pmc_boot_42_architecture = (0x18, 6)
let nv_pmc_boot_42_chip_id = (0x14, 0xa)
let nv_pmc_boot_42_implementation = (0x14, 4)
let nv_pmc_boot_42_major_revision = (0x10, 4)
let nv_pmc_boot_42_minor_extended_revision = (8, 4)
let nv_pmc_boot_42_minor_revision = (0xc, 4)
let nv_pfb_pri_mmu_wpr2_addr_lo = 0x1fa824
let nv_pfb_pri_mmu_wpr2_addr_lo_val = (4, 0x1c)
let nv_pfb_pri_mmu_wpr2_addr_hi = 0x1fa828
let nv_pfb_pri_mmu_wpr2_addr_hi_val = (4, 0x1c)
let nv_pgc6_aon_secure_scratch_group_42 = 0x1183a4
let nv_virtual_function_priv_mmu_invalidate = 0xb830b0
let nv_virtual_function_priv_mmu_invalidate_ack = (7, 2)
let nv_virtual_function_priv_mmu_invalidate_all_pdb = (1, 1)
let nv_virtual_function_priv_mmu_invalidate_all_va = (0, 1)
let nv_virtual_function_priv_mmu_invalidate_cache_level = (0x18, 3)
let nv_virtual_function_priv_mmu_invalidate_cancel_client_id = (9, 6)
let nv_virtual_function_priv_mmu_invalidate_cancel_client_type = (0x14, 1)
let nv_virtual_function_priv_mmu_invalidate_cancel_gpc_id = (0xf, 5)
let nv_virtual_function_priv_mmu_invalidate_hubtlb_only = (2, 1)
let nv_virtual_function_priv_mmu_invalidate_pdb_addr = (4, 0x1c)
let nv_virtual_function_priv_mmu_invalidate_pdb_aperture = (1, 1)
let nv_virtual_function_priv_mmu_invalidate_prop_flush = (0x17, 1)
let nv_virtual_function_priv_mmu_invalidate_replay = (3, 3)
let nv_virtual_function_priv_mmu_invalidate_sys_membar = (6, 1)
let nv_virtual_function_priv_mmu_invalidate_trigger = (0x1f, 1)
let nv_virtual_function_priv_mmu_invalidate_upper_pdb_addr = (0, 0x14)
let nv_virtual_function_priv_mmu_invalidate_use_pasid = (0x15, 1)
let nv_virtual_function_priv_mmu_invalidate_use_size = (0x16, 1)
let nv_pbus_bar1_block = 0x1704
let nv_pbus_bar1_block_map = (0, 0x1e)
let nv_pbus_bar1_block_mode = (0x1f, 1)
let nv_pbus_bar1_block_ptr = (0, 0x1c)
let nv_pbus_bar1_block_target = (0x1c, 2)
let nv_pgsp_queue_head i = 0x110c00 + (i * 8)
let nv_pgsp_queue_head_address = (0, 0x20)
let nv_pmc_boot_42_architecture_ga100 = 0x17
let nv_pmc_boot_42_architecture_ad100 = 0x19
let nv_pmc_boot_42_architecture_gb200 = 0x1b
let nv_pfalcon_falcon_dmatrfcmd_size_256b = 6
let nv_pfalcon_fbif_transcfg_mem_type_physical = 1
let nv_pfalcon2_falcon_mod_sel_algo_rsa3k = 1

module type FAMILY = sig
  val nv_pfalcon_falcon_hwcfg2 : int
  val nv_pfalcon_falcon_hwcfg2_mem_scrubbing : int * int
  val nv_pfalcon_falcon_hwcfg2_riscv : int * int
end

module Legacy = struct
  let nv_pgc6_aon_secure_scratch_group_05_priv_level_mask = 0x118128
  let nv_pgc6_aon_secure_scratch_group_05_priv_level_mask_read_protection = (0, 4)
  let nv_pgc6_aon_secure_scratch_group_05_priv_level_mask_read_protection_level0 = (0, 1)
  let nv_pgc6_aon_secure_scratch_group_05 i = 0x118234 + (i * 4)
  let nv_pgc6_aon_secure_scratch_group_05_0_gfw_boot_progress = (0, 8)
  let nv_pgc6_bsi_secure_scratch_14 = 0x1180f8
  let nv_pgc6_bsi_secure_scratch_14_boot_stage_3_handoff = (0x1a, 1)
  let nv_pgsp_falcon_mailbox0 = 0x110040
  let nv_pgsp_falcon_mailbox0_data = (0, 0x20)
  let nv_pgsp_falcon_mailbox1 = 0x110044
  let nv_pgsp_falcon_mailbox1_data = (0, 0x20)
  let nv_pgsp_falcon_engine = 0x1103c0
  let nv_pgsp_falcon_engine_reset = (0, 1)
  let nv_psec_falcon_engine = 0x8403c0
  let nv_psec_falcon_engine_reset = (0, 1)
  let nv_pfalcon_falcon_os = 0x80
  let nv_pfalcon_falcon_dmatrfcmd = 0x118
  let nv_pfalcon_falcon_dmatrfcmd_ctxdma = (0xc, 3)
  let nv_pfalcon_falcon_dmatrfcmd_full = (0, 1)
  let nv_pfalcon_falcon_dmatrfcmd_idle = (1, 1)
  let nv_pfalcon_falcon_dmatrfcmd_imem = (4, 1)
  let nv_pfalcon_falcon_dmatrfcmd_sec = (2, 2)
  let nv_pfalcon_falcon_dmatrfcmd_set_dmtag = (0x10, 1)
  let nv_pfalcon_falcon_dmatrfcmd_size = (8, 3)
  let nv_pfalcon_falcon_dmatrfcmd_write = (5, 1)
  let nv_pfalcon_falcon_dmatrfbase = 0x110
  let nv_pfalcon_falcon_dmatrfbase_base = (0, 0x20)
  let nv_pfalcon_falcon_dmatrfbase1 = 0x128
  let nv_pfalcon_falcon_dmatrfbase1_base = (0, 9)
  let nv_pfalcon_falcon_dmatrfmoffs = 0x114
  let nv_pfalcon_falcon_dmatrfmoffs_offs = (0, 0x18)
  let nv_pfalcon_falcon_dmatrffboffs = 0x11c
  let nv_pfalcon_falcon_dmatrffboffs_offs = (0, 0x20)
  let nv_pfalcon_falcon_cpuctl = 0x100
  let nv_pfalcon_falcon_cpuctl_alias_en = (6, 1)
  let nv_pfalcon_falcon_cpuctl_alias_startcpu = (1, 1)
  let nv_pfalcon_falcon_cpuctl_halted = (4, 1)
  let nv_pfalcon_falcon_cpuctl_startcpu = (1, 1)
  let nv_pfalcon_falcon_cpuctl_alias = 0x130
  let nv_pfalcon_falcon_bootvec = 0x104
  let nv_pfalcon_falcon_mailbox0 = 0x40
  let nv_pfalcon_falcon_mailbox1 = 0x44
  let nv_pfalcon_falcon_dmactl = 0x10c
  let nv_pfalcon_falcon_dmactl_dmem_scrubbing = (1, 1)
  let nv_pfalcon_falcon_dmactl_imem_scrubbing = (2, 1)
  let nv_pfalcon_falcon_dmactl_require_ctx = (0, 1)
  let nv_pfalcon_falcon_hwcfg2 = 0xf4
  let nv_pfalcon_falcon_hwcfg2_mem_scrubbing = (0xc, 1)
  let nv_pfalcon_falcon_hwcfg2_reset_ready = (0x1f, 1)
  let nv_pfalcon_falcon_hwcfg2_riscv = (0xa, 1)
  let nv_pfalcon_falcon_rm = 0x84
  let nv_pfalcon_fbif_transcfg i = 0x600 + (i * 4)
  let nv_pfalcon_fbif_transcfg_mem_type = (2, 1)
  let nv_pfalcon_fbif_transcfg_target = (0, 2)
  let nv_pfalcon_fbif_ctl = 0x624
  let nv_pfalcon_fbif_ctl_allow_phys_no_ctx = (7, 1)
  let nv_pfalcon2_falcon_brom_paraaddr i = 0x1210 + (i * 4)
  let nv_pfalcon2_falcon_brom_engidmask = 0x119c
  let nv_pfalcon2_falcon_brom_curr_ucode_id = 0x1198
  let nv_pfalcon2_falcon_brom_curr_ucode_id_val = (0, 8)
  let nv_pfalcon2_falcon_mod_sel = 0x1180
  let nv_pfalcon2_falcon_mod_sel_algo = (0, 8)
  let nv_priscv_riscv_cpuctl = 0x1388
  let nv_priscv_riscv_cpuctl_active_stat = (7, 1)
  let nv_priscv_riscv_cpuctl_halted = (4, 1)
  let nv_priscv_riscv_bcr_ctrl = 0x1668
  let nv_priscv_riscv_bcr_ctrl_brfetch = (8, 1)
  let nv_priscv_riscv_bcr_ctrl_core_select = (4, 1)
  let nv_priscv_riscv_bcr_ctrl_valid = (0, 1)
  let nv_prom_data i = 0x300000 + (i * 1)
end

module Blackwell = struct
  let nv_virtual_function_priv_func_bar1_block_low_addr = 0xb80f60
  let nv_virtual_function_priv_func_bar1_block_low_addr_bar1_outstanding = (1, 1)
  let nv_virtual_function_priv_func_bar1_block_low_addr_bar1_pending = (0, 1)
  let nv_virtual_function_priv_func_bar1_block_low_addr_map = (0xa, 0x16)
  let nv_virtual_function_priv_func_bar1_block_low_addr_mode = (9, 1)
  let nv_virtual_function_priv_func_bar1_block_low_addr_ptr = (0xc, 0x14)
  let nv_virtual_function_priv_func_bar1_block_low_addr_target = (0xa, 2)
  let nv_pfalcon_falcon_hwcfg2 = 0xf4
  let nv_pfalcon_falcon_hwcfg2_bmem = (1, 1)
  let nv_pfalcon_falcon_hwcfg2_boot_from_hs = (0xe, 1)
  let nv_pfalcon_falcon_hwcfg2_dbgmode = (3, 1)
  let nv_pfalcon_falcon_hwcfg2_gdma = (0x11, 1)
  let nv_pfalcon_falcon_hwcfg2_hs = (8, 1)
  let nv_pfalcon_falcon_hwcfg2_hscode_revocation = (5, 1)
  let nv_pfalcon_falcon_hwcfg2_kmem = (4, 1)
  let nv_pfalcon_falcon_hwcfg2_mem_scrubbing = (0xc, 1)
  let nv_pfalcon_falcon_hwcfg2_pkcboot = (2, 1)
  let nv_pfalcon_falcon_hwcfg2_prgn_rsvd_fuse = (0x18, 8)
  let nv_pfalcon_falcon_hwcfg2_riscv = (0xa, 1)
  let nv_pfalcon_falcon_hwcfg2_riscv_br_adpair = (0xf, 1)
  let nv_pfalcon_falcon_hwcfg2_riscv_br_priv_lockdown = (0xd, 1)
  let nv_pfalcon_falcon_hwcfg2_riscv_pl3_disable = (0xb, 1)
  let nv_pfalcon_falcon_hwcfg2_scp = (0x10, 1)
  let nv_pfalcon_falcon_hwcfg2_securebus = (9, 1)
  let nv_pfalcon_falcon_hwcfg2_se_lite = (0x12, 1)
  let nv_pfalcon_falcon_hwcfg2_sha = (0, 1)
  let nv_pfalcon_falcon_hwcfg2_strap_fun = (6, 1)
  let nv_pfalcon_falcon_hwcfg2_vhr = (7, 1)
  let nv_therm_i2cs_scratch = 0xad00bc
  let nv_therm_i2cs_scratch_data = (0, 0x20)
  let nv_pfsp_ememc i = 0x8f2ac0 + (i * 8)
  let nv_pfsp_ememc_aincr = (0x19, 1)
  let nv_pfsp_ememc_aincw = (0x18, 1)
  let nv_pfsp_ememc_blk = (8, 8)
  let nv_pfsp_ememc_offs = (2, 6)
  let nv_pfsp_ememd i = 0x8f2ac4 + (i * 8)
  let nv_pfsp_ememd_data = (0, 0x20)
  let nv_pfsp_queue_head i = 0x8f2c00 + (i * 8)
  let nv_pfsp_queue_head_address = (0, 0x20)
  let nv_pfsp_queue_tail i = 0x8f2c04 + (i * 8)
  let nv_pfsp_queue_tail_address = (0, 0x20)
  let nv_pfsp_msgq_head i = 0x8f2c80 + (i * 8)
  let nv_pfsp_msgq_head_val = (0, 0x20)
  let nv_pfsp_msgq_tail i = 0x8f2c84 + (i * 8)
  let nv_pfsp_msgq_tail_val = (0, 0x20)
end

(* The linux-firmware tree the firmware comes from: an image's URL is this
   followed by its path. *)
let origin = "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/"

(* The firmware images of each family, GSP first, and every image's
   BLAKE2b-256 digest. *)
let firmware_ampere = [ "nvidia/ga102/gsp/gsp-570.144.bin"; "nvidia/ga102/gsp/bootloader-570.144.bin"; "nvidia/ga102/gsp/booter_load-570.144.bin" ]
let firmware_ada = [ "nvidia/ga102/gsp/gsp-570.144.bin"; "nvidia/ad102/gsp/bootloader-570.144.bin"; "nvidia/ad102/gsp/booter_load-570.144.bin" ]
let firmware_blackwell = [ "nvidia/ga102/gsp/gsp-570.144.bin"; "nvidia/gb202/gsp/bootloader-570.144.bin"; "nvidia/gb202/gsp/fmc-570.144.bin" ]

let pinned = [
  ("nvidia/ad102/gsp/booter_load-570.144.bin", "3d70b4ad5b9e27983c645019a2dd30f300e0ce869120004eac5357e1e2fe7b40");
  ("nvidia/ad102/gsp/bootloader-570.144.bin", "a83162120a5e1b6d8a4ef8f61bd4492423da1bd5aa051112c427148bc3e48b31");
  ("nvidia/ga102/gsp/booter_load-570.144.bin", "5e8b7daacf8bf6bc6a1fb85f556230f584fb06c045b68ed3342caada357f7ea3");
  ("nvidia/ga102/gsp/bootloader-570.144.bin", "ae4ca5499421f1eb508f2378a242eecd79dcfc6cccb1d038a2c3a65a1d612d22");
  ("nvidia/ga102/gsp/gsp-570.144.bin", "877edf9f772d262d1ea72b9a6ebe52643e60a37c1d312f6456ebbf7f03feb03f");
  ("nvidia/gb202/gsp/bootloader-570.144.bin", "9cba35e93b2a6776fe68319a0bb1486bccb6a2e493dcf3c57ddab2686b2c0426");
  ("nvidia/gb202/gsp/fmc-570.144.bin", "eeca0ba4232118ee41adaa2d8f5dc921f8ee23131cfdc5ebeb0fbf11885f6d46");
]
