(*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(* Generated by ../gen/gen.py from the excerpts in ../gen/headers; do not
   edit. The command that regenerates this file is in ../gen/gen.py.

   The values are copied from rdma-core's and Linux's headers, which
   offer the GNU General Public License version 2 or the OpenIB.org BSD
   licence; raven takes the BSD licence:

   Copyright (c) 2013-2015, Mellanox Technologies. All rights reserved.
   Copyright (c) 2012 Mellanox Technologies, Inc.  All rights reserved.
   Copyright (c) 2020 Intel Corporation.  All rights reserved.
   Copyright (c) 2017 Mellanox Technologies, Inc.  All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

    - Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    - Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE. *)

(* Constants *)

let mlx5_send_wqe_bb = 0x40
let mlx5_opcode_rdma_write = 8
let mlx5_opcode_rdma_read = 0x10
let mlx5_wqe_ctrl_cq_update = 8
let mlx5_inline_seg = 0x80000000
let mlx5_rcv_dbr = 0
let mlx5_snd_dbr = 1
let mlx5_cqe_owner_mask = 1
let mlx5_cqe_req = 0
let mlx5_cqe_req_err = 0xd
let mlx5_cqe_resp_err = 0xe
let mlx5_cqe_invalid = 0xf
let mlx5_cqe_syndrome_local_length_err = 1
let mlx5_cqe_syndrome_local_qp_op_err = 2
let mlx5_cqe_syndrome_local_prot_err = 4
let mlx5_cqe_syndrome_wr_flush_err = 5
let mlx5_cqe_syndrome_mw_bind_err = 6
let mlx5_cqe_syndrome_bad_resp_err = 0x10
let mlx5_cqe_syndrome_local_access_err = 0x11
let mlx5_cqe_syndrome_remote_inval_req_err = 0x12
let mlx5_cqe_syndrome_remote_access_err = 0x13
let mlx5_cqe_syndrome_remote_op_err = 0x14
let mlx5_cqe_syndrome_transport_retry_exc_err = 0x15
let mlx5_cqe_syndrome_rnr_retry_exc_err = 0x16
let mlx5_cqe_syndrome_remote_aborted_err = 0x22
let mlx5_cq_db_req_not = 0
let mlx5_cq_doorbell = 0x20
let mlx5_bf_offset = 0x800
let mlx5_cq_set_ci = 0
let mlx5_cq_arm_db = 1
let mlx5_ib_mmap_cmd_shift = 8
let mlx5_adapter_page_size = 0x1000
let mlx5_bfregs_per_uar = 4
let mlx5_non_fp_bfregs_per_uar = 2
let mlx5_ib_mmap_nc_page = 3

(* Structures: each field is (byte offset, bytes). *)

module Ctrl_seg = struct
  let sizeof = 16
  let opmod_idx_opcode = (0, 4)
  let qpn_ds = (4, 4)
  let signature = (8, 1)
  let dci_stream_channel_id = (9, 2)
  let fm_ce_se = (11, 1)
  let imm = (12, 4)
end

module Raddr_seg = struct
  let sizeof = 16
  let raddr = (0, 8)
  let rkey = (8, 4)
  let reserved = (12, 4)
end

module Data_seg = struct
  let sizeof = 16
  let byte_count = (0, 4)
  let lkey = (4, 4)
  let addr = (8, 8)
end

module Inline_seg = struct
  let sizeof = 4
  let byte_count = (0, 4)
end

module Cqe64 = struct
  let sizeof = 64
  let rsvd0 = (0, 2)
  let wqe_id = (2, 2)
  let rsvd4 = (4, 13)
  let ml_path = (17, 1)
  let rsvd20 = (18, 4)
  let slid = (22, 2)
  let flags_rqpn = (24, 4)
  let hds_ip_ext = (28, 1)
  let l4_hdr_type_etc = (29, 1)
  let vlan_info = (30, 2)
  let srqn_uidx = (32, 4)
  let imm_inval_pkey = (36, 4)
  let app = (40, 1)
  let app_op = (41, 1)
  let app_info = (42, 2)
  let byte_cnt = (44, 4)
  let timestamp = (48, 8)
  let sop_drop_qpn = (56, 4)
  let wqe_counter = (60, 2)
  let signature = (62, 1)
  let op_own = (63, 1)
end

module Err_cqe = struct
  let sizeof = 64
  let rsvd0 = (0, 32)
  let srqn = (32, 4)
  let rsvd1 = (36, 18)
  let vendor_err_synd = (54, 1)
  let syndrome = (55, 1)
  let s_wqe_opcode_qpn = (56, 4)
  let wqe_counter = (60, 2)
  let signature = (62, 1)
  let op_own = (63, 1)
end
