name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build and test nx
        run: |
          opam exec -- dune build --release packages/nx
          opam exec -- dune build --release @packages/nx/runtest

      - name: Build and test brot
        run: |
          opam exec -- dune build --release packages/brot
          opam exec -- dune build --release @packages/brot/runtest

      - name: Build and test talon
        run: |
          opam exec -- dune build --release packages/talon
          opam exec -- dune build --release @packages/talon/runtest

      - name: Build and test rune
        run: |
          opam exec -- dune build --release packages/rune
          opam exec -- dune build --release @packages/rune/runtest

      - name: Build and test kaun
        run: |
          opam exec -- dune build --release packages/kaun
          opam exec -- dune build --release @packages/kaun/runtest

      - name: Build and test fehu
        run: |
          opam exec -- dune build --release packages/fehu
          opam exec -- dune build --release @packages/fehu/runtest

      - name: Build and test sowilo
        run: |
          opam exec -- dune build --release packages/sowilo
          opam exec -- dune build --release @packages/sowilo/runtest

      - name: Build and test hugin
        run: |
          opam exec -- dune build --release packages/hugin
          opam exec -- dune build --release @packages/hugin/runtest

      - name: Build and test quill
        run: |
          opam exec -- dune build --release packages/quill
          opam exec -- dune build --release @packages/quill/runtest
