/*---------------------------------------------------------------------------
  Copyright (c) 2026 The Raven authors. All rights reserved.
  Distributed under the ISC license, see terms at the end of the file.

  Based on ocaml_simd (https://github.com/janestreet/ocaml_simd)
  Copyright (c) 2025-2026 Jane Street Group, LLC
  Released under the MIT license.
  ---------------------------------------------------------------------------*/

#include <assert.h>

#define BUILTIN(name) void name() { assert(!"Didn't use [@@builtin] intrinsic."); }

BUILTIN(caml_vec128_unreachable)
BUILTIN(caml_vec128_cast)

/* float32x4 constants and lane ops */
BUILTIN(caml_float32x4_const1)
BUILTIN(caml_float32x4_const4)
BUILTIN(caml_float32x4_low_of_float32)
BUILTIN(caml_float32x4_low_to_float32)

/* float64x2 constants and lane ops */
BUILTIN(caml_float64x2_const1)
BUILTIN(caml_float64x2_const2)
BUILTIN(caml_float64x2_low_of_float)
BUILTIN(caml_float64x2_low_to_float)

/* int32x4 constants and lane ops */
BUILTIN(caml_int32x4_const1)
BUILTIN(caml_int32x4_const4)
BUILTIN(caml_int32x4_low_of_int32)
BUILTIN(caml_int32x4_low_to_int32)

/* int64x2 constants and lane ops */
BUILTIN(caml_int64x2_const1)
BUILTIN(caml_int64x2_const2)
BUILTIN(caml_int64x2_low_of_int64)
BUILTIN(caml_int64x2_low_to_int64)

/* NEON float32x4 */
BUILTIN(caml_neon_float32x4_add)
BUILTIN(caml_neon_float32x4_sub)
BUILTIN(caml_neon_float32x4_mul)
BUILTIN(caml_neon_float32x4_div)
BUILTIN(caml_neon_float32x4_sqrt)
BUILTIN(caml_neon_float32x4_rcp)
BUILTIN(caml_neon_float32x4_rsqrt)
BUILTIN(caml_neon_float32x4_hadd)
BUILTIN(caml_neon_float32x4_min)
BUILTIN(caml_neon_float32x4_max)
BUILTIN(caml_neon_float32x4_cmeq)
BUILTIN(caml_neon_float32x4_cmge)
BUILTIN(caml_neon_float32x4_cmgt)
BUILTIN(caml_neon_float32x4_cmle)
BUILTIN(caml_neon_float32x4_cmlt)
BUILTIN(caml_neon_float32x4_round_near)
BUILTIN(caml_neon_cvt_float32x4_to_int32x4)
BUILTIN(caml_neon_cvtt_float32x4_to_int32x4)
BUILTIN(caml_neon_cvt_float32x2_to_float64x2)

/* NEON float64x2 */
BUILTIN(caml_neon_float64x2_add)
BUILTIN(caml_neon_float64x2_sub)
BUILTIN(caml_neon_float64x2_mul)
BUILTIN(caml_neon_float64x2_div)
BUILTIN(caml_neon_float64x2_sqrt)
BUILTIN(caml_neon_float64x2_hadd)
BUILTIN(caml_neon_float64x2_min)
BUILTIN(caml_neon_float64x2_max)
BUILTIN(caml_neon_float64x2_cmeq)
BUILTIN(caml_neon_float64x2_cmge)
BUILTIN(caml_neon_float64x2_cmgt)
BUILTIN(caml_neon_float64x2_cmle)
BUILTIN(caml_neon_float64x2_cmlt)
BUILTIN(caml_neon_float64x2_round_near)
BUILTIN(caml_neon_float64x2_round_current)
BUILTIN(caml_neon_cvt_float64x2_to_int64x2)
BUILTIN(caml_neon_cvtt_float64x2_to_int64x2)
BUILTIN(caml_neon_cvt_float64x2_to_float32x2)

/* NEON int32x4 */
BUILTIN(caml_neon_int32x4_add)
BUILTIN(caml_neon_int32x4_sub)
BUILTIN(caml_neon_int32x4_neg)
BUILTIN(caml_neon_int32x4_abs)
BUILTIN(caml_neon_int32x4_mul_low)
BUILTIN(caml_neon_int32x4_mul_even)
BUILTIN(caml_neon_int32x4_mul_even_unsigned)
BUILTIN(caml_neon_int32x4_hadd)
BUILTIN(caml_neon_int32x4_hsub)
BUILTIN(caml_neon_int32x4_min)
BUILTIN(caml_neon_int32x4_max)
BUILTIN(caml_neon_int32x4_min_unsigned)
BUILTIN(caml_neon_int32x4_max_unsigned)
BUILTIN(caml_neon_int32x4_bitwise_or)
BUILTIN(caml_neon_int32x4_bitwise_and)
BUILTIN(caml_neon_int32x4_bitwise_andnot)
BUILTIN(caml_neon_int32x4_bitwise_xor)
BUILTIN(caml_neon_int32x4_bitwise_not)
BUILTIN(caml_neon_int32x4_cmpeq)
BUILTIN(caml_neon_int32x4_cmpgt)
BUILTIN(caml_neon_int32x4_cmpltz)
BUILTIN(caml_neon_int32x4_slli)
BUILTIN(caml_neon_int32x4_srli)
BUILTIN(caml_neon_int32x4_srai)
BUILTIN(caml_neon_int32x4_ushl)
BUILTIN(caml_neon_int32x4_sshl)
BUILTIN(caml_neon_int32x4_dup)
BUILTIN(caml_neon_int32x4_extract)
BUILTIN(caml_neon_int32x4_insert)
BUILTIN(caml_neon_int32x4_dup_lane)
BUILTIN(caml_neon_cvt_int32x4_to_float32x4)
BUILTIN(caml_neon_cvt_int32x4_int16x8_saturating)
BUILTIN(caml_neon_cvt_int32x4_int16x8_saturating_unsigned)
BUILTIN(caml_neon_cvtsx_int32x4_to_int64x2)
BUILTIN(caml_neon_cvtzx_int32x4_to_int64x2)

/* NEON int16x8 */
BUILTIN(caml_int16x8_low_of_int16)
BUILTIN(caml_int16x8_low_to_int16)
BUILTIN(caml_int16x8_const1)
BUILTIN(caml_neon_int16x8_insert)
BUILTIN(caml_neon_int16x8_extract)
BUILTIN(caml_neon_int16x8_add)
BUILTIN(caml_neon_int16x8_sub)
BUILTIN(caml_neon_int16x8_neg)
BUILTIN(caml_neon_int16x8_abs)
BUILTIN(caml_neon_int16x8_add_saturating)
BUILTIN(caml_neon_int16x8_add_saturating_unsigned)
BUILTIN(caml_neon_int16x8_sub_saturating)
BUILTIN(caml_neon_int16x8_sub_saturating_unsigned)
BUILTIN(caml_neon_int16x8_min)
BUILTIN(caml_neon_int16x8_max)
BUILTIN(caml_neon_int16x8_min_unsigned)
BUILTIN(caml_neon_int16x8_max_unsigned)
BUILTIN(caml_neon_int16x8_cmpeq)
BUILTIN(caml_neon_int16x8_cmpgt)
BUILTIN(caml_neon_int16x8_cmpltz)
BUILTIN(caml_neon_int16x8_hadd)
BUILTIN(caml_neon_int16x8_hsub)
BUILTIN(caml_neon_int16x8_slli)
BUILTIN(caml_neon_int16x8_srli)
BUILTIN(caml_neon_int16x8_srai)
BUILTIN(caml_neon_int16x8_ushl)
BUILTIN(caml_neon_int16x8_sshl)
BUILTIN(caml_neon_int16x8_dup)
BUILTIN(caml_neon_int16x8_bitwise_and)
BUILTIN(caml_neon_int16x8_bitwise_or)
BUILTIN(caml_neon_int16x8_bitwise_xor)
BUILTIN(caml_neon_int16x8_bitwise_not)
BUILTIN(caml_neon_int16x8_mul_low)
BUILTIN(caml_neon_int16x8_mul_high)
BUILTIN(caml_neon_int16x8_mul_high_unsigned)
BUILTIN(caml_neon_int16x8_mul_hadd_int32x4)
BUILTIN(caml_neon_int16x8_avg_unsigned)
BUILTIN(caml_neon_cvt_int16x8_int8x16_saturating)
BUILTIN(caml_neon_cvt_int16x8_int8x16_saturating_unsigned)
BUILTIN(caml_neon_cvtsx_int16x8_int32x4)
BUILTIN(caml_neon_cvtzx_int16x8_int32x4)
BUILTIN(caml_neon_cvtsx_int16x8_int64x2)
BUILTIN(caml_neon_cvtzx_int16x8_int64x2)

/* NEON int8x16 */
BUILTIN(caml_int8x16_low_of_int8)
BUILTIN(caml_int8x16_low_to_int8)
BUILTIN(caml_int8x16_const1)
BUILTIN(caml_neon_int8x16_insert)
BUILTIN(caml_neon_int8x16_extract)
BUILTIN(caml_neon_int8x16_dup)
BUILTIN(caml_neon_int8x16_add)
BUILTIN(caml_neon_int8x16_sub)
BUILTIN(caml_neon_int8x16_neg)
BUILTIN(caml_neon_int8x16_abs)
BUILTIN(caml_neon_int8x16_add_saturating)
BUILTIN(caml_neon_int8x16_add_saturating_unsigned)
BUILTIN(caml_neon_int8x16_sub_saturating)
BUILTIN(caml_neon_int8x16_sub_saturating_unsigned)
BUILTIN(caml_neon_int8x16_mul_unsigned_hadd_saturating_int16x8)
BUILTIN(caml_neon_int8x16_min)
BUILTIN(caml_neon_int8x16_max)
BUILTIN(caml_neon_int8x16_min_unsigned)
BUILTIN(caml_neon_int8x16_max_unsigned)
BUILTIN(caml_neon_int8x16_cmpeq)
BUILTIN(caml_neon_int8x16_cmpgt)
BUILTIN(caml_neon_int8x16_cmpltz)
BUILTIN(caml_neon_int8x16_bitwise_and)
BUILTIN(caml_neon_int8x16_bitwise_or)
BUILTIN(caml_neon_int8x16_bitwise_xor)
BUILTIN(caml_neon_int8x16_bitwise_not)
BUILTIN(caml_neon_int8x16_avg_unsigned)
BUILTIN(caml_neon_int8x16_sad_unsigned)
BUILTIN(caml_neon_cvtsx_int8x16_int16x8)
BUILTIN(caml_neon_cvtzx_int8x16_int16x8)
BUILTIN(caml_neon_cvtsx_int8x16_int32x4)
BUILTIN(caml_neon_cvtzx_int8x16_int32x4)
BUILTIN(caml_neon_cvtsx_int8x16_int64x2)
BUILTIN(caml_neon_cvtzx_int8x16_int64x2)

/* NEON int64x2 */
BUILTIN(caml_neon_int64x2_add)
BUILTIN(caml_neon_int64x2_sub)
BUILTIN(caml_neon_int64x2_neg)
BUILTIN(caml_neon_int64x2_bitwise_or)
BUILTIN(caml_neon_int64x2_bitwise_and)
BUILTIN(caml_neon_int64x2_bitwise_xor)
BUILTIN(caml_neon_int64x2_bitwise_not)
BUILTIN(caml_neon_int64x2_cmpeq)
BUILTIN(caml_neon_int64x2_cmpgt)
BUILTIN(caml_neon_int64x2_cmpltz)
BUILTIN(caml_neon_int64x2_slli)
BUILTIN(caml_neon_int64x2_srli)
BUILTIN(caml_neon_int64x2_ushl)
BUILTIN(caml_neon_int64x2_sshl)
BUILTIN(caml_neon_int64x2_dup)
BUILTIN(caml_neon_int64x2_extract)
BUILTIN(caml_neon_int64x2_insert)
BUILTIN(caml_neon_int64x2_dup_lane)
BUILTIN(caml_neon_vec128_shift_left_bytes)
BUILTIN(caml_neon_vec128_shift_right_bytes)
BUILTIN(caml_neon_cvt_int64x2_to_float64x2)
BUILTIN(caml_neon_cvt_int64x2_to_int32x4)
BUILTIN(caml_neon_cvt_int64x2_to_int32x4_low_saturating)

/* Shared vec128 operations */
BUILTIN(caml_simd_vec128_high_64_to_low_64)
BUILTIN(caml_simd_vec128_low_64_to_high_64)
BUILTIN(caml_simd_vec128_interleave_high_32)
BUILTIN(caml_simd_vec128_interleave_low_32)
BUILTIN(caml_simd_vec128_interleave_high_64)
BUILTIN(caml_simd_vec128_interleave_low_64)
BUILTIN(caml_neon_vec128_interleave_high_8)
BUILTIN(caml_neon_vec128_interleave_low_8)
BUILTIN(caml_neon_vec128_interleave_high_16)
BUILTIN(caml_neon_vec128_interleave_low_16)
BUILTIN(caml_neon_vec128_shuffle_8)

/* SSE blend ops (used in shared code) */
BUILTIN(caml_sse41_vec128_blend_32)
BUILTIN(caml_sse41_vec128_blend_64)
