(tests
 (names
  test_rig_remote
  test_rig_remote_lost
  test_rig_remote_own
  test_rig_remote_killed
  test_rig_remote_abort
  test_rig_remote_join
  test_rig_remote_ids)
 (modules
  test_rig_remote
  test_rig_remote_lost
  test_rig_remote_own
  test_rig_remote_killed
  test_rig_remote_abort
  test_rig_remote_join
  test_rig_remote_ids
  remote_job
  watchdog)
 (deps support/agent.exe support/controller.exe support/launched.exe)
 (libraries
  rig
  rig_remote
  rig_remote_proxy
  rig_remote_abi
  rig_support
  threads.posix
  unix
  windtrap))
